cmd/fpga_plugin/fpga_plugin.go, cmd/fpga_plugin/fpga_plugin_test.go
Also add `-mode` switch making the FPGA plugin announce AFU IDs instead if regions' interface IDs.
=> Announce region IDs instead of AFUs

cmd/fpga_plugin/fpga_plugin.go
Using glog.Fatal produces stacktrace, which looks quite scary
for this simple case:
$ ./fpga_plugin -mode bla
F0523 15:17:57.997937   11555 fpga_plugin.go:237] Wrong mode: bla
goroutine 1 [running]:
github.com/intel/intel-device-plugins-for-kubernetes/vendor/github.com/golang/glog.stacks(0xc420214000, 0xc42018e000, 0x42, 0x8f)
/home/ed/go/src/github.com/intel/intel-device-plugins-for-kubernetes/vendor/github.com/golang/glog/glog.go:769 +0xcf
github.com/intel/intel-device-plugins-for-kubernetes/vendor/github.com/golang/glog.(*loggingT).output(0xbf72c0, 0xc400000003, 0xc4200bea50, 0xba3309, 0xe, 0xed, 0x0)
/home/ed/go/src/github.com/intel/intel-device-plugins-for-kubernetes/vendor/github.com/golang/glog/glog.go:720 +0x32d
github.com/intel/intel-device-plugins-for-kubernetes/vendor/github.com …
=> use glog.Error when mode is incorrect

internal/deviceplugin/deviceplugin_test.go
Fixed make vet failure:
internal/deviceplugin/deviceplugin_test.go:190: declaration of "err"
shadows declaration at internal/deviceplugin/deviceplugin_test.go:150
Makefile:14: recipe for target 'vet' failed
make: *** [vet] Error 2
=> fix make vet

cmd/fpga_plugin/fpga_plugin.go, cmd/fpga_plugin/fpga_plugin_test.go
Added mode ("af" or "region") prefix to the resource name to
distingush between announced functions and regions, e.g.
intel.com/fpga-af-f7df405cbd7acf7222f144b0b93acd18
intel.com/fpga-region-ce48969398f05f33946d560708be108a
=> fpga: add prefix to FPGA resource name

internal/deviceplugin/deviceplugin_test.go
Fixed misspell warning pointed out by goreportcard.com:
```
misspell 83%
Misspell Finds commonly misspelled English words
intel-device-plugins-for-kubernetes/internal/deviceplugin/deviceplugin_test.go
Line 90: warning: "emtpy" is a misspelling of "empty" (misspell)
```
=> fix spelling mistake

cmd/fpga_plugin/fpga_plugin.go, internal/deviceplugin/deviceplugin.go
Fixed the following golint warnings:
```
./cmd/fpga_plugin/fpga_plugin.go:71:2: struct field fpgaId should be fpgaID
./cmd/fpga_plugin/fpga_plugin.go:78:44: func parameter fpgaId should be fpgaID
./cmd/fpga_plugin/fpga_plugin.go:104:8: var interfaceId should be interfaceID
./cmd/fpga_plugin/fpga_plugin.go:120:7: var interfaceIdFile should be interfaceIDFile
./cmd/fpga_plugin/fpga_plugin.go:156:8: range var fpgaId should be fpgaID
./cmd/fpga_plugin/fpga_plugin.go:254:6: range var fpgaId should be fpgaID
./cmd/fpga_plugin/fpga_plugin.go:254:14: should omit 2nd value from range; this loop is equivalent to `for fpgaId := range ...`
./internal/deviceplugin/deviceplugin.go:30:6: exported type DeviceInfo should have comment or be unexported
./internal/deviceplugin/deviceplugin.go:35:6: exported …
```
=> fix golint warnings

cmd/fpga_plugin/fpga_plugin_test.go, cmd/gpu_plugin/gpu_plugin_test.go, internal/deviceplugin/deviceplugin_test.go
This is done to fix https://goreportcard.com warnnigs:
gofmt 33%
Gofmt formats Go programs. We run gofmt -s on your code, where -s is for the "simplify" command
intel-device-plugins-for-kubernetes/cmd/fpga_plugin/fpga_plugin_test.go
Line 1: warning: file is not gofmted with -s (gofmt)
intel-device-plugins-for-kubernetes/internal/deviceplugin/deviceplugin_test.go
Line 1: warning: file is not gofmted with -s (gofmt)
intel-device-plugins-for-kubernetes/cmd/gpu_plugin/gpu_plugin_test.go
Line 1: warning: file is not gofmted with -s (gofmt)
intel-device-plugins-for-kubernetes/cmd/fpga_plugin/fpga_plugin.go
Line 1: warning: file is not gofmted with -s (gofmt)
=> reformatted *.go with gofmt -s -w

cmd/fpga_plugin/fpga_plugin_test.go
Fixed go_vet error:
Line 413: error: TestisValidPluginMode has malformed name: first letter after 'Test' must not be lowercase (vet)
=> fix go_vet error reported by goreportcard.com

Makefile
make lint always returs 0 even if there were errors found by golint
Fixed it by using golint command line option -set_exit_status and
checking golint return code
=> fix make lint

Makefile
When refactoring FPGA discovery I realized that upon test failures the coverage report isn't re-generated and the `test` target doesn't actually fail. Thus this correction.
=> Makefile: fail test target correctly upon errors in unit tests

cmd/fpga_plugin/devicecache/devicecache.go, cmd/fpga_plugin/devicecache/devicecache_test.go, cmd/fpga_plugin/fpga_plugin.go, cmd/fpga_plugin/fpga_plugin_test.go
This refactoring brings in device Cache running in its own
thread and scanning FPGA devices once every 5 secs. Then no timers
are used inside ListAndWatch() method of device managers and
no need to run scanning periodically in every device manager's
thread.
Cache generates update events and the plugin creates, updates or
deletes device managers on the fly upon receiving the events.
Introducing new modes of operations is a matter of adding a single
function converting and filtering the content of Cache.
=> fpga_plugin: refactor FPGA scans

cmd/fpga_plugin/devicecache/devicecache.go, cmd/fpga_plugin/devicecache/devicecache_test.go, cmd/fpga_plugin/fpga_plugin.go
In the `af` mode the plugin announces AFUs and tells kubelet
to pass only AFU ports to containers.
In the `region` mode the plugin announces region interfaces and tells
kubelet to pass only AFU ports to containers.
In the `regiondevel` mode the plugin announces region interfaces and
tells kubelet to pass AFU ports and FME devices to containers, so the
conteainers have full access to the regions.
=> add regiondevel mode to fpga_plugin

demo/intelfpga-job.yaml
Name of the test script has been changed recently, but job
spec hasn't been updated.
=> fix script name in fpga job spec

cmd/fpga_plugin/README.md, cmd/fpga_plugin/devicecache/devicecache.go, cmd/fpga_plugin/devicecache/devicecache_test.go
The latest refactoring of FPGA scanning accidentally removed
mode names from resource name prefixes.
Restore them back.
=> fpga: restore mode names in resource prefixes

Makefile
It's easier to refer <image-name>:latest tags in demo YAML files than to update all of them to use the latest hashes of the images.
=> Tag latest image build as 'latest'

cmd/fpga_admissionwebhook/README.md, deployments/fpga_admissionwebhook/deployment.yaml, deployments/fpga_admissionwebhook/mutating-webhook-configuration-tpl.yaml, deployments/fpga_admissionwebhook/service.yaml, scripts/webhook-create-signed-cert.sh, scripts/webhook-deploy.sh
Reduce cognitive load on our users by moving the instructions from webhook's README to a single `webhook-deploy.sh` script.
=> automate FPGA webhook deployment

cmd/fpga_admissionwebhook/README.md, cmd/fpga_admissionwebhook/fpga_admissionwebhook.go, cmd/fpga_admissionwebhook/fpga_admissionwebhook_test.go, deployments/fpga_admissionwebhook/deployment-tpl.yaml, scripts/webhook-create-signed-cert.sh, scripts/webhook-deploy.sh
In `orchestrated` mode the webhook parses requested resources and to translates
them to a container's ENV variables to let CRI hooks to program the FPGA with
requested bitstreams before starting the container.
=> fpga_admissionwebhook: add orchestrated mode

cmd/fpga_plugin/devicecache/devicecache.go
Device descovery can get EBUSY error when AFU is being programmed.
It causes plugin to crash.
This error should be ignored as this is valid use case.
This is harmless as afu will be rediscovered on the next run, when
reprogramming is done.
=> fpga: ignore EBUSY error when reading afu_id

cmd/fpga_crihook/main.go, cmd/fpga_crihook/main_test.go, cmd/fpga_crihook/testdata/stdin-incorrect-intel-annotation.json, cmd/fpga_crihook/testdata/stdin-no-annotations.json, cmd/fpga_crihook/testdata/stdin-no-intel-annotation.json
Check if container annotation com.intel.fpga.mode is set to
"intel.com/fpga-region". This annotation is set by device plugin.
So, the check should help to filter out unwanted workflow that
device plugin is not aware of.
=> fpga_crihook: check if intel annotation is set

Makefile, cmd/qat_plugin/qat_plugin.go
Makefile: fix format target
- Used gofmt instead of go fmt to show the changes and simplify the code
- Made 'make format' to exit with error when formatting is not correct
Fixed formatting errors in QAT plugin code to make Travis CI happy
Fixes: #57
=> fix make format

cmd/gpu_plugin/gpu_plugin.go
DRM control node is deprecated and removed by latest kernel.
This will skip possible drm control node found on host.
Signed-off-by: Zhenyu Wang <zhenyuw@linux.intel.com>
=> gpu_plugin: skip drm control node

build/docker/intel-fpga-plugin.Dockerfile, build/docker/intel-gpu-plugin.Dockerfile, build/docker/intel-qat-plugin.Dockerfile
This fixes build error:
```
github.com/intel/intel-device-plugins-for-kubernetes/internal/deviceplugin
../../internal/deviceplugin/server.go:186: cannot use srv (type *server) as type v1beta1.DevicePluginServer in argument to v1beta1.RegisterDevicePluginServer:
*server does not implement v1beta1.DevicePluginServer (wrong type for Allocate method)
have Allocate("context".Context, *v1beta1.AllocateRequest) (*v1beta1.AllocateResponse, error)
want Allocate("github.com/intel/intel-device-plugins-for-kubernetes/vendor/golang.org/x/net/context".Context, *v1beta1.AllocateRequest) (*v1beta1.AllocateResponse, error)
```
=> bump up Go version for Docker builds

cmd/fpga_crihook/main.go
Added -S <device number> parameter to fpgaconf command line to
ensure usage of allocated device.
=> fpga_crihook: specify socket number when programming device

cmd/fpga_crihook/main.go
Annotation value has been changed in FPGA plugin code recently.
Updated fpga_crihook to use the same value.
=> fpga_crihook: fix annotation value

.travis.yml, Makefile
Added 'demos' and <demo image name> targets to the Makefile
Added 'make demos' to the TravisCI configuration file
@swatisehgal I excluded crypto-perf from the build due to the issue #81. Please, include it back after fixing the issue. Thanks.
=> CI: check if demos can be built

cmd/fpga_plugin/fpga_plugin.go, cmd/fpga_plugin/fpga_plugin_test.go
When the device's firmware crashes the OPAE driver reports all properties of the device as a stream of binary ones. This effectively makes interface and afu IDs look like `ffffffffffffffffffffffffffffffff`.
Mark such devices as Unhealthy.
closes #77
=> fpga_plugin: indicate unhealthy devices

cmd/qat_plugin/qat_plugin.go
Fixed misspell warning in QAT plugin code:
Line 153: warning: "Unknwon" is a misspelling of "Unknown" (misspell)
=> QAT: fixed spelling

cmd/gpu_plugin/gpu_plugin.go, cmd/gpu_plugin/gpu_plugin_test.go
The DRM driver of Intel i915 GPUs allows sharing one device between many containers.
Make it possible to use the same device from different containers. The exact number of containers sharing the same device can be limited with the new option `-shared-dev-num` set to 1 by default.
closes #53
=> gpu_plugin: add -shared-dev-num option

Gopkg.lock, Gopkg.toml, Makefile, build/docker/intel-fpga-plugin.Dockerfile, cmd/fpga_admissionwebhook/controller.go, cmd/fpga_admissionwebhook/controller_test.go, cmd/fpga_admissionwebhook/fpga_admissionwebhook.go, cmd/fpga_admissionwebhook/fpga_admissionwebhook_test.go, cmd/fpga_admissionwebhook/patcher.go, cmd/fpga_admissionwebhook/patcher_test.go, cmd/fpga_crihook/main.go, cmd/fpga_crihook/main_test.go, cmd/fpga_plugin/fpga_plugin.go, cmd/fpga_plugin/fpga_plugin_test.go, cmd/gpu_plugin/gpu_plugin.go, cmd/gpu_plugin/gpu_plugin_test.go, cmd/qat_plugin/README.md, cmd/qat_plugin/qat_plugin.go, cmd/qat_plugin/qat_plugin_test.go, deployments/fpga_admissionwebhook/deployment-tpl.yaml, internal/deviceplugin/manager.go, internal/deviceplugin/manager_test.go, internal/deviceplugin/server.go, internal/deviceplugin/server_test.go, pkg/debug/debug.go, vendor/github.com/pkg/errors/LICENSE, vendor/github.com/pkg/errors/errors.go, vendor/github.com/pkg/errors/stack.go
@pohly has discovered recently that the command `make test WHAT=internal/deviceplugin` fails because it runs `go test -args -logtostderr` even though the package under test doesn't use glog:
```
$ make WHAT=internal/deviceplugin test
flag provided but not defined: -logtostderr
```
glog is inconvenient since it redirects output from file to stderr only through setting its command line flags. And this doesn't fit nicely with one of the 12 cloud app factors (https://12factor.net/logs).
I think that for error tracing it's better to use annotated errors (annotated with a stack trace). See this blog post https://dave.cheney.net/tag/error-handling
For optional debugging output it should be enough to use a very small home-grown `debug` package.
For user visible output the `fmt`'s capabilities are …
=> Proposal for logging and error tracing

cmd/fpga_admissionwebhook/fpga_admissionwebhook.go, cmd/fpga_admissionwebhook/patcher.go, cmd/fpga_admissionwebhook/patcher_test.go
If there's no known mapping for a resource name in the `fpga.intel.com` namespace then deny such request.
=> webook: deny requests for unknown FPGA resources

internal/deviceplugin/server.go
If `grpc.Dial()` call fails, a `nil` connection object is returned. Don't defer a `conn.Close()` call before checking the error value.
=> deviceplugin: don't call method on a nil value.

deployments/fpga_plugin/build-initcontainer-image.sh, deployments/fpga_plugin/fpga_plugin.yaml, deployments/fpga_plugin/intel-fpga-initcontainer.Dockerfile
Container provides FPGA programming wrappers for OPAE and OpenCL and their dependencies in /opt/intel/fpga-sw directory. Wrappers will be called by CRI hook to program FPGA device with green bitstreams.
=> create initcontainer for FPGA plugin daemonset

demo/build-image.sh
Docker documentation recommends configuring proxy in
a Docker client configuration file ~/.docker/config.json for Docker
version >= 17.07: https://docs.docker.com/network/proxy/
Using --build-arg for this purpose is not recommended, hence
removing.
=> demos: get rid of using --build-arg to pass proxy to the Docker

cmd/qat_plugin/qat_plugin.go, cmd/qat_plugin/qat_plugin_test.go, demo/crypto-perf-dpdk-pod-requesting-qat.yaml
- To ensure that the device plugin continues to run in case a certain QAT device
family is not detected on the node
- Updated the extended resource name to qat/generic in demo/crypto-perf-dpdk-pod-requesting-qat.yaml file
=> Fixing minor bugs with QAT plugin

cmd/fpga_plugin/fpga_plugin.go, cmd/fpga_plugin/fpga_plugin_test.go
This helps to avoid restarting pods with fpga_plugin by DaemonSet if the node doesn't have the OPAE driver loaded.
=> fpga_plugin: don't exit if OPAE driver is not loaded

cmd/fpga_crihook/main.go
Different versions of OPAE tool fpgaconf use different command line
options to specify socket number. Latest version uses -S, which CRI-O
hook used so far.
However, fpgaconf in initcontainer comes from older OPAE version, which
uses -s option for the same purpose. This caused fpgaconf and CRI-O hook
to fail with "Invalid cmdline options".
Used 'fpgaconf-wrapper -s' in the CRI-O hook to fix this.
Signed-off-by: Ed Bartosh <eduard.bartosh@intel.com>
=> fpga_crihook: use -s fpgaconf option

Makefile
Docker documentation recommends configuring proxy in
a Docker client configuration file ~/.docker/config.json for Docker
version >= 17.07: https://docs.docker.com/network/proxy/
Using --build-arg for this purpose is not recommended, hence
removing.
=> Makefile: get rid of using --build-arg to pass proxy to the Docker

deployments/fpga_plugin/intel-fpga-initcontainer.Dockerfile
Current configuration has incorrect keywords that caused
CRI not to call prestart hook.
=> fix CRI hook configuration in initcontainer

demo/build-image.sh
Added --rm command line option to remove intermediate images
Tagged with git revision and 'devel' tags the same way as it's done
for other images
=> improve building demo images

demo/test-fpga-region.yml
Added IPC_LOC capability to NLB3 workload failure:
[8][ERROR][accelerator::allocate_buffer] Could not allocate buffer
[8][ERROR][nlb3] failed to allocate DSM workspace.
Error: configuration failed.
=> fix fpga-region pod definition

demo/intelfpga-job.yaml, demo/test-fpga-region.yml
Updated FPGA pods that use ubuntu-demo-opae image to
use 'devel' tag.
=> demo: use ubuntu-demo-opae:devel in FPGA pods

.travis.yml, Makefile, build/docker/build-image.sh, demo/build-image.sh, deployments/fpga_plugin/build-initcontainer-image.sh
Added alternative builder for project images: [buildah](https://github.com/containers/buildah)
Considering that some of our plugins use CRI-O runtime it could be
a good idea to get rid of docker as a builder. It should allow us
not to run docker daemon at all, even for build purposes.
Kubernetes also goes this way encouraging users to switch to CRI
runtimes (CRI-O and containerd), so having non-docker builds supported
looks good from this perspective too.
=> Build images with buildah

.travis.yml
`github.com/golang/lint/golint` doesn't exist and I proposed the change off the `golint` documentation.
=> Fix golint failure

internal/deviceplugin/manager.go
Goroutines don't capture the values of the variables they reference from their
outter scope. As result the last value of `devType` is used at the moment
the goroutine runs.
Pass the correct value of `devType` to the goroutine call.
closes #113
=> internal: isolate goroutine from its outter scope

deployments/fpga_admissionwebhook/mappings-collection.yaml
Added DCP 1.0 Arria10 region and compress AFU ids
to the mapping collection to be able to work with
DCP 1.0 bitstreams.
This is also an enabler for FPGA demo that uses compress.aocx,
which is not compilable by aoc compiler from DCP 1.1
=> fpga: add support for Arria10 DCP 1.0

cmd/qat_plugin/README.md, deployments/qat_plugin/qat_plugin.yaml, deployments/qat_plugin/qat_plugin_default_configmap.yaml
For easier deployments, fetch plugin command line arguments from ConfigMap.
When using ConfigMaps, qat_plugin.yaml needs no changes and can always
be used as is.
qat_plugin_default_configmap.yaml uses built-in defaults.
=> qat: deployment: set parameters via ConfigMap

cmd/gpu_plugin/README.md, demo/intelgpu-job.yaml
There are a two typos in the GPU documentation which I discovered when running the demo in the README file:
- The demo file is called `intelgpu-job.yaml` instead of `intelgpu_job.yaml`
- The container which is created is tagged `ubuntu-demo-opencl:devel` instead of `ubuntu-demo-opencl:latest`
=> Fix a couple of typos in the GPU documentation

demo/crypto-perf/Dockerfile
This change:
* adds cloning and building of QAT-enabled DPDK to the Dockerfile
* disables unnecessary compilation of DPDK kernel modules which depend on the host kernel version
* fixes issue with missing ./resolv.conf file and dpdk directory
=> demo: update crypto-perf Dockerfile

demo/openssl-qat-engine-pod.yaml, demo/openssl-qat-engine/Dockerfile, demo/readme.md
I'm submitting this PR for early review. TODOs to be completed before merging.
Add:
* Dockerfile that builds a container with OpenSSL 1.1.1 + QAT Engine
* Sample openssl-qat-engine-pod deployment yaml
The demo deployment yaml has the following dependencies:
* kata-runtime is installed and registered as the untrusted workload
handler
* QAT virtual function device configuration(s) (from QAT_Engine repo) are
available  in /etc for the target hardware.
TODOs:
* readme.md
* move to RuntimeClass
=> demo: add OpenSSL QAT Engine demo files

Makefile
This build was excluded from the 'make demos' targets as
it was failing. Now the build is fixed, adding the build back.
=> Makefile: enable crypto-perf build

deployments/fpga_admissionwebhook/mappings-collection.yaml
Current mappings break admissionwebhook deployment with this
kind of errors:
```
Invalid value: "arria10_dcp1.0": a DNS-1123 subdomain must consist of
lower case alphanumeric characters, '-' or '.', and must start and end
with an alphanumeric character (e.g. 'example.com', regex used for
validation is
'[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'
```
New mappings conform DNS-1123 regexp. They have been tested by the
compression demo and known to work.
=> fpga: add mappings for dpc1.0 resources

cmd/fpga_admissionwebhook/patcher.go
Region regexp doesn't allow to have dots, which
results in incorrect matching of arria10.dcp1.0 region.
=> admissionwebhook: fix region regexp

cmd/qat_plugin/qat_plugin.go
An `Allocate()` request can be used to allocate resources for many
containers thus `counter` needs to be reset for each container
response.
=> qat: fix numbering of env vars

Makefile
I forgot to remove `internal` from Makefile -> removing it now.
=> drop the internal folder from checks

demo/readme.md
Working link for QAT Device Plugin with DPDK demo screen-cast, as previous video had become archived.
=> New link to QAT screencast

pkg/deviceplugin/server.go, pkg/deviceplugin/server_test.go
The variable which gets assigned a value from a list element on every
loop iteration is always the same. Getting a pointer to this variable
results in the same pointer on every iteration.
Rather get a pointer to the actual element of the list.
=> deviceplugin: fix duplicate device nodes in ContainerResponse

cmd/fpga_admissionwebhook/controller.go, cmd/fpga_admissionwebhook/controller_test.go, cmd/fpga_admissionwebhook/fpga_admissionwebhook.go, cmd/fpga_admissionwebhook/fpga_admissionwebhook_test.go, cmd/fpga_admissionwebhook/patcher.go, cmd/fpga_admissionwebhook/patcher_test.go
CRDs for AF or Region mappings are scoped to namespaces. So an
admitted pod has to be mutated with CRDs existing in the same
namespace as the pod's.
Closes #167
=> fpga: mutate pods with CRDs from its corresponding namespace

cmd/gpu_plugin/gpu_plugin.go, cmd/gpu_plugin/gpu_plugin_test.go
Let a user know the plugin can't find any Intel GPU if that's the case. It might be cumbersome to realize that the plugin runs on a host which doesn't have any Intel GPUs.
Also make the code less nested for better readability.
=> gpu: add log messages for not found cards

cmd/qat_plugin/kerneldrv/kerneldrv.go
In adf_ctl output, qat_devX is a sequence number that includes both
PF and VF devices:
qat_dev0 - type: c6xx,  inst_id: 0,  node_id: 1,  bsf: 84:00.0, #accel: 5 #engines: 10 state: up
qat_dev1 - type: c6xx,  inst_id: 1,  node_id: 1,  bsf: 85:00.0, #accel: 5 #engines: 10 state: up
qat_dev2 - type: c6xx,  inst_id: 2,  node_id: 1,  bsf: 86:00.0, #accel: 5 #engines: 10 state: up
qat_dev3 - type: c6xxvf,  inst_id: 0,  node_id: 1,  bsf: 84:01.0, #accel: 1 #engines: 1 state: up
qat_dev4 - type: c6xxvf,  inst_id: 1,  node_id: 1,  bsf: 84:01.1, #accel: 1 #engines: 1 state: up
...
X cannot be used as the config file identified because it does not match
the real id of the device. inst_id gives this so move to use that to find
the right config file.
Signed-off-by: Mikko Ylinen …
=> qat_plugin: kerneldrv: get device.id from inst_id

cmd/qat_plugin/kerneldrv/kerneldrv.go, cmd/qat_plugin/kerneldrv/kerneldrv_test.go
When IOMMU is on in the system, the physical function (PF)
devices cannot be used. This prevented using kerneldrv as it
was only written to work with PFs.
However, QAT bare metal functions can also be used when IOMMU
is enabled. In this case, they must be used via virtual functions
(VF).
This commit makes it possible to use kerneldrv when IOMMU is
on. The added side benefit is we can now slice the same QAT HW
for both "dpdk" and "kernel" usages simultaneously.
=> qat_plugin: kerneldrv: register VF devices when IOMMU is on

cmd/qat_plugin/README.md, demo/crypto-perf-dpdk-pod-requesting-qat.yaml
Make sure IPC_LOCK capability is set to get DPDK to mmap() hugepages.
=> crypto-perf: add IPC_LOCK to ensure mmap() works

demo/openssl-qat-engine/Dockerfile, demo/openssl-qat-engine/Dockerfile.clear
v0.5.41 QAT_Engine allows us to drop pulling external openssl
git repository.
=> demo: update OpenSSL QAT engine version in containers

build/docker/intel-fpga-admissionwebhook.Dockerfile, build/docker/intel-fpga-plugin.Dockerfile, deployments/fpga_plugin/intel-fpga-initcontainer.Dockerfile
1) fpga-admissionwebhook and fpga-plugin moved to Distroless
2) fpga-initcontainer moved to Clearlinux 
Signed-off-by: Hector Augusto Garcia Baleon <hector.augusto.garcia.baleon@intel.com>
=> Move FPGA plugin to Distroless and Clearlinux

Jenkinsfile
This Jenkinsfile provides basic CI based on the .travis.yml
which ports the travis behaviour to Jenkins by checking the
following make targets:
- make format
- make lint
- make
- make vet
- make cyclomatic-check
- make test
- make images
- make images BUILDER=buildah
- make demos
- make demos BUILDER=buildah
The main intention of this commit is to provide an starting point
where anybody can improve the coverage at anytime and get PR cheks
on Jenkins.
=> jenkins: Add initial jenkinsfile

build/docker/intel-qat-plugin.Dockerfile, demo/openssl-qat-engine/Dockerfile, demo/openssl-qat-engine/Dockerfile.clear
Also, move from ENV to ARG to be able to override the versions
using --build-arg option.
Note: releases qat1.7.l.4.3.0-00033 and older do not have consistent
download URLs so wget'ing those will fail from this commit onwards.
=> demo: update OpenSSL QAT engine and QAT HAL versions in containers

demo/screencast.sh, demo/test-fpga-region.yml, deployments/fpga_admissionwebhook/mappings-collection.yaml
- Ordered collection in DCP release/region/afus order for simpler
maintenance.
- Got rid of ambiguous entries without dcp releases, e.g. Arria10,
Arria10-nlb3 etc.
=> fpga: update mapping collection

build/docker/intel-fpga-admissionwebhook.Dockerfile, build/docker/intel-fpga-initcontainer.Dockerfile, deployments/fpga_admissionwebhook/deployment-tpl.yaml, deployments/fpga_plugin/fpga_plugin.yaml
- used ENTRYPOINT instead of CMD in plugin and admission webhook
Dockerfiles to avoid duplicating commands in the pod yamls
- fixed path to deploy.sh script in fpga initcontainer Dockerfile
=> fpga: fix deployment setup

demo/clearlinux-demo-opae/0001-OPAE-in-containers-don-t-enumerate-missing-device.patch, demo/clearlinux-demo-opae/Dockerfile
On the host with multiple cards installed it might be case
that not all of them are exposed to the container.
Fix OPAE library to ignore devices that are not available.
=> Fix OPAE library to work with multiple cards

cmd/fpga_admissionwebhook/README.md, cmd/fpga_crihook/README.md, cmd/fpga_plugin/README.md, demo/opae-nlb-demo/test_fpga.sh, demo/readme.md, demo/screencast.sh
- Fixed documentation for the CRI-O hook
- Updated the screencast.sh to remove references to the 'Acceleration Stack for Runtime' tarball which is not needed anymore
- Created and updated the link to a new screencast for the NLB3 demo
=> fpga: fixed documentation and demo

Makefile, cmd/fpga_admissionwebhook/README.md, cmd/fpga_crihook/README.md, cmd/fpga_plugin/README.md, demo/intelfpga-job.yaml, demo/opae-nlb-demo/test_fpga.sh, demo/readme.md, demo/screencast.sh, demo/test-fpga-region.yaml, deployments/fpga_admissionwebhook/deployment-tpl.yaml, deployments/fpga_plugin/fpga_plugin.yaml, deployments/gpu_plugin/gpu_plugin.yaml, deployments/qat_dpdk_app/base/crypto-perf-dpdk-pod-requesting-qat.yaml, deployments/qat_plugin/qat_plugin.yaml, deployments/qat_plugin/qat_plugin_kernel_mode.yaml
=> release 0.15.0

cmd/fpga_crihook/main.go, cmd/fpga_crihook/main_test.go
Fixed the following warnings:
- main.go:170:17: Error return value of `errors.Errorf` is not checked (errcheck)
errors.Errorf("Environment variable %s%s is not set", fpgaAfuEnvPrefix, num)
^
- main.go:272:3: ineffectual assignment to `err` (ineffassign)
err = port.PR(bitstream, false)
^
- main.go:55:3: U1000: field `Resources` is unused (unused)
Resources struct {
- main.go:100:105: newHookEnv - result 1 (error) is always nil (unparam)
func newHookEnv(sysFsPrefix, bitstreamDir string, config string, execer utilsexec.Interface) (*hookEnv, error) {
=> Fix golangci-lint findings

cmd/fpga_admissionwebhook/fpga_admissionwebhook.go
In the pods generated automatically by Deployment/ReplicaSets
fields name and namespace might be missing.
We can use information about namespace from request itself.
=> Fix admission hook for pods generated by ReplicaSet

.travis.yml, Jenkinsfile, Makefile, build/docker/build-image.sh, build/docker/intel-fpga-admissionwebhook.Dockerfile, build/docker/intel-fpga-initcontainer.Dockerfile, build/docker/intel-fpga-plugin.Dockerfile, build/docker/intel-gpu-plugin.Dockerfile, build/docker/intel-qat-plugin.Dockerfile, demo/build-image.sh
This takes ideas and changes from #212 but goes back to vendor/ with container builds. vendor/ is created from go mod cache.
=> travis: Use vendored code for container builds

build/docker/intel-fpga-admissionwebhook.Dockerfile, build/docker/intel-fpga-initcontainer.Dockerfile, build/docker/intel-fpga-plugin.Dockerfile, build/docker/intel-gpu-plugin.Dockerfile, build/docker/intel-qat-plugin.Dockerfile, scripts/copy-modules-licenses.sh
This commit adds a script that is (primarily) used in Dockerfiles
to install runtime Go dependencies' LICENSE/NOTICE files into the
image and modifies the Dockerfiles to use the script.
=> images: add LICENSEs

cmd/gpu_plugin/README.md, cmd/qat_plugin/README.md, deployments/gpu_plugin/gpu_plugin.yaml
The default deployment gives rather wide host mounts. We can limit
the mounts only to the subdirectories the plugin needs and mount
them read-only.
Also, add notes that both QAT and GPU plugins can be run as non-root
user.
Fixes: #228
=> deployments/gpu_plugin: limit host mounts

cmd/fpga_plugin/README.md, deployments/fpga_plugin/fpga_plugin.yaml
The default deployment gives rather wide host mounts.
Limited sysfs mount only to the subdirectory the plugin
needs.
Mounted sysfs and dev  mounts read-only.
Added notes that FPGA plugin can be run as non-root user.
=> deployments/fpga_plugin: limit host mounts

demo/opae-nlb-demo/Dockerfile
OPAE-NLB-demo: install content in /usr/local in order to get clean scan results from BDBA
Addresses https://github.com/intel/intel-device-plugins-for-kubernetes/issues/227 
Signed-off-by: Hector Augusto Garcia Baleon hector.augusto.garcia.baleon@intel.com
=> fpga: Install content in /usr/local for the nlb-demo

deployments/fpga_admissionwebhook/deployment-tpl.yaml
Since Kubernetes v1.16 release, DaemonSet, Deployment, StatefulSet, and ReplicaSet in the extensions/v1beta1 and apps/v1beta2 API groups have been deprecated. This PR migrates the webhook deployment to use apps/v1 instead of extensions/v1beta1 and add the selector part also required by the migration.
Signed-off-by: Hector Augusto Garcia Baleon <hector.augusto.garcia.baleon@intel.com>
=> fpga: Migrate webhook deployment to use the apps/v1 API

deployments/fpga_plugin/fpga_plugin.yaml
runtime uses /dev/termination-log to write container termination
messages. If this file doesn't exist on the host the runtime tries
to create it. As /dev is read-only for intel-fpga-plugin container
attempt to create /dev/termination-log fails with this error:
```
Warning Failed kubelet, device-plugins-kubernetes-clearlinux-14-4.novalocal  Error:
container create failed: container_linux.go:345: starting container process caused
"process_linux.go:430: container init caused \"rootfs_linux.go:58:
mounting \\\"/var/lib/kubelet/pods/d7262db5-e3fc-4b7b-bc2e-da245f600c4b/containers/intel-fpga-plugin/cddd0f76\\\"
to rootfs \\\"/var/lib/containers/storage/overlay/edd75bb94b1b4cf93ae1ea5c064945169fb329d0abdb56b7621cddfc721f6eda/merged\\\"
at …
```
=> fpga_plugin: move termination-log out of /dev

demo/opae-nlb-demo/Dockerfile
- Removed Sphynx from the list of bundles as it brings python-basic3,
which triggers this exception:
```
Step 9/18 : RUN cd /usr/src/opae/opae-sdk-${OPAE_RElEASE} \
&&  patch -p1 < 0001-OPAE-in-containers-don-t-enumerate-missing-device.patch \
&&   mkdir build &&     cd build \
&&     cmake .. -DBUILD_ASE=0 -DCMAKE_INSTALL_PREFIX=/usr \
-DCMAKE_SKIP_RPATH=true &&     make xfpga nlb0 nlb3
...
-- Found Sphinx: /usr/sbin/sphinx-build
-- Found PythonInterp: /usr/sbin/python (found suitable version "3.8.1", minimum required is "2.7")
-- Found Perl: /usr/sbin/perl (found version "5.28.2")
-- Found PythonInterp: /usr/sbin/python (found version "3.8.1")
Traceback (most recent call last):
File "/usr/src/opae/opae-sdk-1.3.2-1/build/platforms/scripts/afu_platform_config_main/do_zip.py", line 8, in …
```
=> Fix opae-demo-nlb build

README.md
Improve the front page README (landing page).
Break the structure down to individual plugin sections and add details on what they are/do, and where to find the code and demos.
=> docs: improve frontpage README

.travis.yml, Jenkinsfile, README.md, build/docker/intel-vpu-plugin.Dockerfile, cmd/vpu_plugin/README.md, cmd/vpu_plugin/vpu_plugin.go, cmd/vpu_plugin/vpu_plugin_test.go, demo/intelvpu-job.yaml, demo/ubuntu-demo-openvino/Dockerfile, demo/ubuntu-demo-openvino/do_classification.sh, deployments/vpu_plugin/vpu_plugin.yaml, go.mod, go.sum
This patch is to support Intel VCAC-A card (with MyriadX 2485 VPUs), for other
later on VPUs, we will reuse this plugin and add support.
VCAC-A board info is at:
https://www.intel.com/content/dam/www/public/us/en/documents/datasheets/media-analytics-vcac-a-accelerator-card-by-celestica-datasheet.pdf
Also add openvino HDDL VPU demo for Intel VCAC-A card.
=> VPU: Add Intel Movidius MyriadX VPU plugin support

cmd/gpu_plugin/gpu_plugin.go
If we do not find any GPU devices, for whatever reason
(such as missing or unparsable /dev or /sys files), do not
error and quit, just return an empty device tree (indicating
we have no devices on this node).
This is preferable as we will then not enter a retry-death-spin
type scenario.
Fixes: #260
=> gpu: do not fail if no GPU devices found

cmd/qat_plugin/README.md, deployments/qat_dpdk_app/base/crypto-perf-dpdk-pod-requesting-qat.yaml
crypto-perf instructions were outdated and hand implicit
assumptions about the environment. More specifically:
Clear Linux builds DPDK libraries as shared so for the
compress and crypto test applications to run, the memory and
QAT PMD libraries must be explicitly preloaded using '-d' parameter.
Also, the test-crypto1 and test-compress1 deployments expect the
cluster is configured with CPU Manager's static policy.
=> qat: README: clarify crypto-perf usage

cmd/fpga_plugin/dfl_test.go, cmd/fpga_plugin/fpga_plugin.go, cmd/fpga_plugin/opae_test.go, cmd/gpu_plugin/gpu_plugin.go, cmd/qat_plugin/dpdkdrv/dpdkdrv.go, cmd/qat_plugin/kerneldrv/kerneldrv.go, cmd/vpu_plugin/vpu_plugin.go, go.mod, go.sum, pkg/deviceplugin/api.go, pkg/deviceplugin/manager_test.go, pkg/deviceplugin/server.go, pkg/deviceplugin/server_test.go
Implemented passing topology information from device plugins to kubelet in ListAndWatch responses.
topology.go and topology_test.go were taken from
https://github.com/intel/cri-resource-manager/blob/v0.2.0/pkg/sysfs/ with little changes on top of them.
=> Topology hints

cmd/gpu_plugin/README.md, deployments/gpu_plugin/base/intel-gpu-plugin.yaml, deployments/gpu_plugin/base/kustomization.yaml, deployments/gpu_plugin/kustomization.yaml, deployments/gpu_plugin/overlays/namespace_kube-system/add-namespace-kube-system.yaml, deployments/gpu_plugin/overlays/namespace_kube-system/kustomization.yaml, deployments/gpu_plugin/overlays/nfd_labeled_nodes/add-nodeselector-intel-gpu.yaml, deployments/gpu_plugin/overlays/nfd_labeled_nodes/kustomization.yaml
- Default deployment: `kubectl apply -k deployments/gpu_plugin`
- Variant: deploy only on nodes with Intel GPU label by NFD
`kubectl apply -k deployments/gpu_plugin/overlays/nfd_labeled_nodes`
- GPU plugin README updated.
Signed-off-by: Antti Kervinen <antti.kervinen@intel.com>
=> gpu_plugin: add kustomizations

cmd/fpga_admissionwebhook/README.md, cmd/fpga_plugin/README.md
Not touching "orchestration programmed". Fixing only instances where
this refers directly to the mode recognized by the webhook-deploy.sh
script.
Signed-off-by: Antti Kervinen <antti.kervinen@intel.com>
=> fpga_plugin: orchestration/orchestrated fixed in READMEs

cmd/fpga_admissionwebhook/README.md, cmd/fpga_crihook/README.md, cmd/fpga_plugin/README.md, cmd/gpu_plugin/README.md, cmd/qat_plugin/README.md, cmd/vpu_plugin/README.md
go get'ing does not work due to our k8s.io/kubernetes dependency
so guide users to use git clone to get the code.
Fixes: #290
=> READMEs: use git clone to get the code

cmd/vpu_plugin/README.md, deployments/vpu_plugin/base/intel-vpu-plugin.yaml, deployments/vpu_plugin/base/kustomization.yaml, deployments/vpu_plugin/kustomization.yaml, deployments/vpu_plugin/overlays/namespace_kube-system/add-namespace-kube-system.yaml, deployments/vpu_plugin/overlays/namespace_kube-system/kustomization.yaml
- Default deployment: `kubectl apply -k deployments/vpu_plugin`
- Default deployment does not specify namespace anymore
(was: `kube-system`)
- Variant: deploy to `kube-system` instead of user-defined namespace
(or `default`)
`kubectl apply -k deployments/vpu_plugin/overlays/namespace_kube-system`
- VPU plugin README updated.
- Change volume mounts to readonly when possible
=> vpu_plugin: add kustomizations

scripts/fpga-plugin-prepare-for-kustomization.sh
The certificate got signed for wrong service name (fallback default
"webhook-svc") due to incorrectly passed parameter. This showed as
"http: TLS handshake error from ... tls: bad certificate"
error in webhook pod logs.
Fixes: #303
Signed-off-by: Antti Kervinen <antti.kervinen@intel.com>
=> FPGA kustomization: fix signing certificate

deployments/qat_plugin/base/intel-qat-plugin.yaml, pkg/deviceplugin/api.go
Previously, /dev/vfio/xx devices were just arbitrary strings and the
plugin did not need the devices for anything. After adding the checks
for topology hints, we need to read the devices attached to those so
the device nodes must be bind mounted in the plugin container.
Moreover, be more verbose about any errors coming from the topology code.
=> qat: mount VFIO devices for topology hints to work

Makefile, build/docker/intel-fpga-admissionwebhook.Dockerfile, build/docker/intel-fpga-initcontainer.Dockerfile, build/docker/intel-fpga-plugin.Dockerfile, build/docker/intel-gpu-plugin.Dockerfile, build/docker/intel-qat-plugin.Dockerfile, build/docker/intel-vpu-plugin.Dockerfile, demo/crypto-perf/Dockerfile, demo/intelfpga-job.yaml, demo/opae-nlb-demo/Dockerfile, demo/test-fpga-region.yaml, deployments/fpga_admissionwebhook/base/intel-fpga-webhook-deployment.yaml, deployments/fpga_admissionwebhook/deployment-tpl.yaml, deployments/fpga_plugin/base/intel-fpga-plugin-daemonset.yaml, deployments/fpga_plugin/fpga_plugin.yaml, deployments/gpu_plugin/base/intel-gpu-plugin.yaml, deployments/qat_dpdk_app/base/crypto-perf-dpdk-pod-requesting-qat.yaml, deployments/qat_plugin/base/intel-qat-kernel-plugin.yaml, deployments/qat_plugin/base/intel-qat-plugin.yaml, deployments/vpu_plugin/base/intel-vpu-plugin.yaml
=> Prepare for release-0.17

build/docker/intel-fpga-admissionwebhook.Dockerfile, build/docker/intel-fpga-initcontainer.Dockerfile, build/docker/intel-fpga-plugin.Dockerfile, build/docker/intel-gpu-plugin.Dockerfile, build/docker/intel-qat-plugin.Dockerfile, build/docker/intel-vpu-plugin.Dockerfile, demo/crypto-perf/Dockerfile, demo/opae-nlb-demo/Dockerfile
swupd os-install fails (clearlinux/swupd-client/issues/1369) if
"--bundles=os-core" is used. It was confirmed that os-core is
always installed first regardless of what other --bundles are
specified.
To get the builds working, we move to rely on that implicit os-core
install.
Fixes: #330
=> images: make os-core install implicit

build/docker/intel-vpu-plugin.Dockerfile
Running ldconfig seems to fix last build issue(vpu plugin image):
```
...
pkg-config: error while loading shared libraries: libglib-2.0.so.0: cannot open shared object file: No such file or directory
...
##[error]Process completed with exit code 2.
```
This blocks a lot of pending PRs, so please review & merge. Thanks.
Fixes #336
=> fix image build failure

Makefile, build/docker/build-image.sh
Users had no options to specify extra builder arguments to $BUILDER.
With this patch it's possible, e.g., to build QAT plugin with kernel
mode support:
make intel-qat-plugin EXTRA_BUILD_ARGS="--build-arg TAGS_KERNELDRV=kernel
Fixes: #234
=> build: pass extra builder arguments from users

cmd/qat_plugin/kerneldrv/kerneldrv.go
Kerneldrv checks for available devices based on adf_ctl output.
We only accepted two cases: PFs if IOMMU is off and VFs if IOMMU
is on.
The right check is to only skip PFs if IOMMU is on and allow other
cases. This fixes two scenarios: when run in VMs, we accept VFs
regardless of (v)IOMMU presence.
Moreover, do not hard code domain '0000:' because it is not the
case always.
=> qat: kerneldrv: fix device registration when run in VMs

deployments/vpu_plugin/base/intel-vpu-plugin.yaml
Previously, /dev/ion device was just arbitrary string and the plugin
did not need the device for anything. After adding the checks for
topology hints, the device node must be bind mounted in the plugin
container.
=> vpu: mount myd_ion device for topology hints to work

demo/ubuntu-demo-openvino/Dockerfile, demo/ubuntu-demo-openvino/do_classification.sh
OVC upgraded hddldaemon to use R4, so we should do so too.
also change the openvino tgz file download from "ADD" to curl to leverage
the docker build cache.
=> ubuntu-demo-openvino: upgrade to openvino R4 release to align with OVC

DEVEL.md, cmd/qat_plugin/README.md, cmd/qat_plugin/dpdkdrv/dpdkdrv.go, cmd/qat_plugin/dpdkdrv/dpdkdrv_test.go, cmd/qat_plugin/kerneldrv/kerneldrv.go, cmd/qat_plugin/kerneldrv/kerneldrv_test.go, cmd/qat_plugin/kerneldrv/stub.go, cmd/qat_plugin/qat_plugin.go, deployments/qat_plugin/base/intel-qat-plugin-config.yaml, deployments/qat_plugin/base/intel-qat-plugin.yaml, deployments/qat_plugin/overlays/debug/kustomization.yaml, pkg/deviceplugin/api.go, pkg/deviceplugin/manager.go, pkg/deviceplugin/manager_test.go, pkg/deviceplugin/server.go, pkg/deviceplugin/server_test.go
Unify our logging across the repo to use klog.
This brings with it extra annotations to the log entries, as well as a bunch of command line arguments to the plugins to allow control of how and where to log.
Related-To: #323
=> klog: Add klog logging to framework and qat plugins

cmd/gpu_plugin/gpu_plugin.go, cmd/gpu_plugin/gpu_plugin_test.go
Move from fmt to klog for logging and debug.
Also add an extra info level message noting when we find
new devices.
=> gpu: move to using klog

cmd/qat_plugin/dpdkdrv/dpdkdrv_test.go
Add NewDevicePlugin() tests to improve test coverage. This also
contributes to "input validation" (part of #321) that wasn't done
properly before.
Fixes: #325
=> dpdkdrv: improve unit test coverage

DEVEL.md, cmd/fpga_admissionwebhook/controller.go, cmd/fpga_admissionwebhook/controller_test.go, cmd/fpga_admissionwebhook/fpga_admissionwebhook.go, cmd/fpga_admissionwebhook/fpga_admissionwebhook_test.go, cmd/fpga_admissionwebhook/patcher.go, cmd/fpga_admissionwebhook/patcher_test.go, cmd/fpga_crihook/main.go, cmd/fpga_crihook/main_test.go, cmd/fpga_plugin/fpga_plugin.go, cmd/fpga_plugin/fpga_plugin_test.go, deployments/fpga_admissionwebhook/base/intel-fpga-webhook-deployment.yaml, deployments/fpga_admissionwebhook/deployment-tpl.yaml
Move all the fpga components to using klog for logging
and debug. This includes replacing our homebrew 'fatal()'
with klog.Error().
Modify the deployment files to move from `-debug` to
`-v`, and set their default level to '1' (Info), rather
than full debug mode ('4').
=> fpga: move to using klog for logs and debug

pkg/deviceplugin/api.go, pkg/deviceplugin/manager.go, pkg/deviceplugin/manager_test.go, pkg/deviceplugin/server.go, pkg/deviceplugin/server_test.go
Some plugins may require doing some work before a container starts. To allow such functionality the `deviceplugin` package adds one more optional interface - `ContainerPreStarter`. If a device plugin implements it then kubelet always calls `PreStartContainer()` gRPC call.  No other configuration is needed.
Once the interface is implemented kubelet always calls `PreStartContainer()`. If there's a use case when this additional gRPC call causes a problem then `deviceplugin.Manager` should have something like `RegisterPreStartContainerFunc()`. But I'm not aware of any such use cases.
Also worth noting that one `devieplugin.Manager` may fire up multiple gRPC servers. Should we enable/disable `PreStartContainer` for all of them or need better granularity? I cannot come up with any use case when …
=> Add interface ContainerPreStarter optionally implemented by device plugins

cmd/fpga_plugin/dfl_test.go, cmd/fpga_plugin/opae_test.go
- used t.Run api for better visibility
- used ioutil.TempDir to create temporary directories
=> fpga tests cleanup

deployments/fpga_admissionwebhook/deployment-tpl.yaml
The `-v 1` arg is treated as single word thus klog throws `flag provided but not defined: -v 1` error.
Caught it while running E2E tests for the new mode-less webhook.
=> fix flag provided but not defined error

deployments/fpga_admissionwebhook/base/intel-fpga-webhook-deployment.yaml
The same fix as previous:
```
The `-v 1` arg is treated as single word thus klog throws
"flag provided but not defined: -v 1" error.
```
This time it's in the webhook kustomize base.
=> fix flag provided but not defined error again

deployments/fpga_plugin/fpga_plugin.yaml, deployments/fpga_plugin/fpga_plugin_service_account.yaml, scripts/deploy-fpgaplugin.sh, test/e2e/deviceplugins_suite_test.go, test/e2e/fpga/fpga.go
implemented e2e tests for preprogrammed(af) and
orchestrated(region) plugin modes.
Fixes: #350
=> implement e2e tests for FPGA plugin

demo/ubuntu-demo-openvino/Dockerfile
Openvino 2020 repo now has hddl package support. We should leverage that.
=> ubuntu-demo-openvino: use apt source instead of tar ball downloading

pkg/topology/topology.go, pkg/topology/topology_test.go
Doing strings.Split with a non-empty separator against a potentially
empty string (hint.NUMAs) may return an empty string in a slice of
size one, which then doesn't parse nicely with ParseInt and results
in a repeating warning.
It is better to check for hint.NUMAs emptiness before trying to
split it.
=> topology: avoid unnecessary warning prints

deployments/gpu_plugin/base/intel-gpu-plugin.yaml
Without the node selector this will deploy on arm nodes with a constantly retrying pod.
=> Add node selector to restrict to x86

demo/opae-nlb-demo/Dockerfile, deployments/qat_plugin/overlays/apparmor_unconfined/add-apparmor-unconfined-intel-qat.yaml, deployments/qat_plugin/overlays/apparmor_unconfined/kustomization.yaml
Some Ubuntu systems may run with Apparmor LSM policy enformements making
the default QAT daemonset to fail with (un)bind errors.
This commit adds a sample kustomize overlay to deploy the QAT daemonset with
Apparmor uconfined policy.
Fixes: #381
=> deployments: qat: add an overlay for Apparmor annotations

deployments/fpga_admissionwebhook/crd/bases/fpga.intel.com_af.yaml
OpenCL bitstream .aocx has longer than 32 unique ID. Extend to 40 to accommodate it.
=> Extend afu id max length to 40 for aocx Unique UUID

deployments/fpga_admissionwebhook/mappings-collection.yaml
This mapping will be used in the new demo screencast for FPGA plugin
deployment in preprogrammed mode.
=> mapping-collection: add mappings for arria10.dcp1.2-nlb3-preprogrammed

deployments/fpga_admissionwebhook/mappings-collection.yaml
This mapping will be used in the new demo screencast for FPGA plugin deployment in orchestrated mode.
=> Mapping-collection: Add mappings for d5005-matrix-mult-orchestrated

demo/readme.md, demo/screencast-fpga-preprogrammed.sh, demo/test-fpga-preprogrammed.yaml
This screencast demonstrates deployment scenario for FPGA
preprogrammed mode. It uses Docker as a runtime to show that
CRI-O is not required in this mode.
=> FPGA demo: add screencast for preprogrammed mode

demo/openssl-qat-engine/Dockerfile
ipp-crypto repository did not provide a tag with the necessary changes
included until recently so we were using the master branch.
Now the tag was added (and master broke our build) so we move to use
it.
=> demo: fix openssl-qat-engine build

cmd/fpga_tool/fpga_tool.go, pkg/fpga/dfl_linux.go, pkg/fpga/intel_fpga_linux.go, pkg/fpga/interfaces.go
fpgatool now understands two new commands `release` and `assign` that are needed to prepare FME for SR-IOV configurations.
=> Support for FME port Release/Assign for SR-IOV configurations

cmd/gpu_plugin/gpu_plugin.go
For every created device info, a new topology scan is performed in
the filesystem. The shared dev count was implemented so that for each
shared device, a new device info was created, which resulted in the
topology scan happening as many times per Scan-round, as there were
shared devs.
This fixes the issue by making the device info to be shared among the
shared devices.
#448 
=> gpu_plugin: reduce topology scanning for high shared dev count

deployments/qat_plugin/overlays/sriov_numvfs/kustomization.yaml, deployments/qat_plugin/overlays/sriov_numvfs/sriov_numvfs_init.yaml
This commit adds two initcontainers in a kustomize overlay to QAT
deployment. The overlay can be used to prepare QAT setup on a freshly
booted system.
Note: containerd/cri-o seem to have issues mounting sysfs rw in even
if the container is privileged. Therefore, we do a special /sys:/sys
bind mount for 'cat sriov_totalvs | tee sriov_numvfs' to work.
Fixes: #320
=> qat: add kustomize overlay to enable SR-IOV

demo/sgx-sdk-demo/Dockerfile
The client side packages Recommends aesmd service and that gets pulled
in the image. aesmd service is expected to run in its own container so
we build the sample apps container without it.
=> sgx-sdk-demo: install packages without recommendations

.gitignore, Makefile, conf.py, docs/extensions.rst, docs/index.html, docs/requirements.txt, index.rst
Signed-off-by: Kevin Putnam <kevin.putnam@intel.com>
=> Documentation: adds ability to build Read the Docs static site.

.github/workflows/publish.yml
The initial publish.yml was a merger of two examples with
different ways to handle the publishing and resulted in
some inconsistencies.
v2 of the docs publishing correctly takes the git author
info from the original respository and uses that info to
create the docs-only repo ($HOME/output) that is then pushed
to gh-pages.
=> ci: fix docs publishing

.github/workflows/publish.yml
$author and $email do not get set because actions/checkout@v2
fetches only a single commit by default.
Pull full history by setting fetch-depth according to checkout
documentation.
=> ci: fix docs publishing again

.github/workflows/ci.yaml, build/docker/intel-gpu-initcontainer.Dockerfile, cmd/gpu_nfdhook/README.md, cmd/gpu_nfdhook/labeler.go, cmd/gpu_nfdhook/labeler_test.go, cmd/gpu_nfdhook/main.go, deployments/gpu_plugin/base/intel-gpu-plugin.yaml
This adds an nfd-hook for the gpu-plugin, which will create labels
for the GPUs that can then be used for POD deployment purposes or
creation of GPU extended resources which allow then finer grained
GPU resource management.
The nfd-hook will install to the host system when the
intel-gpu-initcontainer is run. It is added into the plugin deployment
yaml.
=> gpu-plugin nfd-hook

cmd/gpu_nfdhook/README.md, cmd/gpu_nfdhook/labeler.go, cmd/gpu_nfdhook/labeler_test.go, cmd/gpu_nfdhook/main.go
This adds reading of the GPU memory amount from the sysfs. As a
fallback the environment variable GPU_MEMORY_OVERRIDE remains.
Another environment variable GPU_MEMORY_RESERVED can be used to
reserve a dedicated byte amount outside of kubernetes usage.
=> gpu_nfdhook memory amount reading from sysfs

pkg/fpga/dfl_linux.go
Using now correct IOCTLs for upstream DFL drivers.
=> Fix FPGA DFL Release/Assign ioctl numbers

cmd/fpga_plugin/dfl.go, cmd/fpga_plugin/dfl_test.go, cmd/fpga_plugin/fpga_plugin.go, cmd/fpga_plugin/fpga_plugin_test.go, cmd/fpga_plugin/opae.go, cmd/fpga_plugin/opae_test.go
Reimplemented discovering FPGA devices using APIs from pkg/fpga/intel_fpga_linux.
The APis are also used in the fpga_tool utility.
The API is more advanced and supports SR-IOV among other things.
Fixes: #372
=> fpga: reimplement device discovering

cmd/fpga_plugin/dfl.go, cmd/fpga_plugin/fpga_plugin.go, cmd/fpga_plugin/opae.go
Used generic newPort API instead of device-specific
newDflPort and newIntelFpgaPort to initialize plugin.newPort.
=> fpga: improve port init

demo/openssl-qat-engine/Dockerfile
It was observed that qat-hw (when built right after qat-sw) is not built
correctly. Run make clean before the build (and back-up qat-sw since
clean removes it).
=> openssl-qat-engine: fix qat-hw engine build

deployments/operator/crd/bases/deviceplugin.intel.com_gpudeviceplugins.yaml, pkg/apis/deviceplugin/v1/fpgadeviceplugin_webhook.go, pkg/apis/deviceplugin/v1/gpudeviceplugin_types.go, pkg/apis/deviceplugin/v1/gpudeviceplugin_webhook.go, pkg/apis/deviceplugin/v1/webhook_common.go, pkg/controllers/gpu/controller.go
This adds the initImage field to the custom resource definition
and takes it into use.
Closes: #474 
=> operator: GPU-plugin initImage

cmd/fpga_tool/fpga_tool.go, pkg/fpga/dfl_linux.go, pkg/fpga/intel_fpga_linux.go
This call is implemented by calling ioctl, which raises
"open /dev/intel-fpga-port.X: operation not permitted" when
called inside unprivileged container.
This breaks FPGA plugin.
Calling this API from fpga_tool is still OK, so
moving calls there should fix the issue.
=> fpga: move GetAPIVersion call out of NewPort and NewFME

go.mod
For some reason the script used for automated upgrade doesn't touch two records in go.mod. Update them manually.
=> manually fix deps to point to latest release

README.md, deployments/gpu_plugin/base/intel-gpu-plugin.yaml, deployments/operator/manager/manager.yaml, scripts/set-image-pull-policy.sh
These patches change imagePullPolicy to Always in base deployments
and demos as discussed in #400.
In case a specific imagePullPolicy is required, it can be provided
through the relevant kustomization.yaml.
Closes #400.
=> Change imagePullPolicy to Always

.github/workflows/ci.yaml, README.md, build/docker/intel-dsa-plugin.Dockerfile, cmd/dsa_plugin/README.md, cmd/dsa_plugin/dsa_plugin.go, deployments/dsa_plugin/base/intel-dsa-plugin.yaml, deployments/dsa_plugin/base/kustomization.yaml, deployments/dsa_plugin/kustomization.yaml, deployments/dsa_plugin/overlays/namespace_kube-system/add-namespace-kube-system.yaml, deployments/dsa_plugin/overlays/namespace_kube-system/kustomization.yaml, pkg/idxd/plugin.go, pkg/idxd/plugin_test.go
This plugin discovers DSA work queues in /sys/bus/dsa/devices/
For the queues in "user" mode it looks for ```/dev/dsa/wqN.N```device nodes and correspondent  ```/dev/char/<major>.<minor>``` symlinks
Here is how the work queue resources are described in the ```kubectl describe node``` output:
```
$ k describe node dhcp0 | grep -A5 Allocatable
Allocatable:
cpu:                  2
dsa.intel.com/wq-kernel-dedicated:  1
dsa.intel.com/wq-mdev-dedicated:    6
dsa.intel.com/wq-mdev-shared:       5
dsa.intel.com/wq-user-shared:       45
``` 
Ref: #442
=> Implement DSA plugin

Makefile
Our 'make push' started failing and it looks docker picks :latest tag
for the image it just built but fails because it does not exist:
Using default tag: latest
...
tag does not exist:
cloud-native-image-registry.westus.cloudapp.azure.com/intel-deviceplugin-operator:latest
Fix 'make push' to explicitly use the image tag set by Jenkins.
=> Makefile: add explicit image tags to push

cmd/qat_plugin/dpdkdrv/dpdkdrv.go, cmd/qat_plugin/dpdkdrv/dpdkdrv_test.go, deployments/qat_plugin/base/intel-qat-plugin-config.yaml
It looks that for a long time now we have accepted a setup where a valid QAT
device ID is accepted as a QAT device resource even though the device is
not "enabled" via kernelVfDrivers parameter.
Fix device ID validation to skip valid QAT devices that are not
explicitly specified in kernelVfDrivers.
=> qat: fix device ID validation

cmd/gpu_nfdhook/labeler.go, cmd/gpu_nfdhook/labeler_test.go, cmd/gpu_nfdhook/main.go
This removes the devfs dependency. Sysfs is sufficient for scanning
presense of GPUs.
=> gpu_nfdhook: remove devfs dependency

pkg/deviceplugin/api.go, pkg/deviceplugin/manager.go, pkg/deviceplugin/manager_test.go, pkg/deviceplugin/server.go, pkg/deviceplugin/server_test.go
This adds a GetPreferredAllocator interface so that plugins can
optionally implement the API.
=> api: add PreferredAllocator interface

cmd/dsa_plugin/README.md
Fixed example of getting allocatable DSA resources. It was borrowed from GPU plugin and wasn't changed correctly.
=> dsa: fix kubectl command line

pkg/deviceplugin/server.go, pkg/deviceplugin/server_test.go
The option was left to false, this fixes it.
=> enable getPreferredAllocation

cmd/dsa_plugin/README.md, cmd/fpga_plugin/README.md, cmd/gpu_plugin/README.md, cmd/qat_plugin/README.md, cmd/sgx_plugin/README.md, cmd/vpu_plugin/README.md
Removed device plugin socket check from the documentation as
device plugin support is enabled by default in Kubelet.
=> documentation: remove kubelet configuration check

cmd/sgx_plugin/sgx_plugin.go, cmd/sgx_plugin/sgx_plugin_test.go
Decouple the default enclaveLimit/provisionLimit from core count. With
this change, the default limit is constant and it can be made relative
to core count by setting POD_PER_CORE multiplier via env variable.
=> sgx: change getDefaultPodCount() logic

pkg/webhooks/sgx/sgx.go
Go report card shows golint warnings for the SGX webhook. This
commit fixes those.
=> sgx: fix golint warnings

cmd/sgx_epchook/main.go, cmd/sgx_plugin/README.md, deployments/sgx_plugin/base/intel-sgx-plugin.yaml, deployments/sgx_plugin/base/kustomization.yaml, deployments/sgx_plugin/kustomization.yaml, deployments/sgx_plugin/overlays/epc-nfd/add-epc-nfd-initcontainer.yaml, deployments/sgx_plugin/overlays/epc-nfd/kustomization.yaml, deployments/sgx_plugin/overlays/epc-register/add-epc-register-initcontainer.yaml, deployments/sgx_plugin/overlays/epc-register/kustomization.yaml, deployments/sgx_plugin/overlays/epc-register/service-account.yaml, test/e2e/sgx/sgx.go
Signed-off-by: Dmitry Shmulevich <dmitry.shmulevich@gmail.com>
Closes: #457
=> added implementation of EPC extended resource advertiser

cmd/sgx_plugin/README.md
Related to pr499.
Line 15, 188: "Verify SGX device plugin is registered" removed 'on master'
Line 109, 120, 145: 'master' to 'main'
=> Editing sgx_plugin README. Replacing 'master' with 'main'. 

.github/workflows/ci.yaml, Jenkinsfile, build/docker/intel-deviceplugin-operator.Dockerfile, build/docker/intel-dsa-plugin.Dockerfile, build/docker/intel-fpga-admissionwebhook.Dockerfile, build/docker/intel-fpga-initcontainer.Dockerfile, build/docker/intel-fpga-plugin.Dockerfile, build/docker/intel-gpu-initcontainer.Dockerfile, build/docker/intel-gpu-plugin.Dockerfile, build/docker/intel-qat-plugin.Dockerfile, build/docker/intel-sgx-initcontainer.Dockerfile, build/docker/intel-sgx-plugin.Dockerfile, build/docker/intel-vpu-plugin.Dockerfile
=> ci: fix builds with buildah

cmd/sgx_plugin/README.md, demo/sgx-sdk-demo/Dockerfile, deployments/operator/samples/deviceplugin_v1_sgxdeviceplugin.yaml, deployments/sgx_aesmd/base/sgx_default_qcnl.conf, deployments/sgx_enclave_apps/overlays/sgx_ecdsa_inproc_quote/sgx_default_qcnl.conf, deployments/sgx_nfd/nfd-worker.conf
=> sgx: update SGX SDK/DCAP versions

cmd/qat_plugin/README.md
Replaced multiple instances of master with main.
Reworded line 15 "Verify QAT device plugin is registered" removed 'on master'
and corresponding section heading. Related to pr499.
=> Edited qat_plugin README

deployments/operator/rbac/auth_proxy_client_clusterrole.yaml
In order to get rid of deprecation warnings when deploying the operator,
move away from v1beta1 in RBAC API.
Closes: #489
=> Move to v1 in RBAC API

demo/screencast-sgx.sh
With the recent move to NFD custom source config for SGX features,
we no longer get SGX* cpuid labels but custom-intel.sgx so the grep
fails. Move to lowercase only checks.
=> demo: fix SGX screencast

pkg/apis/deviceplugin/v1/webhook_common.go
In order to support domains with a custom port, parse the image version
after the domain part.
Closes #605
=> webhook_common: Support domains with a custom port in the image string

DEVEL.md, Makefile, README.md, cmd/operator/README.md
As the operator container image is available from a registry, we should
guide users to use it rather than build and deploy it locally.
Further, drop (un)deploy-operator targets in favor of simply using
kubectl for deployment.
=> operator: update usage guidelines

deployments/operator/manager/manager.yaml
We have been getting reports about the operator getting killed
with an OOMKilled reason. This indicates we consume more memory
than what the resource limit states.
Bump up the memory limit to 50M.
=> operator: increase manager memory limit

cmd/gpu_nfdhook/labeler.go
This add support for parsing also hex and octal amounts.
=> gpu_nfdhook: make memory parsing more robust

cmd/operator/README.md, cmd/operator/main.go, deployments/operator/device/dsa/dsa.yaml, deployments/operator/device/dsa/kustomization.yaml, deployments/operator/device/fpga/fpga.yaml, deployments/operator/device/fpga/kustomization.yaml, deployments/operator/device/gpu/gpu.yaml, deployments/operator/device/gpu/kustomization.yaml, deployments/operator/device/qat/kustomization.yaml, deployments/operator/device/qat/qat.yaml, deployments/operator/device/sgx/kustomization.yaml, deployments/operator/device/sgx/sgx.yaml
In order to support per device deployment in the operator:
- Add customization overlays for FPGA, DSA, SGX, GPU, QAT under deployments/operator/device/
- Add --device cmdline to operator main.go which defines the controllers/webhooks to set up
=> Make it possible to select supported devices in the operator

README.md
Signed-off-by: Kailun Qin <kailun.qin@intel.com>
=> docs: README: fix SGX annotations used by Kata

Makefile, cmd/fpga_admissionwebhook/README.md, cmd/fpga_plugin/README.md, cmd/operator/README.md, cmd/sgx_admissionwebhook/README.md, cmd/sgx_plugin/README.md
Apart from updating to the latest release this PR also fixes major issue with automatic e2e testing:
FPGA webhook pod wasn't able to run due to a hard to debug mount issue:
```
At 2021-04-13 20:13:48 +0300 EEST - event for intelfpgaplugin-webhook-7b9c7b779c-rvtq4: ​​​​​​​​kubelet <host>:
FailedMount: MountVolume.SetUp failed for volume "cert" : secret "webhook-server-cert" not found
```
=> update to cert-manager v1.3.1

cmd/gpu_plugin/gpu_plugin.go, cmd/gpu_plugin/gpu_plugin_test.go
Added "i915_monitoring" resource mounts all GPU devices to requesting container.
This is needed to get GPU metrics from the host.  Requesting pod doesn't know how many GPUs the node it's assigned to has, so there needs to means to request them all.  Only alternative for this would be requesting Privileged mode, which is clearly worse as that would grant access also to all other devices and capabilities.
Checking for expected number of monitoring resources (0/1) is added to tests.
=> Add "i915_monitoring" resource to GPU plugin

cmd/sgx_plugin/README.md
The SGX DCAP out-of-tree v1.41 driver is also known to work
with the SGX plugin. However, the default NFD labeling does not
work with the out-of-tree driver so warn users about it.
=> sgx: add note about the SGX DCAP driver usage

demo/opae-nlb-demo/Dockerfile
With GCC 11, the build triggers errors:
/usr/src/opae/opae-sdk-1.5.0-2/opae-libs/include/opae/log.h:51:1: error: this 'if' clause does not guard... [-Werror=misleading-indentation]
51 | if (p > file)                                                  \
| ^~
...
Workaround the problem with -Wno-misleading-indentation.
=> opae-nlb-demo: fix GCC 11 errors

cmd/gpu_plugin/gpu_plugin.go, cmd/gpu_plugin/gpu_plugin_test.go
NOTE: this has impact only for GPUs which are virtualized with SR-IOV.
Access to physical devices (PFs) is disabled for "i915" resource when they have configured virtual devices (VFs).
This is because:
* GPU resources are expected to be evenly split between VFs in such configurations
* But PF resource amount is expected to differ from VFs and typically retain only enough resources (just few MB of RAM), to be able to provide GPU metrics that are not available from VFs
* Neither the current GPU plugin, nor Kubernetes scheduling in general, has proper support for heterogeneous GPUs (= capability based scheduling)
Therefore "i915" resource needs to be limited to GPU devices with homogeneous amount of resources, which in SR-IOV configurations is expected to be the case only with VFs (when such …
=> Skip PF for "i915" resource when it has VFs

cmd/gpu_plugin/gpu_plugin.go, cmd/gpu_plugin/gpu_plugin_test.go
Commits in this PR do following changes for the GPU plugin:
* Disable "i915_monitoring" resource by default, and add "-enable-monitoring" option so that this resource (exposing all node GPUs) can be enabled only when needed
* Move options to their own struct, so their use is more explicit (no magic values) and they can be more easily passed around
* Add testing for the new option, and also for the device sharing option that was missing testing support
---
These changes were dropped from latest versions of the PR:
* WIP/untested operator support for the new option (I will test it properly after it's clear whether rest of the changes are going to be accepted)
* Because option combinations change how GPU plugin should interpret the test environment, they and the expected resulting values are …
=> Add "-enable-monitoring" option to GPU plugin + testing for its options

.github/workflows/ci.yaml, Jenkinsfile, build/docker/intel-deviceplugin-operator.Dockerfile, build/docker/intel-dsa-plugin.Dockerfile, build/docker/intel-fpga-admissionwebhook.Dockerfile, build/docker/intel-fpga-plugin.Dockerfile, build/docker/intel-gpu-plugin.Dockerfile, build/docker/intel-qat-plugin-kerneldrv.Dockerfile, build/docker/intel-qat-plugin.Dockerfile, build/docker/intel-sgx-admissionwebhook.Dockerfile, build/docker/intel-sgx-plugin.Dockerfile, cmd/qat_plugin/README.md, deployments/fpga_admissionwebhook/manager/manager.yaml, deployments/operator/manager/manager.yaml, deployments/sgx_admissionwebhook/manager/manager.yaml, scripts/copy-modules-licenses.sh
All but one (VPU) of the published container images can be built with
static binaries which allows us to use distroless/static as the
base image. Moreover, when combined with stripping the plugin binaries,
we can get both build time and image size savings.
This is the part 1 (out of 2) of the rework. Part 2 will finish the
change by making some adjustments to VPU plugin image and moving the
FPGA/SGX/GPU initcontainers to distroless/static too.
Partial: #516
Signed-off-by: Ed Bartosh <eduard.bartosh@intel.com>
=> images: move most plugin images to distroless/static

cmd/qat_plugin/dpdkdrv/dpdkdrv.go, cmd/qat_plugin/dpdkdrv/dpdkdrv_test.go
<device>/driver symlink does not exist if the device is not bound
to any driver. bindDevice() failed when writing to <device>/driver/unbind
errored but IsNotExist() error is acceptable in case there's no driver
to unbind.
=> qat: do not fail if driver/unbind file does not exist

cmd/gpu_nfdhook/README.md, cmd/gpu_plugin/README.md
This adds a link from gpu-plugin README to the nfdhook README, and
updates the nfdhook README with label descriptions.
=> add link to gpu_nfdhook and update hook README

pkg/apis/deviceplugin/v1/qatdeviceplugin_webhook.go
Since we currently validate only the image name and the tag,
ignore registry, vendor and extract only relevant parts.
Closes #605
=> qatdeviceplugin_webhook: Extract only relevant parts for the validation

deployments/gpu_plugin/overlays/fractional_resources/add-args.yaml
An easter-egg slipped in the args. This removes it.
=> remove monitoring arg from fractional resource overlay

deployments/operator/webhook/manifests.yaml, deployments/sgx_admissionwebhook/webhook/manifests.yaml
I am deploying sgx-device plugin on Azure VMs with [Marblerun](https://github.com/edgelesssys/marblerun).
They have a use case with a mutating admission [webhook](https://github.com/edgelesssys/marblerun/blob/master/injector/injector.go#L280) that injects resource request and limits on `sgx.intel.com/epc`.
However the ordering of two webhooks may be incorrect---the sgx device operator webhook runs first and then their custom webhook.
Adding `reinvocationPolicy: IfNeeded` following recommandation on [k8s admission control doc](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#reinvocation-policy) avoid this issue.
I also set `reinvocationPolicy: Never` in the custom webhook on the marblerun injector to facilitate proper ordering.
=> Add reinvocationPolicy for sgx operator

demo/openssl-qat-engine/Dockerfile
This updates the QAT driver to the latest version
and updates the new driver download location on
downloadmirror. Also, this openssl container build
requires yasm so it was added as well.
Signed-off-by: Eric Adams <eric.adams@intel.com>
=> Update QAT driver in openssl-qat-engine Dockerfile

README.md, cmd/gpu_plugin/README.md
* Information on specific HW & virtualization types on which GPU plugin is tested on, belongs to releases notes, not to README intro (where it has already became obsolete)
* HW offloading is provided by driver backends, not frontends (e.g. OneVPL is just one of the media driver frontends)
* Offloading can also be done for workloads that are not computationally intensive.  It's completely workload dependent whether that helps either with performance, power usage, both or neither
=> Make GPU plugin intro information more generic & accurate

deployments/operator/crd/bases/deviceplugin.intel.com_gpudeviceplugins.yaml, pkg/apis/deviceplugin/v1/gpudeviceplugin_types.go, pkg/controllers/gpu/controller.go
Earlier added 'i915_monitoring' support is disabled by default, so this is needed to be able to use it when operator is used.
Based on Ukri's examples and tested by Ukri.
=> Add "-enable-monitoring" GPU plugin option operator support

cmd/sgx_plugin/README.md, deployments/sgx_plugin/overlays/epc-nfd/kustomization.yaml
I am deploying sgx-device-plugin on Azure SGX VMs.
According to the [SGX device plugin doc](https://intel.github.io/intel-device-plugins-for-kubernetes/cmd/sgx_plugin/README.html#deploying-as-a-daemonset):
> There is a kustomization for deploying everything:
`$ kubectl apply -k ${INTEL_DEVICE_PLUGINS_SRC}/deployments/sgx_plugin/overlays/epc-nfd/`
However this does not start the device operator by default. Therefore `/dev/sgx_enclave` will not be mapped into the containers when resource `sgx.intel.com/epc` is requested.
Adding `operator/default` initiates the webhook and fixes the issue.
Although I still have to start the `cert-manager` by running
`$ kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.3.1/cert-manager.yaml`
I am not sure if adding this as …
=> Add SGX webhook operator as dependency of sgx-nfd

demo/crypto-perf/run-dpdk-test
The run-dpdk-test helper script builds dpdk-test-[compress|crypto]-perf
command line parameters dynamically. Some of the parameters were changed
in the recent DPDK builds and need updating.
=> demo: crypto-perf: update test tool parameters

.golangci.yml, cmd/fpga_crihook/main.go, cmd/fpga_plugin/fpga_plugin.go, cmd/fpga_plugin/fpga_plugin_test.go, cmd/fpga_plugin/mode.go, cmd/fpga_tool/fpga_tool.go, cmd/qat_plugin/kerneldrv/kerneldrv_test.go, pkg/deviceplugin/server_test.go, pkg/fpgacontroller/fpgacontroller_test.go, pkg/idxd/plugin_test.go, test/e2e/utils/utils.go
Add goerr113 lintercheck
Fix the usage of fmt.Errorf() by wrapping errors
Fix the usage of errors.New()
Closes: #641
=> Add goerr113 linter check

cmd/dsa_plugin/README.md, cmd/fpga_plugin/README.md, cmd/gpu_plugin/README.md, cmd/qat_plugin/README.md, cmd/sgx_plugin/README.md, cmd/vpu_plugin/README.md
The 'Verify node kubelet config' content was removed in 6b208f8.
Signed-off-by: Li Ning <ning.a.li@transwarp.io>
=> documentation: remove deprecated toc section in README

pkg/apis/deviceplugin/v1/dsadeviceplugin_webhook.go, pkg/apis/deviceplugin/v1/fpgadeviceplugin_webhook.go, pkg/apis/deviceplugin/v1/gpudeviceplugin_webhook.go, pkg/apis/deviceplugin/v1/qatdeviceplugin_webhook.go, pkg/apis/deviceplugin/v1/sgxdeviceplugin_webhook.go, pkg/apis/deviceplugin/v1/webhook_common.go
Move CRD validating webhooks' image min version checks to use
common constant across all the plugins.
After the change, we carry the same min version for all devices
and this version becomes easier to maintain when we make new
releases.
Each CRD webhook still carries its own xyzMinVersion if we decide
to go back to CRD specific versions later.
Closes: #627
=> webhooks: use common constant for plugin min version

README.md
Update link to Kata Containers 2.x QAT documentation, Kata Containers
1.x has been deprecated
Signed-off-by: Julio Montes <julio.montes@intel.com>
=> readme: update link to Kata Containers QAT documentation

build/docker/intel-fpga-initcontainer.Dockerfile, build/docker/intel-gpu-initcontainer.Dockerfile, build/docker/intel-qat-plugin-kerneldrv.Dockerfile, build/docker/intel-sgx-initcontainer.Dockerfile, build/docker/toybox-config, demo/openssl-qat-engine/Dockerfile
Add checksum checks for toybox and qat driver
Use toybox version 0.8.5 instead of 0.8.4
Update toybox-config
Closes: #643
=> Add checksum checks for toybox and qat driver

build/docker/intel-deviceplugin-operator.Dockerfile, build/docker/intel-dsa-plugin.Dockerfile, build/docker/intel-fpga-admissionwebhook.Dockerfile, build/docker/intel-fpga-initcontainer.Dockerfile, build/docker/intel-fpga-plugin.Dockerfile, build/docker/intel-gpu-initcontainer.Dockerfile, build/docker/intel-gpu-plugin.Dockerfile, build/docker/intel-qat-plugin-kerneldrv.Dockerfile, build/docker/intel-qat-plugin.Dockerfile, build/docker/intel-sgx-admissionwebhook.Dockerfile, build/docker/intel-sgx-initcontainer.Dockerfile, build/docker/intel-sgx-plugin.Dockerfile, build/docker/intel-vpu-plugin.Dockerfile
Changed base from Debian buster to Debian bullseye as suggested [here](https://github.com/intel/intel-device-plugins-for-kubernetes/pull/717#issuecomment-927610286) as bullseye(stable) is closer to our target distro (Debian-unstable) than buster (oldstable) among availalble golang bases.
=> change golang base to Debian bullseye

Makefile
Github Actions logs the following:
<string>:1: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default
Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
Silence the deprecation warning by specifying Loader=yaml.SafeLoader.
=> make: fix deprecation warning with yaml.load()

.github/workflows/e2e-fpga.yml, Makefile, test/e2e/fpga/fpga.go
This workflow is for testing FPGA plugin on the machine
with FPGA hardware.
The workflow can be triggered interactively from https://github.com/intel/intel-device-plugins-for-kubernetes/actions. This way maintainers can run it for any existing ref
To actually run the workflow some additional work should be done by the project admin:
=> add e2e-fpga workflow

deployments/operator/device/dsa/dsa.yaml, deployments/operator/device/fpga/fpga.yaml, deployments/operator/device/gpu/gpu.yaml, deployments/operator/device/qat/qat.yaml, deployments/operator/device/sgx/sgx.yaml
The flag is --devices, not --device so fix the YAMLs.
=> deployments: fix operator parameters for single-device configs

.github/workflows/e2e-qat.yml, Makefile
This workflow is for testing QAT plugin on the machine with QAT hardware.
The workflow can be triggered interactively from https://github.com/intel/intel-device-plugins-for-kubernetes/actions. This way maintainers can run it for any existing ref
=> actions: add e2e qat workflow

.github/workflows/ci.yaml, .gitignore, README.md, build/docker/intel-dlb-plugin.Dockerfile, cmd/dlb_plugin/README.md, cmd/dlb_plugin/dlb_plugin.go, cmd/dlb_plugin/dlb_plugin_test.go, cmd/internal/pluginutils/sriov.go, demo/dlb-dpdk-demo-pod.yaml, demo/dlb-dpdk-demo/Dockerfile, demo/dlb-dpdk-demo/test.sh, demo/dlb-libdlb-demo-pod.yaml, demo/dlb-libdlb-demo/Dockerfile, demo/dlb-libdlb-demo/test.sh, demo/libdlb-demo.yaml, deployments/dlb_plugin/base/intel-dlb-plugin.yaml, deployments/dlb_plugin/base/kustomization.yaml, deployments/dlb_plugin/kustomization.yaml
DLB plugin enables [Dynamic Load Balancer](https://builders.intel.com/docs/networkbuilders/SKU-343247-001US-queue-management-and-load-balancing-on-intel-architecture.pdf) accelerator.
=> Implement DLB plugin

demo/dlb-dpdk-demo-pod.yaml, demo/dlb-libdlb-demo-pod.yaml
Add memory request and limit with 200Mi so that pods can be guaranteed
=> dlb:Add memory request and limit for demo pods

cmd/gpu_plugin/README.md, cmd/gpu_plugin/gpu_plugin.go, cmd/gpu_plugin/gpu_plugin_test.go, deployments/operator/crd/bases/deviceplugin.intel.com_gpudeviceplugins.yaml, pkg/apis/deviceplugin/v1/gpudeviceplugin_types.go, pkg/apis/deviceplugin/v1/gpudeviceplugin_webhook.go, pkg/controllers/gpu/controller.go
1. Implement PreferredAllocator interface.
2. Provide 3 preferred allocation policies: balancingPolicy, packingPolicy and randomizingPolicy.
3. Provide the cmdline interface: -allocation-policy balanced/packed/random, to select which preferred allocation policy to use.
4. Add the unit test and update documentation.
=> GPU devices resource preferred allocation methods.

cmd/qat_plugin/README.md, cmd/qat_plugin/qat_plugin.go, deployments/qat_plugin/base/intel-qat-plugin-config.yaml, deployments/qat_plugin/base/intel-qat-plugin.yaml, deployments/qat_plugin/base/kustomization.yaml, deployments/qat_plugin/overlays/debug/add-args.yaml, deployments/qat_plugin/overlays/debug/kustomization.yaml
To make QAT plugin deployment consistent with the other plugins
we update the default flags and deploy without the flag settings
provided by the ConfigMap.
=> qat: update default flags and deploy without ConfigMap

pkg/apis/deviceplugin/v1/sgxdeviceplugin_webhook.go
The Defaulter wrongly assigned the "intel-sgx-initcontainer" to
Spec.Image instead of Spec.InitImage.
We don't see any problems because the default DaemonSet yaml
uses "intel-sgx-initcontainer".
=> operator: fix SgxDevicePlugin webhook.Defaulter

deployments/daemonsets.go, deployments/fpga_plugin/base/intel-fpga-plugin-daemonset.yaml, go.mod, pkg/controllers/dlb/controller.go, pkg/controllers/dlb/controller_test.go, pkg/controllers/dsa/controller.go, pkg/controllers/dsa/controller_test.go, pkg/controllers/fpga/controller.go, pkg/controllers/fpga/controller_test.go, pkg/controllers/gpu/controller.go, pkg/controllers/gpu/controller_test.go, pkg/controllers/qat/controller.go, pkg/controllers/qat/controller_test.go, pkg/controllers/sgx/controller.go, pkg/controllers/sgx/controller_test.go
Used go:embed to generate plugin daemonset objects instead of creating them manually in controller.go for all plugins.
Fixes: #394
=> operator: use go:embed to generate daemonset objects

deployments/operator/rbac/role.yaml, deployments/operator/webhook/manifests.yaml, pkg/controllers/dlb/controller.go, pkg/controllers/dsa/controller.go, pkg/controllers/fpga/controller.go, pkg/controllers/gpu/controller.go, pkg/controllers/qat/controller.go, pkg/controllers/sgx/controller.go
Clusters with OwnerReferencesPermissionEnforcement (e.g., OpenShift)
get stricter checks for metadata.ownerReferences.
This appears via errors like:
“is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to
a resource you can’t set finalizers on: ...”
The fix is to add "update" permissions to finalizers subresource
for the xDevicePlugins resources.
=> operator: allow controllers to touch ownerReferences always

.github/workflows/ci.yaml, Jenkinsfile, test/envtest/suite_test.go
ci:
- use 1.22.1 version of K8s
- update suite_test to support kubernetes 1.21+ version
In the pr [#758](https://github.com/intel/intel-device-plugins-for-kubernetes/pull/758#discussion_r753153008), k8s 1.20.2 was used to avoid the problem of timeout for waiting for process kube-apiserver to stop. Mikko figured out that there was an [update](https://github.com/kubernetes-sigs/kubebuilder/pull/2302) of [tutorial](https://book.kubebuilder.io/cronjob-tutorial/writing-tests.html) that we followed for suite_test.go file, and that we did not fix after the update was made. So, I updated the code.
=> ci: use 1.22.1 version of k8s instead of 1.20.2

test/envtest/dlbdeviceplugin_controller_test.go, test/envtest/suite_test.go
envtest:
- add DlbDevicePlugin tests
=> envtest: add DlbDevicePlugin tests

pkg/controllers/dsa/controller.go, pkg/controllers/dsa/controller_test.go
=> operator: dsa: Handle initcontainer and ConfigMap updates

test/e2e/deviceplugins_suite_test.go, test/e2e/dlb/dlb.go
I made e2e test for dlb. It needs both pf and vf in the node where the e2e test runs.
@mythi Sorry, I don't remember where you said to put the information about this matter. Please tell me again. 
In addition, I put resource requests and limits for both of resources. Would it be better to divide same as the yaml file of the demo file?
=> e2e: add dlb test

demo/dlb-dpdk-demo/Dockerfile, demo/dlb-libdlb-demo/Dockerfile
download dlb tarball from downloadmirror.intel.com, not from 01.org that would be down soon
=> dlb: update links for dlb demos

.github/dependabot.yml
Start with 'daily' check interval but we can relax it to
'weekly' later if needed.
Closes: #785 
(move away from draft after #788)
=> enable Github dependabot checks

cmd/gpu_plugin/README.md, cmd/gpu_plugin/render-device.sh
Easier alternative (for container maintainers) would be GPU device plugin providing `RENDER_DEVICE<X>` environment variables for all the requested GPUs, but Ukri was not interested in adding temporary [1] media specific workaround to the GPU plugin code, that still requires adding shell to the container, or modifying application code to directly use such env var.  Hence this workaround.
[1] (OneAPI) VPL API includes (feature based) device discovery support, but for now almost none of the media applications support VPL, so that does help yet.
QSV is deprecated in favor of VPL, so it is never going to get device discovery functionality, and there has been not much indication in last 3 years that libva would be getting such support either: https://github.com/intel/libva/issues/221
=> Provide workaround for the media issue and document it

.golangci.yml
golangci-lint outputs max 50 issues by default. This can lead to false estimation of the fixing effort for enabling new checks
Disabling default threashold should fix this
=> lint: output all found issues

cmd/gpu_nfdhook/README.md, cmd/gpu_nfdhook/labeler.go, cmd/gpu_nfdhook/labeler_test.go
"gen" number is in latest kernels capabilities files replaced with separate display, graphics, and media versions.
For compatibility with newer kernels, provide "gen" based on the new labels (but without decimals), and for older kernel compatibility, new labels based on "gen".
Optimize capabilities file parsing by using prefix check instead of scanf.
=> Adapt GPU label support to debugfs DRM entry changes

cmd/dlb_plugin/dlb_plugin.go
Add flag parsing to get command line parameters so that parameters about klog can be not ignored
=> dlb:Fix the problem that klog is not printed

cmd/dsa_plugin/README.md, deployments/dsa_plugin/overlays/dsa_initcontainer/dsa_initcontainer.yaml
There are a few things left un-renamed after \#771.
Rename those to idxd-config-initcontainer.
=> dsa: Fix the names still left as idxd-initcontainer

cmd/dlb_plugin/README.md
Remove the sentence for pre-built image since Dockerhub image for dlb plugin is available.
Closes: #697 
=> dlb: update README

.github/workflows/e2e-sgx.yml, Makefile
Add workflow to test SGX plugin on a machine with SGX hardware
Fixes: #664
=> sgx: add e2e workflow

.github/workflows/e2e-qat.yml, .github/workflows/e2e-sgx.yml
'concurrency: one_at_a_time_sgx' option doesn't work as expected
it causes failures of the builds when worker is busy.
Without this option job run stays in waiting state until a worker
picks it up.
=> e2e workflows:get rid of one_at_a_time concurency

Makefile
Enabled FPGA webhook tests by widening ginkgo.focus regexp. So far it was covering only FPGA plugin test cases.
=> fpga-e2e: enable webhook tests

.github/workflows/e2e-fpga.yml, .github/workflows/e2e-qat.yml, .github/workflows/e2e-sgx.yml
**NOTE:** this PR can be accepted only after setting "Require approval for all outside collaborators" option in the project configuration.
=> e2e: enable triggering e2e jobs on PRs

DEVEL.md
Current instruction does not work properly.
operator-sdk run packagemanifests should run with the manifests of the
previous version.
It will look like [this](https://github.com/hj-johannes-lee/intel-device-plugins-for-kubernetes/blob/fix-devel.md/DEVEL.md#how-to-publish-a-new-version-of-the-intel-device-plugins-operator-to-operatorhubio).
=> doc: fix operatorhub publishing instruction

DEVEL.md, Makefile
commit 1:
Makefile: add package manifests target directory 
commit 2:
doc: fix operatorhub publishing instruction
There was a mistake in #842 that 'git clone' command didn't come up
together with the command 'cp -r'. In addition, this pr includes
the changes following [the suggestion made after #842 was merged](https://github.com/intel/intel-device-plugins-for-kubernetes/pull/842#discussion_r782058383).
=> doc, Makefile: fix and update the operatorhub instruction related matters 

test/e2e/sgx/sgx.go
The NFD worker sleep timout is 60s by default so there are changes
we'll miss getting the sgx.intel.com/epc extended resource registered
before the timeout.
Increase the timeout so that at least two NFD worker labeling rounds
are included.
=> e2e/sgx: increase epc registration check timeout

cmd/gpu_nfdhook/README.md, cmd/gpu_nfdhook/labeler.go, cmd/gpu_nfdhook/labeler_test.go
This adds a new label "gpu-numbers" for short numbered lists of
gpus, omitting "card" from the names. Also adds splitting of long
label values.
Similarly this adds a new label "pci-groups" for PCI groups. Grouping
can be controlled by env var GPU_PCI_GROUPING_LEVEL. The env var
dictates, how many pci-folder names need to match, in order for GPUs
to be considered to belong in a group.
=> gpu_nfdhook: gpu-numbers and pci-groups

.github/workflows/e2e-fpga.yml, .github/workflows/e2e-qat.yml, .github/workflows/e2e-sgx.yml
Added event type 'pull_request' to the list of events
that trigger e2e-* workflows.
**NOTE:** this PR can be accepted only after setting "Require approval for all outside collaborators" option in the project configuration.
=> e2e: enable triggering hw jobs on PRs

cmd/gpu_nfdhook/README.md, cmd/gpu_nfdhook/labeler.go, cmd/gpu_nfdhook/labeler_test.go
This label isn't dependent on the debugfs as the platform
specific tile count is.
=> Add a total tile count to node's labels

deployments/nfd/node-feature-rules.yaml
Intel GPUs come at least in two classes: "0300" and 0380". Desktop GPUs with
3D / display support are in "0300" category, server/compute GPUs without
those are in "0380" category.
"0380" is missing so add it.
=> operator: update NFD rules for GPUs

Makefile
Fixes #881
Add wheel installing process before installing reuiqrements
I do not know why, but putting 'wheel' in requirements.txt does
not work for fixing the error in #881. So, alternatively, install
wheel first and then continue the following installing command.
=> Makefile: fix the target for python3 venv

README.md, build/docker/intel-deviceplugin-operator.Dockerfile, build/docker/intel-dlb-plugin.Dockerfile, build/docker/intel-dsa-plugin.Dockerfile, build/docker/intel-fpga-admissionwebhook.Dockerfile, build/docker/intel-fpga-initcontainer.Dockerfile, build/docker/intel-fpga-plugin.Dockerfile, build/docker/intel-gpu-initcontainer.Dockerfile, build/docker/intel-gpu-plugin.Dockerfile, build/docker/intel-qat-plugin.Dockerfile, build/docker/intel-sgx-admissionwebhook.Dockerfile, build/docker/intel-sgx-initcontainer.Dockerfile, build/docker/intel-sgx-plugin.Dockerfile
Updated license path to /install_root/licenses/ for all the plugin images except - intel-qat-plugin-kerneldrv, intel-vpu-plugin and intel-idxd-config-initcontainer images.
=> Images: Update license path for all plugin images

build/docker/intel-gpu-initcontainer.Dockerfile, build/docker/intel-idxd-config-initcontainer.Dockerfile, build/docker/intel-qat-plugin-kerneldrv.Dockerfile, build/docker/intel-sgx-initcontainer.Dockerfile, build/docker/intel-vpu-plugin.Dockerfile
An earlier commit updated the license install paths in our
distroless based images. This updates the remaining ones
to stay consistent.
=> images: update license install path in all images

build/docker/build-image.sh, build/docker/intel-deviceplugin-operator.Dockerfile, build/docker/intel-dlb-plugin.Dockerfile, build/docker/intel-dsa-plugin.Dockerfile, build/docker/intel-fpga-admissionwebhook.Dockerfile, build/docker/intel-fpga-initcontainer.Dockerfile, build/docker/intel-fpga-plugin.Dockerfile, build/docker/intel-gpu-initcontainer.Dockerfile, build/docker/intel-gpu-plugin.Dockerfile, build/docker/intel-idxd-config-initcontainer.Dockerfile, build/docker/intel-qat-plugin-kerneldrv.Dockerfile, build/docker/intel-qat-plugin.Dockerfile, build/docker/intel-sgx-admissionwebhook.Dockerfile, build/docker/intel-sgx-initcontainer.Dockerfile, build/docker/intel-sgx-plugin.Dockerfile, build/docker/intel-vpu-plugin.Dockerfile
Updated base image to use 'ubi8-micro' image from RedHat for all plugins.
Closes: #852
=> Images: Updated base image to use 'ubi8-micro' image from RedHat

test/envtest/dlbdeviceplugin_controller_test.go, test/envtest/dsadeviceplugin_controller_test.go, test/envtest/fpgadeviceplugin_controller_test.go, test/envtest/gpudeviceplugin_controller_test.go, test/envtest/iaadeviceplugin_controller_test.go, test/envtest/qatdeviceplugin_controller_test.go, test/envtest/sgxdeviceplugin_controller_test.go
Add tests for args, initImage, nodeSelector, etc
Export getPodArgs function of controllers
Closes: #772 
=> envtest: add more tests

deployments/operator/manifests/bases/intel-device-plugins-operator.clusterserviceversion.yaml
When validated bundle against operatorframework suite, it show the warning to mention the minKubeVersion (minimum kubernetes cluster version supported). Please see below - 
[ckulkar1@jfz1r09h07 intel-device-plugins-for-kubernetes]$ operator-sdk bundle validate ./bundle --select-optional suite=operatorframework
WARN[0000] Warning: Value : (intel-device-plugins-operator.v0.23.0) csv.Spec.minKubeVersion is not informed. It is recommended you provide this information. Otherwise, it would mean that your operator project can be distributed and installed in any cluster version available, which is not necessarily the case for all projects.
INFO[0000] All validation tests have completed successfully
Signed-off-by: chaitanya1731 <chaitanya.kulkarni@intel.com>
=> operator-csv: Added minKubeVersion to clusterServiceVersion.yaml. Picked '1.21.0' as it is mentioned in the "supported versions" matrix in README.md

pkg/fpgacontroller/patcher/patcher.go, pkg/fpgacontroller/patcher/patchermanager.go, pkg/fpgacontroller/patcher/patchermanager_test.go
Fixes a linter warning:
"unexported-return: exported method GetPatcher returns unexported type
*patcher.patcher, which can be annoying to use (revive)"
=> fpga: export Patcher type

test/envtest/suite_test.go
Go 1.18 deprecates strings.Title() which triggers linter
failures for us. Move to use "cases" as the recommended
replacement (to keep the existing functionality).
=> envtest: drop deprecated strings.Title()

cmd/gpu_plugin/README.md, cmd/gpu_plugin/gpu_plugin.go, cmd/gpu_plugin/gpu_plugin_test.go, cmd/gpu_plugin/rm/gpu_plugin_resource_manager.go, cmd/gpu_plugin/rm/gpu_plugin_resource_manager_test.go
Add support to target individual gpu tiles in containers through a level zero affinity variable. Container requesting gpu.intel.com/tiles resources will be running with a level zero environment variable which will limit/target the devices the applications can use.
=> gpu: add tiles annotation support

.github/workflows/ci.yaml, Jenkinsfile, Makefile, build/docker/intel-deviceplugin-operator.Dockerfile, build/docker/intel-dlb-plugin.Dockerfile, build/docker/intel-dsa-plugin.Dockerfile, build/docker/intel-fpga-admissionwebhook.Dockerfile, build/docker/intel-fpga-initcontainer.Dockerfile, build/docker/intel-fpga-plugin.Dockerfile, build/docker/intel-gpu-initcontainer.Dockerfile, build/docker/intel-gpu-plugin.Dockerfile, build/docker/intel-iaa-plugin.Dockerfile, build/docker/intel-qat-initcontainer.Dockerfile, build/docker/intel-qat-plugin-kerneldrv.Dockerfile, build/docker/intel-qat-plugin.Dockerfile, build/docker/intel-sgx-admissionwebhook.Dockerfile, build/docker/intel-sgx-initcontainer.Dockerfile, build/docker/intel-sgx-plugin.Dockerfile, build/docker/intel-vpu-plugin.Dockerfile
k8s v1.24 will move go Go 1.18. Let's do that too for our v0.24.
=> ci: move to Go 1.18

cmd/gpu_plugin/rm/gpu_plugin_resource_manager_test.go, pkg/deviceplugin/server.go, pkg/deviceplugin/server_test.go
Closes: #814
grpc-go v1.43.0 deprecated grpc.WithInsecure() in favor of
insecure.NewCredentials(). Move to use the recommended approach
and drop the linter annotations.
=> drop deprecated grpc.WithInsecure()

cmd/qat_plugin/README.md, cmd/qat_plugin/dpdkdrv/dpdkdrv.go, cmd/qat_plugin/dpdkdrv/dpdkdrv_test.go, cmd/qat_plugin/qat_plugin.go, deployments/operator/crd/bases/deviceplugin.intel.com_qatdeviceplugins.yaml, pkg/apis/deviceplugin/v1/qatdeviceplugin_types.go, pkg/controllers/qat/controller.go, test/envtest/qatdeviceplugin_controller_test.go
=> qat: implement preferredAllocation policies

README.md, cmd/qat_plugin/dpdkdrv/dpdkdrv.go, cmd/qat_plugin/dpdkdrv/dpdkdrv_test.go, deployments/qat_plugin/base/intel-qat-plugin.yaml, pkg/controllers/qat/controller_test.go
=> qat: 4xxx: split generic resource to compression and crypto

demo/screencast-dsa-accel-config.sh, demo/screencast-fpga-orchestrated.sh, demo/screencast-fpga-preprogrammed.sh, demo/screencast-qat-dpdk.sh, demo/screencast-qat.sh, demo/screencast-sgx.sh
This commit improves the screencast files by using the shell argument `$0` to represent the actual script filenames.
Closes: #964
=> doc: use shell argument $0 instead of embedded filenames in the screencast files

pkg/deviceplugin/server.go
Commit 2adad5ae76 missed one grpc.WithInsecure(). Drop
it in this commit.
=> drop one more grpc.WithInsecure()

cmd/qat_plugin/kerneldrv/kerneldrv.go, cmd/qat_plugin/kerneldrv/kerneldrv_test.go
Containers running on QAT Gen4 should be based on qatlib and therefore
kerneldrv is not the right mode. Skip registering 4xxx* devices to
ensure it is not used.
=> qat: kerneldrv: skip QAT Gen4 devices

deployments/operator/rbac/role.yaml, deployments/sgx_plugin/base/intel-sgx-plugin.yaml, pkg/controllers/sgx/controller.go, pkg/controllers/sgx/controller_test.go
* run the sgx container as container_device_plugin_t and init container
as container_device_plugin_init_t. these labels are being added to
container_selinux package upstream.
* add rbac role for openshift
Signed-off-by: Manish Regmi <manish.regmi@intel.com>
=> changes related to selinux and permissions for openshift

README.md
Will add the link to operator on Red Hat catalog once the operator is published. We are also thinking of adding another readme specifically for RedHat OpenShift Platform at location - cmd/operator/README-OCP.md.
Signed-off-by: chaitanya1731 <chaitanya.kulkarni@intel.com>
=> Updated Readme.md to include the Red Hat OCP availability

Makefile
Remove OPERATOR_VERSION that is already included in BUNDLE_DIR
Use BUILDER instead of docker directly
Correct style of using a variable to be "$()"
=> Makefile: fix misconfig and typo

build/docker/intel-qat-initcontainer.Dockerfile
Our images use /usr/local/bin paths so let's follow
that with qat-initcontainer too.
=> qat: move initcontainer script to standard path

deployments/nfd/overlays/node-feature-discovery/node-feature-discovery-openshift.yaml, deployments/nfd/overlays/node-feature-rules/node-feature-rules-openshift.yaml
This sample nfd cr can be used to make a new nfd instance with SGX support in openshift.
Fixes: #781
=> sgx: add a sample nfd CR that can be used in openshift

build/docker/intel-deviceplugin-operator.Dockerfile, build/docker/intel-dlb-plugin.Dockerfile, build/docker/intel-dsa-plugin.Dockerfile, build/docker/intel-fpga-admissionwebhook.Dockerfile, build/docker/intel-fpga-initcontainer.Dockerfile, build/docker/intel-fpga-plugin.Dockerfile, build/docker/intel-gpu-initcontainer.Dockerfile, build/docker/intel-gpu-plugin.Dockerfile, build/docker/intel-iaa-plugin.Dockerfile, build/docker/intel-qat-plugin.Dockerfile, build/docker/intel-sgx-admissionwebhook.Dockerfile, build/docker/intel-sgx-initcontainer.Dockerfile, build/docker/intel-sgx-plugin.Dockerfile
Just a trivial cleanup using:
$ sed -e 's/[[:space:]]$//' -i *.Dockerfile
=> images: cleanup whitespace line endings

Jenkinsfile
I have understood the images created in PR-triggered builds dont get any use afterwards, so the idea is to reduce stress and space consuming on registry, also saving some job time.
I moved push stmt from post block to become a stage, as I think conditional is not possible in post block.
Running push as a last stage instead of post-if-success should have same effect.
=> Jenkinsfile: do not push images if job was PR-triggered

test/e2e/dlb/dlb.go, test/e2e/gpu/gpu.go, test/e2e/sgx/sgx.go
WaitForFinish waits for pod to finish running, regardless of
success or failure. WaitForSuccess waits for pod to succeed
which is what we expect from our test workloads that try
to use the devices.
=> e2e: expect test workloads to finish successfully

cmd/qat_plugin/README.md, cmd/qat_plugin/dpdkdrv/dpdkdrv.go, demo/qat-init.sh, pkg/controllers/qat/controller.go
QAT_401xx is a derivative of 4xxx. Add support for that device
by including the device IDs (both PF and VF).
=> qat: add support for 401xx devices

cmd/operator/main.go, deployments/operator/default/manager_auth_proxy_patch.yaml, deployments/operator/device/dlb/dlb.yaml, deployments/operator/device/dsa/dsa.yaml, deployments/operator/device/fpga/fpga.yaml, deployments/operator/device/gpu/gpu.yaml, deployments/operator/device/qat/qat.yaml, deployments/operator/device/sgx/sgx.yaml
kubebuilder v3 based scaffolding has updated many things
and they are documented in [1].
Update operator's functionality to v3 level. We've done
most/some of the changes earlier (e.g., by not using
deprecated k8s APIs anymore) so the changes are minimal.
[1] https://book.kubebuilder.io/migration/v2vsv3.html
=> operator: align with kubebuilder v3 functionality

deployments/nfd/overlays/node-feature-rules/node-feature-rules.yaml
Added OPAE kernel module as an alternative to DFL
to the Arria10 labeling rules.
Fixes: #1069
=> fpga: update NFD labelling rules

cmd/sgx_plugin/README.md
I found the SGX device plugin deployments url always points to `main` branch, it will cause errors if users try to deploy previous version of SGX device plugin using this url.
=> doc: modify SGX device plugin deployments url from 'main' to '<RELEASE_VERSION>'

README.md
As a workaround for broken links, this removes the Workload Authors
section table and replaces it with a list.
fixes #1058
=> fix links by removing table

docs/requirements.txt
823e87a fixed docs generation by locking Markdown version that
is compatible with sphinx-markdown-tables but did not lock
sphinx-markdown-tables itself.
Now that sphinx-markdown-tables got fixed so that it requires the
latest Markdown version, the docs generation fails again.
Fix it by dropping the Markdown version lock. This also fixes
docs generation for the release branches.
=> ci: fix docs generation again

.github/workflows/ci.yaml, .github/workflows/e2e-dlb.yml, .github/workflows/e2e-dsa.yml, .github/workflows/e2e-fpga.yml, .github/workflows/e2e-gpu.yml, .github/workflows/e2e-iaa.yml, .github/workflows/e2e-qat.yml, .github/workflows/e2e-sgx.yml, .github/workflows/publish.yml
This PR adds minimum token permissions for the GITHUB_TOKEN using https://github.com/step-security/secure-workflows.
GitHub recommends defining minimum GITHUB_TOKEN permissions for securing GitHub Actions workflows 
- https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/  
- https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
- The Open Source Security Foundation (OpenSSF) [Scorecards](https://github.com/ossf/scorecard) treats not setting token permissions as a high-risk issue. Merging this PR will also help improve the Scorecard score for this project.  
Signed-off-by: Varun Sharma <varunsh@stepsecurity.io>
`GITHUB_TOKEN` has `write` permissions for multiple scopes which …
=> ci: add GitHub token permissions for workflows

cmd/operator/README.md
Add note about cert-manager in the section for deploying with pre-built
images since it is a requirement for the default operator deployment.
Add missing code block to section the the operator README.
Signed-off-by: Chelsea Mafrica <chelsea.e.mafrica@intel.com>
**Some notes/questions:**
I'm not sure if you want to use a small PR for updates to documents, so here are 2 changes that I think would improve clarity for installation/setup. I tested with Kata containers.
I am also wondering if it would make sense to put a note at the bottom of the SGX plugin README regarding `Pending` status and unavailable nodes due to `Insufficient sgx.intel.com/epc`, similar to how there is a note in the VPU plugin and a few others. I ran into this error with SGX, I think because I had initially not set up …
=> docs: Fix missing code block in operator doc 

build/docker/intel-idxd-config-initcontainer.Dockerfile, build/docker/templates/intel-idxd-config-initcontainer.Dockerfile.in, demo/opae-nlb-demo/Dockerfile
Due to a glibc version mismatch in the debian repos and the
unstable-slim docker image 3 CI jobs have been failing last several days.
Using testing-slim image as a base should fix the issue.
=> Use debian:testing-slim as a base image to fix CI issues for fpga, dsa and iaa

build/docker/intel-idxd-config-initcontainer.Dockerfile, build/docker/templates/intel-idxd-config-initcontainer.Dockerfile.in, demo/opae-nlb-demo/Dockerfile
Due to a glibc version mismatch in the Debian repos and the
unstable-slim and testing-slim docker image 3 CI jobs have been failing
for some time. The issue was fixed by switching to testing-slim base image
and started again when the bug was introduced to the image.
Using testing-slim image as a base should fix the issue.
=> fpga,dsa,iaa: Fix CI issue (attempt 2)

test/e2e/sgx/sgx.go
Due to a regression in k8s.io@v1.25, WaitForPodsWithLabelRunningReady()
ignored user provided timeout and defaulted to 60s. In some cases, NFD
needs more than that to the tests fail.
Workaround the problem by moving to use WaitForPodsRunningReady() with
minPods=2 (nfd-master and at least one nfd-worker).
=> e2e: fix SGX test flakiness

build/docker/intel-idxd-config-initcontainer.Dockerfile, build/docker/templates/intel-idxd-config-initcontainer.Dockerfile.in, demo/opae-nlb-demo/Dockerfile
We had to switch to debian unstable earlier due to a
mismatch in glibc versions in the debian-unstable-slim and
debian-testing-slim images and Debian package repositories.
[This issue has been fixed](https://github.com/debuerreotype/docker-debian-artifacts/issues/168), so we can switch back to debian-stable.
=> switch back to debian:unstable-slim as a base

cmd/gpu_nfdhook/README.md
Reason for deprecating IP block version labels, and better alternative, is explained in the relevant commit comment.
=> Improve GPU nfdhook README

deployments/dsa_plugin/overlays/namespace_kube-system/kustomization.yaml, deployments/gpu_plugin/overlays/fractional_resources/kustomization.yaml, deployments/gpu_plugin/overlays/namespace_kube-system/kustomization.yaml, deployments/gpu_plugin/overlays/nfd_labeled_nodes/kustomization.yaml, deployments/qat_plugin/overlays/debug/kustomization.yaml, deployments/qat_plugin/overlays/e2e/kustomization.yaml, deployments/sgx_plugin/overlays/epc-hook-initcontainer/kustomization.yaml, deployments/sgx_plugin/overlays/epc-nfd/kustomization.yaml, deployments/sgx_plugin/overlays/epc-register/kustomization.yaml, deployments/vpu_plugin/overlays/namespace_kube-system/kustomization.yaml, deployments/vpu_plugin/overlays/xlink/kustomization.yaml
This was made obsolete in v1.0.9
https://github.com/kubernetes-sigs/kustomize/blob/v1.0.9/pkg/types/kustomization.go#L129
And stopped working in v3.0.3
https://github.com/kubernetes-sigs/kustomize/issues/1373
=> Replace obsolete patches syntax

cmd/gpu_plugin/gpu_plugin.go
GPU plugin code assumes container paths to match host paths, and container runtime prevents creating fake files under real paths.  When non-standard paths are used, devices can be faked for scalability testing.
The whole picture and review comments are in the RFC PR #1104, from which this is split off.
=> Add "prefix" option to GPU plugin for scalability testing

test/e2e/dlb/dlb.go, test/e2e/dsa/dsa.go, test/e2e/fpga/fpga.go, test/e2e/fpgaadmissionwebhook/fpgaadmissionwebhook.go, test/e2e/gpu/gpu.go, test/e2e/iaa/iaa.go, test/e2e/qat/qatplugin_dpdk.go, test/e2e/qat/qatplugin_kernel.go
=> e2e: Remove unnecessary namespace arguments from KubectlOrDie calls

cmd/gpu_plugin/gpu_plugin.go, pkg/deviceplugin/api.go
This improves #1113 further by:
* logging both GPU plugin resource type count changes separately, and
* getting rid of DeviceTree internals access
Increase in scan() method complexity required splitting the innermost loop to a separate method => changes are best reviewed from the commits themselves.
(This is WIP because there's some ongoing discussion about whether DeviceTree could provide method for this, and to indicate that it's not supposed to go in before the next release.)
=> Log GPU plugin resource count changes per type

DEVEL.md, README.md, cmd/dlb_plugin/README.md, cmd/dsa_plugin/README.md, cmd/fpga_crihook/README.md, cmd/fpga_plugin/README.md, cmd/gpu_plugin/README.md, cmd/iaa_plugin/README.md, cmd/qat_plugin/README.md, cmd/sgx_plugin/README.md, cmd/vpu_plugin/README.md
Currently, each individual plugin README documents roughly the same
daily development steps to git clone, build, and deploy. Re-purpose
the plugin READMEs more towards cluster admin type of documentation
and start moving all development related documentation to DEVEL.md.
The same is true for e2e testing documentation which is scattered
in places where they don't belong to. Having all day-to-day
development Howtos is good to have in a centralized place.
Finally, the cleanup includes some harmonization to plugins'
table of contents which now follows the pattern:
* [Introduction](#introduction)
(* [Modes and Configuration Options](#modes-and-configuration-options))
* [Installation](#installation)
(* [Prerequisites](#prerequisites))
* [Pre-built Images](#pre-built-images)
* [Verify Plugin …
=> docs: rework development guide

cmd/sgx_plugin/sgx_plugin.go
/dev/sgx_* cannot be mapped to any topology. SGX itself is topology
aware but we cannot control it with TopologyInfo.
Currently, pkg/topology returns empty TopologyInfo{Nodes:[]*NUMANode{}}
for /dev/sgx_* but kubelet TopologyManager (when enabled and with the
policy other than 'none') interpretes that as "Hint Provider has no
possible NUMA affinities for resource" and rejects the SGX resources.
What we want is "Hint Provider has no preference for NUMA affinity with
resource". This is communicated using nil TopologyInfo.
See: https://github.com/kubernetes/kubernetes/issues/112234
=> sgx: send nil TopologyInfo

.github/workflows/e2e-dlb.yml, .github/workflows/e2e-dsa.yml, .github/workflows/e2e-iaa.yml, .github/workflows/e2e-qat4.yml
As we have unified Simics SPR targets and they can run any Simics jobs let's unify labels too to avoid confusing configurations similar to this:
```
name: e2e-qat4
-    runs-on: [dsa]
```
This unification also helps to spread the load among runners more effectively.
=> ci: unify labeling for Simics jobs

charts/operator/templates/operator.yaml, deployments/fpga_admissionwebhook/rbac/leader_election_role.yaml, deployments/operator/rbac/leader_election_role.yaml
controller-runtime now defaults LeaderElectionResourceLock to leases and we had missed the migration to it properly.
Update the RBAC rules to get our controllers to write their leader election locks to leases.
=> deployments: fix leader election RBAC rules

deployments/gpu_plugin/base/intel-gpu-plugin.yaml, pkg/controllers/gpu/controller.go, pkg/controllers/gpu/controller_test.go
Added selinux labels for Intel GPU plugins. This runs the gpu container as container_device_plugin_t and gpu init container
as container_device_plugin_init_t.
=> Added selinux labels for GPU plugins

.github/workflows/e2e-dsa.yml, .github/workflows/e2e-iaa.yml
- Converted DLB and IAA jobs into matrix jobs
- Added simics-gnr target to the jobs
Fixes: #1044
=> e2e: run DSA and IAA jobs on SPR and GNR instances

deployments/nfd/overlays/node-feature-rules/node-feature-rules-openshift.yaml, deployments/nfd/overlays/node-feature-rules/node-feature-rules.yaml
6.0.0 kernel doesn't seem to have 'drm' module anymore and it makes more sense to depend on the i915 module.
=> Use 'i915' instead of 'drm' kernel mod as requirement for gpu label

deployments/gpu_plugin/overlays/fractional_resources/add-nodeselector-intel-gpu.yaml, deployments/gpu_plugin/overlays/fractional_resources/kustomization.yaml
Updated documentation indicates that fractional overlay uses nfd so maybe it should.
=> gpu: add nodeSelector to fractional overlay

deployments/gpu_plugin/overlays/fractional_resources/add-serviceaccount.yaml, deployments/gpu_plugin/overlays/fractional_resources/gpu-manager-role.yaml, deployments/gpu_plugin/overlays/fractional_resources/gpu-manager-rolebinding.yaml, deployments/gpu_plugin/overlays/fractional_resources/gpu-manager-sa.yaml, deployments/gpu_plugin/overlays/fractional_resources/kustomization.yaml
Operator has used "gpu-manager" as part of the cluster object names it creates. Kustomize based deployments can be aligned with that.
=> align gpu kustomize object naming with operator naming

cmd/gpu_plugin/README.md
- Add note about LTS kernel DKMS source repo
- Correct previous demo note update (unlike FPGA demo, GPU demo is not in docker hub)
=> Improve GPU drivers installation instructions

.github/workflows/ci.yaml, .github/workflows/e2e-dlb.yml, build/docker/intel-dlb-initcontainer.Dockerfile, build/docker/templates/intel-dlb-initcontainer.Dockerfile.in, build/docker/toybox-config, demo/dlb-init.sh, deployments/dlb_plugin/overlays/dlb_initcontainer/dlb_initcontainer.yaml, deployments/dlb_plugin/overlays/dlb_initcontainer/kustomization.yaml, deployments/operator/crd/bases/deviceplugin.intel.com_dlbdeviceplugins.yaml, deployments/operator/samples/deviceplugin_v1_dlbdeviceplugin.yaml, pkg/apis/deviceplugin/v1/dlbdeviceplugin_types.go, pkg/apis/deviceplugin/v1/dlbdeviceplugin_webhook.go, pkg/controllers/dlb/controller.go, test/e2e/dlb/dlb.go, test/envtest/dlbdeviceplugin_controller_test.go, test/envtest/suite_test.go
Closes: #1053 
initcontainer enables vfs and configures vfs
- the number of pfs and vfs per pf can be configurable by users
add dlb-initcontainer kustomize overlay
update CRD to have initImage
implment operator to run initcontainer
update e2e test to run initcontainer overlay
pudate envtest to test initimage
---
TO BE DISCUSSED & IMPROVED:
1. Do we actually keep the variable "REMAINING_NUM_PFS"? Or find another way?
2. How to have no 'default' values for variables ("REMAINING_NUM_PFS", "NUM_VFS_PER_PF) in the script, yaml, etc.
3. This PR does not have any change of CRD for the variables. Do we include here, or later in another PR?
*There will be no more work for this PR until September.
=> dlb: add initcontainer to plugin

Jenkinsfile
The infrastucture does not run bionic workers anymore so the release publishing fails.
Move to what's in main, that is Jammy worker.
=> release-0.24: ci: use jammy worker in Jenkins

build/docker/intel-qat-initcontainer.Dockerfile, build/docker/templates/intel-qat-initcontainer.Dockerfile.in, demo/qat-init.sh
closes: #1222
related work that adds e2e tests of checking initcontainer's idempotence: #1223 
=> qat: fix initcontainer to skip when sriov is already configured

DEVEL.md, Makefile, deployments/operator/manager/manager.yaml, deployments/operator/manifests/bases/intel-device-plugins-operator.clusterserviceversion.yaml
https://sdk.operatorframework.io/docs/cli/operator-sdk_run_bundle/
According to the documentation of operator-sdk, docker.io should be speficied.
In addition, we update the operator version to 0.25.0.
Also, publishing to operatorhub part in DEVEL.md has been updated/fixed.
=> operator: update image name and version

test/e2e/iaa/iaa.go
e2e-iaa job fails more often recently due to added accel-config tests.
increasing timeout should fix this flackiness.
=> e2e-iaa: increase test timeout

deployments/operator/default/manager_auth_proxy_patch.yaml
draft until `v0.13.1` becomes available.
=> deployments: update kube-rbac-proxy image and args

build/docker/intel-qat-initcontainer.Dockerfile, build/docker/templates/intel-qat-initcontainer.Dockerfile.in, build/docker/toybox-config, cmd/qat_plugin/README.md, demo/qat-init.sh, deployments/operator/crd/bases/deviceplugin.intel.com_qatdeviceplugins.yaml, deployments/qat_plugin/base/intel-qat-plugin.yaml, deployments/qat_plugin/overlays/e2e/kustomization.yaml, deployments/qat_plugin/overlays/qat_initcontainer/kustomization.yaml, deployments/qat_plugin/overlays/qat_initcontainer/qat.conf, deployments/qat_plugin/overlays/qat_initcontainer/qat_initcontainer.yaml, deployments/qat_plugin/overlays/sriov_numvfs/kustomization.yaml, pkg/apis/deviceplugin/v1/qatdeviceplugin_types.go, pkg/apis/deviceplugin/v1/qatdeviceplugin_webhook.go, pkg/controllers/qat/controller.go, pkg/controllers/qat/controller_test.go, test/envtest/qatdeviceplugin_controller_test.go
=> qat: add configuration of cfgServices to qat initcontainer

test/e2e/dlb/dlb.go, test/e2e/dsa/dsa.go, test/e2e/gpu/gpu.go, test/e2e/iaa/iaa.go, test/e2e/qat/qatplugin_dpdk.go, test/e2e/qat/qatplugin_kernel.go, test/e2e/qat/qatplugin_qatgen4_crypto.go, test/e2e/sgx/sgx.go
finnish -> finish
check -> check if
=> e2e: fix typos and minor grammar issues

cmd/gpu_plugin/README.md
Otherwise most shells will interpreted `?` in an unintended way. You can see one example of a confused user (likely due to this) [here](https://www.truenas.com/community/threads/use-intel-gpu-hardware-encoding-in-plex-kubernetes-deployment.89747/post-621097).
=> Fix command in docs by adding single quotes

cmd/gpu_plugin/rm/gpu_plugin_resource_manager.go, cmd/gpu_plugin/rm/gpu_plugin_resource_manager_test.go
ContainerAssignments and PodAssignementDetauls need not be exported.
=> unexport internal types

cmd/gpu_plugin/README.md, deployments/gpu_plugin/overlays/monitoring_shared-dev_nfd/add-args.yaml, deployments/gpu_plugin/overlays/monitoring_shared-dev_nfd/add-nodeselector-intel-gpu.yaml, deployments/gpu_plugin/overlays/monitoring_shared-dev_nfd/kustomization.yaml, deployments/nfd/base/kustomization.yaml
=> gpu: add new nfd + monitoring + shared-dev deployment option

.github/workflows/ci.yaml, README.md, build/docker/intel-xpumanager-sidecar.Dockerfile, build/docker/templates/intel-xpumanager-sidecar.Dockerfile.in, cmd/xpumanager_sidecar/README.md, cmd/xpumanager_sidecar/main.go, cmd/xpumanager_sidecar/main_test.go, deployments/xpumanager_sidecar/kustom/kustom_xpumanager.yaml, deployments/xpumanager_sidecar/kustomization.yaml, go.mod
Adds a new component that gathers xelink topology information from xpu-manager and then supplies that info as node labels.
Support in xpu-manager is still pending.
=> Gather XeLink mapping info to nodes via xpu-manager sidecar

demo/dlb-dpdk-demo/Dockerfile, deployments/sgx_aesmd/base/sgx_default_qcnl.conf, deployments/sgx_enclave_apps/base/intelsgx-job.yaml, deployments/sgx_enclave_apps/overlays/sgx_ecdsa_inproc_quote/sgx_default_qcnl.conf, test/e2e/deviceplugins_suite_test.go
=> assorted fixes

demo/dlb-dpdk-demo/test.sh
=> fix dlb-dpdk-demo's argument 'dev_id' to 'hwdev_id'

test/e2e/deviceplugins_suite_test.go
Apparently some of simulated CI nodes have out of sync boot configuration.
In order to be able to get the configuration in sync, the e2e NFD timeout should be increased (it takes 250-260 seconds for NFD to get up with the right boot parameters in the simulated environments).
=> e2e: Increase nfd timeout to 300 seconds

demo/crypto-perf/Dockerfile, demo/dlb-dpdk-demo/Dockerfile
ninja-build is installed as a dependency to meson so we don't need to install it separately. In fact pip install fails on setups that enforce PEP-668 of externally managed environments.
=> demo: do not pip install ninja

deployments/gpu_plugin/base/intel-gpu-plugin.yaml, deployments/sgx_plugin/overlays/epc-hook-initcontainer/add-epc-nfd-initcontainer.yaml, deployments/sgx_plugin/overlays/epc-nfd/add-epc-nfd-initcontainer.yaml, pkg/controllers/gpu/controller.go, pkg/controllers/sgx/controller.go
NFD hooks are deprecated and going away:
https://github.com/kubernetes-sigs/node-feature-discovery/issues/856
This makes the mount names more future-proof, and shows where later changes need to be done (to change operator mount directory, and switch hook-using deployments e.g. to feature files).
I decided to split this from PR https://github.com/intel/intel-device-plugins-for-kubernetes/pull/1118, so that same change can be done for all plugins (GPU + SGX), to avoid complicating later switch away from hooks.  Added SGX part is not tested, but that change is identical to GPU one.
=> Use more generic name for NFD features host directory volume

INSTALL.md, deployments/dsa_plugin/overlays/namespace_kube-system/add-namespace-kube-system.yaml, deployments/dsa_plugin/overlays/namespace_kube-system/kustomization.yaml, deployments/gpu_plugin/overlays/namespace_kube-system/add-namespace-kube-system.yaml, deployments/gpu_plugin/overlays/namespace_kube-system/kustomization.yaml, deployments/vpu_plugin/overlays/namespace_kube-system/add-namespace-kube-system.yaml, deployments/vpu_plugin/overlays/namespace_kube-system/kustomization.yaml
In relation to issues #1312 and #1061
=> Add INSTALL.md with pointers to plugin and operator installation + new HELM instructions

test/e2e/dlb/dlb.go, test/e2e/dsa/dsa.go, test/e2e/iaa/iaa.go, test/e2e/qat/qatplugin_dpdk.go, test/e2e/qat/qatplugin_kernel.go, test/e2e/qat/qatplugin_qatgen4_crypto.go
Restructure e2e tests from a single It() as follows:
Describe("device")
*BeforeEach("deploys plugin")
**Context("When device resources are available")
***BeforeEach("checks if resources are available")
****It("runs a pod requesting resources")
****It("runs another pod requesting resources if there is")
=> e2e: make tests divided into smaller parts (DLB, DSA, IAA, QAT) 

build/docker/intel-idxd-config-initcontainer.Dockerfile, build/docker/templates/intel-idxd-config-initcontainer.Dockerfile.in, demo/crypto-perf/Dockerfile, demo/dlb-dpdk-demo/Dockerfile
=> images: move to Debian packaged accel-config

pkg/deviceplugin/server.go
When more than one device ID is Allocate()'d to a container, Envs/Annotations for all but the last device ID get lost because their cresp.* maps are (re-)instantiated on each loop.
Fix it by doing that only once.
Fixes: 55f3e17
/cc @bart0sh need your approval
=> pkg/deviceplugin: do not reset Envs/Annotations from previous loops

cmd/gpu_plugin/rm/gpu_plugin_resource_manager.go, cmd/gpu_plugin/rm/gpu_plugin_resource_manager_test.go, deployments/gpu_plugin/base/intel-gpu-plugin.yaml, deployments/gpu_plugin/overlays/fractional_resources/add-kubelet-crt-mount.yaml, deployments/gpu_plugin/overlays/fractional_resources/gpu-manager-role.yaml, deployments/gpu_plugin/overlays/fractional_resources/kustomization.yaml, deployments/operator/rbac/gpu_manager_role.yaml, deployments/operator/rbac/role.yaml, pkg/controllers/gpu/controller.go, pkg/controllers/gpu/controller_test.go, pkg/controllers/reconciler.go
In large clusters with resource management, gpu-plugins cause high load to api-server. These changes will move the load from api-server to kubelet. If kubelet API isn't available, fetching will be done from api-server, but for example the cleanup method isn't activated as often as before.
=> Gpu: Kubelet API use and less frequent cleanup

cmd/gpu_plugin/gpu_plugin.go, cmd/gpu_plugin/gpu_plugin_test.go
oneCCL requires the /dev/dri/by-path folder to be available to create a mapping between GPUs.
=> gpu: mount by-path directory

scripts/test-image-base-layer.sh
with docker 23.0.0, the builder defaults to Buildx which changed how multi-stage builds are done. It looks the images used during builds are no longer part of "docker images" which make the image base layer test to fail:
Testing docker.io/intel/intel-deviceplugin-operator:devel base layer Error: No such object: gcr.io/distroless/static
ERROR: failed to inspect gcr.io/distroless/static
Therefore, we must ensure gcr.io/distroless/static is pulled before the image base layer is checked.
=> ci: fix image base layer test

cmd/gpu_plugin/README.md, cmd/operator/README.md
Updates for documentation from #1045.
Fixes: #1381
Fixes: #1132 
Fixes: #1059
=> Doc updates

cmd/qat_plugin/README.md, cmd/qat_plugin/qat_plugin.go, deployments/qat_plugin/overlays/qat_initcontainer/kustomization.yaml, deployments/qat_plugin/overlays/qat_initcontainer/qat.conf, deployments/qat_plugin/overlays/qat_initcontainer/qat_initcontainer.yaml, test/e2e/qat/qatplugin_dpdk.go
divide the current test case into two cases:
-without any configMap set
-with configMap set for cy service
The structure of e2e test flows is as follows:
** Case 1: without configMap set
- JustBeforeEach(deploying QAT plugin)
- Context
- It(checks if resources are available)
** Case 2: with configMap set
- BeforeEach(createing a configMap)
- JustBeforeEach(deploying QAT plugin)
- Context
- JustBeforeEach(checks if resources are available)
- It(runs a test pod)
- [It(runs another test pod)]*
=> qat init: make qat.conf optional

cmd/gpu_plugin/gpu_plugin.go, cmd/gpu_plugin/gpu_plugin_test.go
With shared-dev-num and multiple i915s in the resource request, try to find as many individual GPUs to expose to the container.
Previously, with multiple i915 resources, it was typical to get only one GPU device in the container.
Fixes: #1377
=> gpu: change 'none' allocation policy

demo/dlb-dpdk-demo/Dockerfile, demo/dlb-libdlb-demo/Dockerfile
Fixes: #1405 
e2e test runs successfully with 8.3.0 driver.
With 8.0.0 driver, 'epoll' test fails. So, system should have 8.3.0 driver installed
=> dlb: update demo to use dlb 8.3.0

test/envtest/suite_test.go
to mitigate spurious errors with:
E0515 15:28:06.626887 1995892 listener.go:48] "controller-runtime/metrics: metrics server failed to listen. You may want to disable the metrics server or use another port if it is due to conflicts" err="error lis tening on :8080: listen tcp :8080: bind: address already in use"
disable metrics completely. Moreover, check for error value from NewManager() before proceeding with the tests to avoid crashes.
This makes envtest more robust but the up()/down() logic needs careful review to ensure there are no race conditions.
=> envtest: disable controller metrics in tests

cmd/qat_plugin/README.md
default qat.conf file does not exist any more. Update it to make user create own conf file or use --from-literal instead.
=> doc, qat: update document

demo/dlb-init.sh
Even if sriov_numvfs is not found, do not finish with an error.
It is necessary because VM still recognizes VF's BDF as xx.xx.0,
and script tries to find sriov_numvfs. So, chnage the script just
print some informational message and end with exit 0.
=>  dlb: make init script end with exit 0 when sriov_numvfs not found 

.github/workflows/e2e.yml
Disable gpu e2e as the worker is currently broken.
=> disable gpu e2e test temporarily

pkg/controllers/qat/controller.go, test/envtest/qatdeviceplugin_controller_test.go
setInitContainer() adds "init-sriov-numvfs" to initContainers but uses initcontainerName constant to search where to add the QAT configMap volumeMount. Fix by moving all code to use the const.
It was also noticed in the controller logs that setting Pod Volumes is not idempotent but broken DaemonSet gets created:
""intel-device-plugins-manager: Reconciler error "err="DaemonSet.apps \"intel-qat-plugin\" is invalid: spec.template.spec.volumes[6].name: Duplicate value: \"qat-config\"" controller="qatdeviceplugin" controllerGroup="deviceplugin.intel.com"
Finally, change 'qat-config' to 'intel-qat-config-volume' to better describe that it's a volume.
=> operator: fix setting QAT provisioning config volumeMount

demo/dsa.conf, deployments/dsa_plugin/overlays/dsa_initcontainer/dsa-config.yaml
fixes: #1445 
token related attributes got deprecated. To remove warnings, replace with read_buff.
=> dsa: replace token with read_buffer in conf

.github/workflows/ci.yaml, Makefile
=> Disable VPU plugin builds

deployments/operator/rbac/role.yaml, pkg/controllers/iaa/controller.go
=> operator: add missing IaaDevicePlugin finalizers RBAC

deployments/dsa_plugin/base/intel-dsa-plugin.yaml, deployments/dsa_plugin/overlays/dsa_initcontainer/dsa_initcontainer.yaml, deployments/iaa_plugin/base/intel-iaa-plugin.yaml, deployments/iaa_plugin/overlays/iaa_initcontainer/iaa_initcontainer.yaml, pkg/controllers/dsa/controller.go, pkg/controllers/dsa/controller_test.go, pkg/controllers/iaa/controller.go, pkg/controllers/iaa/controller_test.go
Proper SELinux labels are required for the plugins to run in SELinux enabled clusters like openshift. These labels are custom made for plugins and are part of container-selinux package. Add these labels to IAA and DSA.
=> Add SELinux Labels for DSA and IAA

cmd/qat_plugin/kerneldrv/kerneldrv.go
…OV device of QAT
The string of the sIOV device type exceeds the range of [[alnum]], such as: # adf_ctl status
Checking status of all devices.
There is 2 QAT acceleration device(s) in the system:
qat_dev0 - type: vqat-adi,  inst_id: 0,  node_id: 0,  bsf: 0000:00:08.0,  #accel: 1 #engines: 1 state: up
qat_dev1 - type: vqat-adi,  inst_id: 1,  node_id: 0,  bsf: 0000:00:09.0,  #accel: 1 #engines: 1 state: up
=> Change the regular expression of the device type to support sIOV device

test/e2e/dsa/dsa.go, test/e2e/iaa/iaa.go, test/e2e/operator/operator.go, test/e2e/sgx/sgx.go
While working for #1470, I noticed that we have go-cognit's min-complexity value is 31 and in many parts, it is already so close to the value that little addition of the code causes an error message from the linter check.
I do not know if we need to decide to ignore that check for e2e tests, but there is one thing we can improve already.
Tests with operator have duplicate code, and seems to be right decision to make a common function in utils.go.
=> e2e: remove duplicate code of testing with operator

test/e2e/sgx/sgx.go
Structure is as follows:
```
Structure is as follows:
Describe("SGX plugin")
BeforeEach("deploys plugin")
Context("When device resources are available")
BeforeEach("checks if resources are available")
It("runs a pod requesting resources")
AfterEach("undeploys plugin")
```
This is basically same structure as DSA, DLB, IAA, QAT E2E tests (#1263).
=> e2e,sgx: divide single It() to have multiple layers

.github/workflows/e2e.yml, demo/sgx-sdk-demo/Dockerfile, scripts/set-version.sh, test/e2e/sgx/sgx.go
Busybox does not run anything inside the container, and it does not test with real resources. Use sgx-sdk-demo image instead.
* #1469 should be merged first, and then this should be rebased.
=> sgx: use sgx-sdk-demo app instead of busybox

test/e2e/dlb/dlb.go, test/e2e/dsa/dsa.go, test/e2e/fpga/fpga.go, test/e2e/gpu/gpu.go, test/e2e/iaa/iaa.go, test/e2e/qat/qatplugin_dpdk.go, test/e2e/qat/qatplugin_kernel.go, test/e2e/sgx/sgx.go, test/e2e/utils/utils.go
=> e2e: make demo pod logged only when failed running

deployments/fpga_admissionwebhook/webhook/manifests.yaml, deployments/operator/webhook/manifests.yaml, deployments/sgx_admissionwebhook/webhook/manifests.yaml, pkg/fpgacontroller/patcher/patchermanager.go, pkg/webhooks/sgx/sgx.go
FPGA and SGX webhooks mutate container resources which are immutable. Therefore, stop processing pod updates and act on creation only.
Fixes: #1357
=> webhooks: stop handling Pod updates

Jenkinsfile
kind tests were dropped from GHA long time ago as they were time consuming and did not improve test coverage.
Jenkins had those tests still running and they worked fine until they were made HW dependent.
This change drops kind tests from CI completely.
=> ci: drop kind tests from Jenkins too

test/e2e/dsa/dsa.go, test/e2e/iaa/iaa.go
Because of the indentation of code, it seems a bit dirty, but the only change is that the outermost layer
`ginkgo.Describe("Without using operator", func() {})` is removed.
=> e2e,dsa,iaa: remove unnecessary layer ginkgo.Describe

.github/workflows/devel.yaml, .github/workflows/e2e.yaml, .github/workflows/lib-build.yaml, .github/workflows/lib-e2e.yaml, .github/workflows/lib-publish.yaml, .github/workflows/lib-trivy.yaml, .github/workflows/lib-validate.yaml, .github/workflows/release.yaml, .github/workflows/template/trivy-csv.tpl, .gitignore, .trivyignore, Makefile
=> workflows: rework, trivy & publish

cmd/gpu_fakedev/gpu_fakedev.go
This adds generation of the sys/bus folder files, so that dra can use the generated files to an extent.
=> gpu_fakedev: better dra support

DEVEL.md, Makefile, cmd/operator/README.md, pkg/controllers/dlb/controller.go, pkg/controllers/dsa/controller.go, pkg/controllers/fpga/controller.go, pkg/controllers/gpu/controller.go, pkg/controllers/iaa/controller.go, pkg/controllers/qat/controller.go, pkg/controllers/reconciler.go, pkg/controllers/reconciler_test.go, pkg/controllers/sgx/controller.go
=> operator: add image upgrade with env vars

.github/workflows/lib-e2e.yaml, DEVEL.md, Makefile, test/e2e/dlb/dlb.go, test/e2e/dsa/dsa.go, test/e2e/fpga/fpga.go, test/e2e/gpu/gpu.go, test/e2e/iaa/iaa.go, test/e2e/qat/qatplugin_dpdk.go, test/e2e/qat/qatplugin_kernel.go, test/e2e/sgx/sgx.go
=> e2e: make running subsets of e2e tests more organized

Makefile, build/docker/intel-deviceplugin-operator.Dockerfile, build/docker/intel-dlb-initcontainer.Dockerfile, build/docker/intel-dlb-plugin.Dockerfile, build/docker/intel-dsa-plugin.Dockerfile, build/docker/intel-fpga-admissionwebhook.Dockerfile, build/docker/intel-fpga-initcontainer.Dockerfile, build/docker/intel-fpga-plugin.Dockerfile, build/docker/intel-gpu-fakedev.Dockerfile, build/docker/intel-gpu-initcontainer.Dockerfile, build/docker/intel-gpu-plugin.Dockerfile, build/docker/intel-iaa-plugin.Dockerfile, build/docker/intel-qat-initcontainer.Dockerfile, build/docker/intel-qat-plugin-kerneldrv.Dockerfile, build/docker/intel-qat-plugin.Dockerfile, build/docker/intel-sgx-admissionwebhook.Dockerfile, build/docker/intel-sgx-initcontainer.Dockerfile, build/docker/intel-sgx-plugin.Dockerfile, build/docker/intel-vpu-plugin.Dockerfile, build/docker/intel-xpumanager-sidecar.Dockerfile, build/docker/lib/golang_base.docker, go.mod
=> build: move to Go 1.21.x

.golangci.yml, README.md, cmd/qat_plugin/README.md, cmd/qat_plugin/dpdkdrv/dpdkdrv.go, cmd/qat_plugin/dpdkdrv/dpdkdrv_test.go, demo/qat-init.sh
=> qat: heartbeat support + new capabilities 

pkg/controllers/dlb/controller_test.go, pkg/controllers/dsa/controller_test.go, pkg/controllers/fpga/controller_test.go, pkg/controllers/gpu/controller_test.go, pkg/controllers/qat/controller_test.go, pkg/controllers/sgx/controller_test.go, pkg/webhooks/sgx/sgx.go
=> controller cleanups

cmd/operator/README.md, pkg/apis/deviceplugin/v1/dlbdeviceplugin_webhook.go, pkg/apis/deviceplugin/v1/dsadeviceplugin_webhook.go, pkg/apis/deviceplugin/v1/fpgadeviceplugin_webhook.go, pkg/apis/deviceplugin/v1/gpudeviceplugin_webhook.go, pkg/apis/deviceplugin/v1/iaadeviceplugin_webhook.go, pkg/apis/deviceplugin/v1/qatdeviceplugin_webhook.go, pkg/apis/deviceplugin/v1/sgxdeviceplugin_webhook.go, pkg/controllers/dlb/controller.go, pkg/controllers/dlb/controller_test.go, pkg/controllers/dsa/controller.go, pkg/controllers/dsa/controller_test.go, pkg/controllers/fpga/controller.go, pkg/controllers/fpga/controller_test.go, pkg/controllers/gpu/controller.go, pkg/controllers/gpu/controller_test.go, pkg/controllers/iaa/controller.go, pkg/controllers/iaa/controller_test.go, pkg/controllers/qat/controller.go, pkg/controllers/qat/controller_test.go, pkg/controllers/reconciler.go, pkg/controllers/sgx/controller.go, pkg/controllers/sgx/controller_test.go, test/envtest/dlbdeviceplugin_controller_test.go, test/envtest/dsadeviceplugin_controller_test.go, test/envtest/fpgadeviceplugin_controller_test.go, test/envtest/gpudeviceplugin_controller_test.go, test/envtest/iaadeviceplugin_controller_test.go, test/envtest/qatdeviceplugin_controller_test.go, test/envtest/sgxdeviceplugin_controller_test.go
Differentiate objects by adding cr names as suffixes
Drop kind book keeping and related functions from controllers
Make serviceaccounts and clusterrolebindings shared between GPU CRs.
Deny GPU CRs with mixed resource manager selections.
Fixes #1529
=> operator: remove one-cr-per-kind limitation

.github/workflows/ci.yaml, .github/workflows/devel.yaml, .github/workflows/lib-build.yaml, .github/workflows/lib-codeql.yaml, .github/workflows/lib-publish.yaml, .github/workflows/lib-scorecard.yaml, .github/workflows/lib-trivy.yaml, .github/workflows/lib-validate.yaml, README.md
Tweak token permissions and add scorecard badge.
=> workflows: add scorecard and codeql

deployments/sgx_plugin/overlays/epc-nfd/kustomization.yaml, deployments/sgx_plugin/overlays/epc-nfd/nfd_label.yaml
Our SGX README guides users to first deploy NFD and create NodeFeatureRules when sgx_plugin/overlays/epc-nfd is used. However, it turns out the "SGX enabled" label is not being used by the plugin DaemonSet.
Use "intel.feature.node.kubernetes.io/sgx": "true" as the nodeSelector value when the kustomization overlay with NFD is used.
/cc @ffuerste
=> sgx: use NodeFeatureRule SGX label in the NFD overlay

cmd/fpga_admissionwebhook/main.go, cmd/operator/main.go, cmd/sgx_admissionwebhook/main.go, pkg/fpgacontroller/fpgacontroller_test.go, pkg/fpgacontroller/patcher/patcher_test.go, pkg/fpgacontroller/patcher/patchermanager_test.go, test/envtest/suite_test.go
klog has added ktesting/textlogger and is going to deprecate klogr. The deprecation is going to trigger golangci-lint (staticcheck) errors so rework the logging and move to ktesting/textlogger.
The commit also fixes the loglevel setting with operator.
Split from #1584
=> logging: move away from klogr to ktesting/textlogger

build/docker/intel-dlb-initcontainer.Dockerfile, build/docker/intel-idxd-config-initcontainer.Dockerfile, build/docker/intel-qat-initcontainer.Dockerfile, build/docker/templates/intel-dlb-initcontainer.Dockerfile.in, build/docker/templates/intel-idxd-config-initcontainer.Dockerfile.in, build/docker/templates/intel-qat-initcontainer.Dockerfile.in
=> dlb, idxd, qat: install LICENSE to initcontainer

.github/workflows/release.yaml
Attempt to fix this:
[Invalid workflow file: .github/workflows/release.yaml#L23](https://github.com/intel/intel-device-plugins-for-kubernetes/actions/runs/7273880873/workflow)
The workflow is not valid. .github/workflows/release.yaml (Line: 23, Col: 3): Error calling workflow 'intel/intel-device-plugins-for-kubernetes/.github/workflows/lib-trivy.yaml@49d59d4eb60baae858d3403eb3f07b3e52b830d0'. The workflow is requesting 'actions: read', but is only allowed 'actions: none'. .github/workflows/release.yaml (Line: 23, Col: 3): Error calling workflow 'intel/intel-device-plugins-for-kubernetes/.github/workflows/lib-trivy.yaml@49d59d4eb60baae858d3403eb3f07b3e52b830d0'. The nested job 'trivy-scan-vulns' is requesting 'security-events: write', but is only allowed 'security-events: none'.
=> workflow: fix permissions for release

demo/sgx-sdk-demo/Dockerfile
Hopefully fixes random failures with e2e-sgx.
=> e2e: sgx: fetch SGX DC attestation primitives as tar.gz

deployments/operator/rbac/role.yaml, pkg/controllers/reconciler.go
Remove the privileged section as it is not needed for openshift. Tested in Openshift 4.13 cluster with 0.28.0 build.
=> privileged is not needed for openshift

test/e2e/fpga/fpga.go
fpga test fails due to webhook not being ready/available when the pod is scheduled. Fix test by waiting for webhook to be running&ready.
=> e2e: fpga: fix intermittent failures

cmd/qat_plugin/README.md, deployments/qat_plugin/base/intel-qat-plugin.yaml, deployments/qat_plugin/overlays/apparmor_unconfined/kustomization.yaml, deployments/qat_plugin/overlays/e2e/kustomization.yaml, pkg/controllers/qat/controller.go, pkg/controllers/qat/controller_test.go
=> qat: Add AppArmor unconfided anntotation configurability in the operator

.github/workflows/lib-validate.yaml
Step gets stuck and we seem to be using a deprecated way to create the report.
=> workflow: disable codecov report

.github/workflows/lib-e2e.yaml, cmd/qat_plugin/README.md, cmd/qat_plugin/dpdkdrv/dpdkdrv.go, cmd/qat_plugin/qat_plugin.go, demo/qat-init.sh, deployments/nfd/overlays/node-feature-rules/node-feature-rules.yaml, deployments/operator/crd/bases/deviceplugin.intel.com_qatdeviceplugins.yaml, deployments/operator/samples/deviceplugin_v1_qatdeviceplugin.yaml, pkg/apis/deviceplugin/v1/qatdeviceplugin_types.go, pkg/apis/deviceplugin/v1/qatdeviceplugin_webhook.go, pkg/controllers/qat/controller.go
=> Add QAT support for 420xx driver and the 4946 device (GNR-D)

.github/dependabot.yml, .github/workflows/lib-build.yaml, .github/workflows/lib-codeql.yaml, .github/workflows/lib-e2e.yaml, .github/workflows/lib-publish.yaml, .github/workflows/lib-scorecard.yaml, .github/workflows/lib-trivy.yaml, .github/workflows/lib-validate.yaml, .github/workflows/publish.yml
Fix issues generated by the scorecard.
=> Pin workflow actions sha's

INSTALL.md, cmd/qat_plugin/README.md, cmd/qat_plugin/qat_plugin.go, deployments/operator/samples/deviceplugin_v1_qatdeviceplugin.yaml
The devices searched by default are QAT Gen4+ only.
=> qat: drop c6xxvf from defaults

demo/accel-config-demo/Dockerfile
=> demo: accel-config-demo updates

pkg/fpga/pci_linux.go
Adds subsystem vendor and device information to PCIDevice struct.
Useful for distinguishing different FPGA boards driven by the DFL driver, where vendor and device ID are the same ([DFL PCI IDs](https://github.com/OFS/dfl-feature-id/blob/main/dfl-pci-ids.rst)).
=> fpga: add subsystem vendor & device fields to PCIDevice

deployments/dlb_plugin/base/intel-dlb-plugin.yaml, deployments/dsa_plugin/base/intel-dsa-plugin.yaml, deployments/fpga_plugin/base/intel-fpga-plugin-daemonset.yaml, deployments/gpu_plugin/base/intel-gpu-plugin.yaml, deployments/iaa_plugin/base/intel-iaa-plugin.yaml, deployments/qat_plugin/base/intel-qat-kernel-plugin.yaml, deployments/qat_plugin/base/intel-qat-plugin.yaml, deployments/sgx_plugin/base/intel-sgx-plugin.yaml, pkg/controllers/dlb/controller_test.go, pkg/controllers/dsa/controller_test.go, pkg/controllers/fpga/controller_test.go, pkg/controllers/gpu/controller_test.go, pkg/controllers/iaa/controller_test.go, pkg/controllers/qat/controller_test.go, pkg/controllers/sgx/controller_test.go
=> add updateStrategy to daemonSets

cmd/qat_plugin/dpdkdrv/dpdkdrv.go
Plugin used to consider only the value "-1" but there are some cases when files show "\n" or "\n\x00". This makes plugin to have wrong status of the device. So, trim the value after \n so only numerical value can be read.
=> QAT: make plugin read trimmed heartbeat status

.github/workflows/devel.yaml, .github/workflows/lib-publish.yaml, .github/workflows/release.yaml, README.md
Signs release containers with `cosign`. Also modified the publish workflow to support other registries. Makes it easier to test changes.
Tests:
https://hub.docker.com/repository/docker/tkatila/intel-gpu-plugin/tags
Test runs:
https://github.com/tkatila/intel-device-plugins-for-kubernetes/actions/runs/10367001757/job/28697484565
https://github.com/tkatila/intel-device-plugins-for-kubernetes/actions/runs/10367083492/job/28697736086
cosign can be used to verify containers:
`cosign verify --certificate-oidc-issuer https://token.actions.githubusercontent.com --certificate-identity-regexp https://github.com/tkatila/intel-device-plugins-for-kubernetes/.github/workflows/lib-publish.yaml.* tkatila/intel-gpu-plugin:0.30.101  | jq .`
=> workflow: sign release containers

cmd/xpumanager_sidecar/README.md, cmd/xpumanager_sidecar/main.go, deployments/xpumanager_sidecar/base/kustomization.yaml, deployments/xpumanager_sidecar/kustomization.yaml, deployments/xpumanager_sidecar/overlays/cert-manager/certs.yaml, deployments/xpumanager_sidecar/overlays/cert-manager/kustomization.yaml, deployments/xpumanager_sidecar/overlays/cert-manager/xpumanager.yaml, deployments/xpumanager_sidecar/overlays/http/kustomization.yaml, deployments/xpumanager_sidecar/overlays/http/xpumanager.yaml
Add deployment that uses cert-manager to provide self-signed certificates
Add functionality to verify server endpoint in the sidecar
=> xpumanager sidecar: verify certificate with HTTPS

.golangci.yml, cmd/gpu_plugin/README.md, cmd/gpu_plugin/gpu_plugin.go, cmd/gpu_plugin/gpu_plugin_test.go, deployments/gpu_plugin/base/intel-gpu-plugin.yaml, pkg/controllers/gpu/controller_test.go, test/e2e/dlb/dlb.go, test/e2e/dsa/dsa.go, test/e2e/fpga/fpga.go, test/e2e/gpu/gpu.go, test/e2e/iaa/iaa.go, test/e2e/operator/operator.go, test/e2e/qat/qatplugin_dpdk.go, test/e2e/qat/qatplugin_kernel.go, test/e2e/sgx/sgx.go, test/e2e/utils/utils.go
This is on top of the generic CDI restructuring: https://github.com/intel/intel-device-plugins-for-kubernetes/pull/1810
=> GPU-plugin: add cdi support

.github/workflows/lib-publish.yaml
Cache av databases to save download bw with each image
=> workflow: add malware scan for publish

build/docker/intel-deviceplugin-operator.Dockerfile, build/docker/intel-dlb-plugin.Dockerfile, build/docker/intel-dsa-plugin.Dockerfile, build/docker/intel-fpga-admissionwebhook.Dockerfile, build/docker/intel-fpga-initcontainer.Dockerfile, build/docker/intel-fpga-plugin.Dockerfile, build/docker/intel-gpu-fakedev.Dockerfile, build/docker/intel-gpu-initcontainer.Dockerfile, build/docker/intel-gpu-plugin.Dockerfile, build/docker/intel-iaa-plugin.Dockerfile, build/docker/intel-qat-plugin-kerneldrv.Dockerfile, build/docker/intel-qat-plugin.Dockerfile, build/docker/intel-sgx-admissionwebhook.Dockerfile, build/docker/intel-sgx-initcontainer.Dockerfile, build/docker/intel-sgx-plugin.Dockerfile, build/docker/intel-xpumanager-sidecar.Dockerfile, build/docker/lib/default_args.docker, build/docker/lib/default_build.docker, build/docker/templates/intel-qat-plugin-kerneldrv.Dockerfile.in, pkg/deviceplugin/server.go
One is from static scan. The other is not really an issue but I noticed with asmflags, gcflags and ldflags that the flag handling could be better. This came up while working with the [GPU levelzero PR](#1803 ).
=> Misc fixes vol. 9/2024

cmd/gpu_levelzero/ze.h, cmd/gpu_levelzero/zes.c
Static scan notified that calloc's return value wasn't checked.
=> levelzero: add missing calloc return value check

deployments/dlb_plugin/base/intel-dlb-plugin.yaml, deployments/dsa_plugin/base/intel-dsa-plugin.yaml, deployments/fpga_plugin/base/intel-fpga-plugin-daemonset.yaml, deployments/gpu_plugin/base/intel-gpu-plugin.yaml, deployments/iaa_plugin/base/intel-iaa-plugin.yaml, deployments/qat_plugin/base/intel-qat-plugin.yaml, deployments/sgx_plugin/base/intel-sgx-plugin.yaml, pkg/controllers/dlb/controller_test.go, pkg/controllers/dsa/controller_test.go, pkg/controllers/fpga/controller_test.go, pkg/controllers/gpu/controller_test.go, pkg/controllers/iaa/controller_test.go, pkg/controllers/qat/controller_test.go, pkg/controllers/sgx/controller_test.go
Operator maturity level 3 requires cpu/memory requests and limits for operands. Add them to all plugins deployed by operator.
=> Add cpu/memory requests and limits

deployments/operator/default/manager_auth_proxy_patch.yaml
As kubebuilder does not provide rbac-proxy containers anymore, move to bitnami/vmware containers.
=> operator: kube-rbac-proxy to 0.18.1

build/docker/intel-qat-initcontainer.Dockerfile, build/docker/templates/intel-qat-initcontainer.Dockerfile.in, cmd/qat_plugin/README.md, demo/qat-autoreset.sh, demo/qat-init.sh
For some reason, the previous pr #1838 is closed.
I make another pr.
=>  qat, initcontainer: add enablement of auto_reset

deployments/operator/default/kustomization.yaml, deployments/operator/device/dlb/dlb.yaml, deployments/operator/device/dsa/dsa.yaml, deployments/operator/device/fpga/fpga.yaml, deployments/operator/device/gpu/gpu.yaml, deployments/operator/device/qat/qat.yaml, deployments/operator/device/sgx/sgx.yaml
To sync with operator bundle that has been 'intel-deviceplugins-' since 0.30.0 version, change the name prefix.
=> operator: change name prefix of controller-manager

.github/workflows/lib-e2e.yaml, test/e2e/qat/qatplugin_dpdk.go, test/e2e/utils/utils.go
This is draft for suggesting an idea and getting opinions.!
=> qat,e2e: add heartbeat and auto-reset validation

pkg/controllers/reconciler.go, pkg/controllers/reconciler_test.go
fixes: #1873 
Operatorhub bundle can have sha256 image tags that are put through env vars. When operator controller manager gets upgraded, its operands (plugin daemonsets) should be updated to the image in the env vars. But it has not been working properly because of wrong parsing.
Fix it to parse the image names that have sha256 tags correctly so env vars in operator can be used as intended.
=> operator: fix upgradeImages

.github/workflows/lib-e2e.yaml, demo/openssl-qat-engine/Dockerfile, test/e2e/qat/qatplugin_dpdk.go
=> QAT, e2e: add qat-engine's testapp case

build/docker/intel-deviceplugin-operator.Dockerfile, build/docker/intel-dlb-initcontainer.Dockerfile, build/docker/intel-dlb-plugin.Dockerfile, build/docker/intel-dsa-plugin.Dockerfile, build/docker/intel-fpga-admissionwebhook.Dockerfile, build/docker/intel-fpga-initcontainer.Dockerfile, build/docker/intel-fpga-plugin.Dockerfile, build/docker/intel-gpu-fakedev.Dockerfile, build/docker/intel-gpu-initcontainer.Dockerfile, build/docker/intel-gpu-levelzero.Dockerfile, build/docker/intel-gpu-plugin.Dockerfile, build/docker/intel-iaa-plugin.Dockerfile, build/docker/intel-qat-initcontainer.Dockerfile, build/docker/intel-qat-plugin-kerneldrv.Dockerfile, build/docker/intel-qat-plugin.Dockerfile, build/docker/intel-sgx-admissionwebhook.Dockerfile, build/docker/intel-sgx-initcontainer.Dockerfile, build/docker/intel-sgx-plugin.Dockerfile, build/docker/intel-xpumanager-sidecar.Dockerfile, build/docker/lib/default_plugin.docker, build/docker/templates/intel-dlb-initcontainer.Dockerfile.in, build/docker/templates/intel-fpga-initcontainer.Dockerfile.in, build/docker/templates/intel-gpu-initcontainer.Dockerfile.in, build/docker/templates/intel-gpu-levelzero.Dockerfile.in, build/docker/templates/intel-qat-initcontainer.Dockerfile.in, build/docker/templates/intel-qat-plugin-kerneldrv.Dockerfile.in, build/docker/templates/intel-sgx-initcontainer.Dockerfile.in, demo/crypto-perf/Dockerfile, demo/dlb-dpdk-demo/Dockerfile
We use 'as' and 'FROM' keywords which do not match with each other.
Use 'AS' instead of 'as'.
=> Dockerfiles: fix warning for 'FromAsCasing'

pkg/apis/deviceplugin/v1/dlbdeviceplugin_webhook.go, pkg/apis/deviceplugin/v1/dsadeviceplugin_webhook.go, pkg/apis/deviceplugin/v1/fpgadeviceplugin_webhook.go, pkg/apis/deviceplugin/v1/gpudeviceplugin_webhook.go, pkg/apis/deviceplugin/v1/iaadeviceplugin_webhook.go, pkg/apis/deviceplugin/v1/qatdeviceplugin_webhook.go, pkg/apis/deviceplugin/v1/sgxdeviceplugin_webhook.go, pkg/apis/deviceplugin/v1/webhook_common.go
the next controller-runtime drops deprecated `webhook.Defaulter/Validator`. Move to `admission.CustomDefaulter/Validator`
=> operator: rework webhooks

.github/workflows/lib-codeql.yaml
Noticed some time ago that codeql phase had this error in the logs:
```
cd cmd/gpu_levelzero; go build -tags ""
ze.c:19:10: fatal error: ze_api.h: No such file or directory
19 | #include <ze_api.h>
|          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:115: gpu_levelzero] Error 1
2024/11/26 10:56:36 Running /usr/bin/make [make] failed, continuing anyway: exit status 2
```
This is an attempt to fix it.
=> codeql: install libze to allow full analysis

.github/workflows/lib-publish.yaml, demo/crypto-perf/Dockerfile
crypto-perf tests are failing on e2e-spr. Also, stop publishing `crypto-perf` and `opae-nlb-demo`. Their original purpose is now gone.
=> ci: crypto-perf updates

.github/workflows/devel.yaml, .github/workflows/lib-trivy.yaml, .github/workflows/trivy-periodic.yaml
Fail trivy vuln scan cleanly and create a periodic trivy scan to upload results to Github's security.
Trivy-action doesn't work too well when it's executed multiple times in the job. The env variables the action sets spill over to the next step and the step might be executed incorrectly. In our case, the "show report in human-readable format" actually just converted the json format back to json format and it didn't show the actual vulnerability in the action's logs.
=> workflow: improve trivy vulnerability scanning

deployments/dlb_plugin/base/intel-dlb-plugin.yaml, deployments/dsa_plugin/base/intel-dsa-plugin.yaml, deployments/fpga_plugin/base/intel-fpga-plugin-daemonset.yaml, deployments/gpu_plugin/base/intel-gpu-plugin.yaml, deployments/gpu_plugin/overlays/levelzero/levelzero.yaml, deployments/iaa_plugin/base/intel-iaa-plugin.yaml, deployments/qat_plugin/base/intel-qat-plugin.yaml, deployments/sgx_plugin/base/intel-sgx-plugin.yaml, pkg/controllers/dlb/controller_test.go, pkg/controllers/dsa/controller_test.go, pkg/controllers/fpga/controller_test.go, pkg/controllers/gpu/controller_test.go, pkg/controllers/iaa/controller_test.go, pkg/controllers/qat/controller_test.go, pkg/controllers/sgx/controller_test.go
=> depl: drop capabilities from all plugins

test/e2e/fpga/fpga.go
During tests a second plugin started running before the first one had exited. It resulted in the plugin going to crashloop and the workload getting stuck.
=> e2e: fpga: fix false failure

cmd/qat_plugin/README.md, cmd/qat_plugin/dpdkdrv/dpdkdrv.go, demo/qat-init.sh, deployments/operator/samples/deviceplugin_v1_dlbdeviceplugin.yaml, deployments/operator/samples/deviceplugin_v1_qatdeviceplugin.yaml, deployments/qat_plugin/base/intel-qat-plugin.yaml, pkg/controllers/qat/controller.go, pkg/controllers/qat/controller_test.go, test/envtest/qatdeviceplugin_controller_test.go
It's been GA since k8s 1.30 so we can enable it unconditionally starting with our 0.32 release.
Fixes: #1818
Fixes: #1887
=> qat: drop AppArmor annotations

.trivyignore
as it invalidly detects missing security context in patch files
=> trivy: ignore KSV-0118

cmd/gpu_plugin/README.md, cmd/gpu_plugin/fractional.md
=> Add deprecation notices about GAS

deployments/nfd/base/kustomization.yaml, deployments/nfd/overlays/node-feature-rules/node-feature-rules.yaml
Based on
https://github.com/torvalds/linux/commit/4fecf944c051ea852e98c062636bf5b4c7f5f8a7
https://github.com/torvalds/linux/commit/f91f2a9879cc77db1f45f690f38f42698580416e
=> deployments: nfd: update DSA/IAA PCI IDs and nfd version

.github/workflows/lib-build.yaml, .github/workflows/lib-e2e.yaml, .github/workflows/lib-publish.yaml, Makefile
also remove e2e-fpga from workflows
part of #1946 
part of #1765
=> build: drop dlb and fpga related images

.github/workflows/lib-build.yaml, .github/workflows/lib-e2e.yaml, README.md, cmd/dsa_plugin/README.md, demo/dsa-dpdk-dmadevtest.yaml, demo/dsa-dpdk-dmadevtest/Dockerfile, demo/dsa.conf, go.mod, go.sum, scripts/set-version.sh, test/e2e/dsa/dsa.go
=> dsa: dpdk example workload and use it in e2e

DEVEL.md, Makefile, PROJECT, deployments/operator/manifests/bases/intel-device-plugins-operator.clusterserviceversion.yaml, deployments/operator/manifests/kustomization.yaml
=> operator: fix outdated information

.github/dependabot.yml
As we track pinned github actions, we get an update every time a new tag appears for any action we use. Furthermore, as we have a scheduled run on Sundays, we get many single action update PRs that have accumulated during the week to work with on Monday mornings.
Group all github-actions updates to a single PR to help with PR merges and to avoid unnecessary CI runs.
=> dependabot: group all github-actions updates

demo/intelgpu-job-wsl.yaml, demo/intelgpu-job.yaml
This PR updates the GPU configuration in Kubernetes deployments on WSL by replacing the i915 driver with DXG (DirectX Graphics Kernel) to enhance GPU acceleration and compatibility with Windows-based environments.
**Testing & Validation:**
- Verified GPU acceleration in WSL-based Kubernetes containers.
- Ran sample workloads requiring GPU compute to ensure proper execution.
- Checked resource utilization and performance benchmarks.
**Impact:**
- Solves an issue where i915 not found on wsl machine.
=> Switching from i915 to DXG for GPU Acceleration in Kubernetes on WSL

.github/workflows/lib-validate.yaml, .golangci.yml, Makefile
The config file is migrated using golangci-lint migrate. Three new staticcheck checks got disabled (QF100x, 1,4, and 8).
=> ci: bump to golangi-lint v2

INSTALL.md, deployments/operator/manager/manager.yaml
=> operator: set pod security admission to privileged

.github/workflows/lib-e2e.yaml
Due to infrastructure updates, these e2e targets will have to be disabled.
=> github: disable gnr(d) e2e targets

build/docker/intel-gpu-levelzero.Dockerfile, build/docker/templates/intel-gpu-levelzero.Dockerfile.in
Also install the igc-core components as they seem to be required. Sadly the container size will increase with little benefit.
Fixes: #2039
=> gpu levelzero: update the components to support LunarLake in WSL

cmd/operator/main.go, pkg/controllers/dlb/controller.go, pkg/controllers/dlb/controller_test.go, pkg/controllers/dsa/controller.go, pkg/controllers/dsa/controller_test.go, pkg/controllers/fpga/controller.go, pkg/controllers/fpga/controller_test.go, pkg/controllers/gpu/controller.go, pkg/controllers/gpu/controller_test.go, pkg/controllers/iaa/controller.go, pkg/controllers/iaa/controller_test.go, pkg/controllers/qat/controller.go, pkg/controllers/qat/controller_test.go, pkg/controllers/reconciler.go, pkg/controllers/sgx/controller.go, pkg/controllers/sgx/controller_test.go, test/envtest/suite_test.go
Change is split into two commits, one adding the support to provide the secrets, and  another to restructure how data is passed to the controllers. The restructuring can be dropped or the two can be merged.
Fixes #https://github.com/intel/intel-device-plugins-for-kubernetes/issues/1981
=> Allow providing a pull secret for the plugin daemonsets

cmd/gpu_plugin/gpu_plugin.go, cmd/gpu_plugin/gpu_plugin_test.go
One of the last changes in the allow/deny-list PR broke GPU plugin use without any list.
=> gpu: fix breakage with allow/deny list being empty

demo/crypto-perf/Dockerfile, demo/dsa-dpdk-dmadevtest/Dockerfile
On GNR, I noticed the dpdk-test-crypto-perf failed with this error:
```
EAL: Detected CPU lcores: 128
EAL: Detected NUMA nodes: 4
EAL: lcore 128 >= RTE_MAX_LCORE (128)
EAL: lcore 129 >= RTE_MAX_LCORE (128)
EAL: To use high physical core ids, please use --lcores to map them to lcore ids below RTE_MAX_LCORE, e.g. --lcores 0@1,1@128,2@129
EAL: invalid core list syntax
EAL: FATAL: Invalid 'command line' arguments.
EAL: Invalid 'command line' arguments.
EAL: Error - exiting with code: 1
Cause: Invalid EAL arguments!
'( )' can be omitted for single element group,
'@' can be omitted if cpus and lcores have the same value
```
In addition, update dpdk to a newer version.
These were done in July, but I had forgotten them until I ran e2e tests again.
=> qat: fix dpdk core selection on high core count systems
