intel/intel-device-plugins-for-kubernetes

README.md
here is how it looks like: https://github.com/bart0sh/intel-device-plugins-for-kubernetes/tree/PR0015-add-goreportcard-badge
=> add goreportcard.com badge

README.md
You can see how it looks [here](https://github.com/bart0sh/intel-device-plugins-for-kubernetes)
=> Add Intel logo to the README

demo/intelfpga-job.yaml
Explicitly request usage of HugePages and cpu in fpga demo
job spec as OPAE requires it.
Fixes #3
=> request usage of HugePages in the job spec

cmd/fpga_plugin/fpga_plugin.go, cmd/fpga_plugin/fpga_plugin_test.go
Plugin sets container annotation com.intel.fpga.mode to
intel.com/fpga-region or intel.com/fpga-regiondevel in
region and regiondevel modes.
This should allow to configure CRI-O to run reprogramming hooks
only when annotation is set.
=> fpga: set container annotations

cmd/fpga_plugin/devicecache/devicecache.go, cmd/fpga_plugin/devicecache/devicecache_test.go
When running in the region mode we don't need to know AFU IDs
thus don't read them while in the mode.
It's important not to try to read them because in the region mode
AFUs are supposed to be reprogrammed in the fly anyway and the
afu_id files may become busy.
=> fpga: ignore afu_id in region mode

cmd/fpga_plugin/fpga_plugin.go, cmd/fpga_plugin/fpga_plugin_test.go
When kubelet notifies the plugin about its restart by removing
the plugin's socket we do reconnect to kubelet, but we don't
send the current list of monitored devices to kubelet. As result
kubelet is not aware of discovered devices if it restarts.
Always send the current list of monitored devices to kubelet
upon ListAndWatch() request.
=> Send device list upon reconnecting to kubelet

Makefile
'make images' command fails with this error output:
...
docker build -f build/docker/intel-fpga-crihook.Dockerfile --build-arg
HTTP_PROXY --build-arg HTTPS_PROXY --build-arg NO_PROXY --build-arg
http_proxy --build-arg https_proxy --build-arg no_proxy --pull -t
intel-fpga-crihook:4ec2c4acb63ce677684c42d2eb986227182e0742 .
unable to prepare context: unable to evaluate symlinks in Dockerfile
path: lstat
build/docker/intel-fpga-crihook.Dockerfile:
no such file or directory
Makefile:46: recipe for target 'intel-fpga-crihook' failed
make: *** [intel-fpga-crihook] Error 1
This is caused by incorrect assumption that there is a Docker file for
every item in cmd/
Reimplemented 'make images' to build only images that have Docker
files in build/docker directory.
=> fix 'make images' failure

cmd/gpu_plugin/README.md
Edits for consistent format and text flow.
=> GPU readme edits for format and text flow.

README.md
Signed-off-by: MCamp859 <mary.camp@ptiglobal.net>
=> Edited text for clarity and flow.

cmd/qat_plugin/README.md
@swatisehgal  Please review these text edits. I have a couple open questions for you. 
Signed-off-by: MCamp859 <mary.camp@ptiglobal.net>
=> QAT readme edits for format and text flow.

.travis.yml
Added ```make images``` target to the .travis.yaml
=> Check image builds

deployments/fpga_admissionwebhook/mutating-webhook-configuration-tpl.yaml, deployments/fpga_admissionwebhook/rbac-config-tpl.yaml, scripts/webhook-deploy.sh
=> webhook: add --namespace option to deployment script

cmd/fpga_plugin/README.md
=> clarify fpga plugin modes in README.md

demo/test-fpga-region.yml
This file will be used in the FPGA Device Plugin demo to demonstrate
orchestration programmed FPGA workflow.
=> demo: add test-fpga-region.yml

cmd/gpu_plugin/README.md, deployments/gpu_plugin/gpu_plugin.yaml
Added DaemonSet yaml
Added deployment instructions to plugin's README
=> add GPU plugin deployment

demo/screencast.sh
Added screencast.sh script that generates asciinema screencast
for the FPGA demo "Intel FPGA Plugin for Kubernetes".
The screencast demonstrates build and deployment of the
FPGA plugin in orchestration programmed mode.
=> demo: add script that generates FPGA screencast

.travis.yml, build/docker/intel-fpga-admissionwebhook.Dockerfile, build/docker/intel-fpga-plugin.Dockerfile, build/docker/intel-gpu-plugin.Dockerfile, build/docker/intel-qat-plugin.Dockerfile, cmd/fpga_admissionwebhook/fpga_admissionwebhook.go, cmd/fpga_admissionwebhook/fpga_admissionwebhook_test.go, cmd/fpga_admissionwebhook/patcher.go, cmd/fpga_admissionwebhook/patcher_test.go, cmd/fpga_crihook/main.go, cmd/fpga_crihook/main_test.go, cmd/fpga_crihook/testdata/config-correct.json, cmd/fpga_crihook/testdata/config-no-FPGA-devices.json, cmd/fpga_crihook/testdata/config-no-afu.json, cmd/fpga_crihook/testdata/config-no-devices.json, cmd/fpga_crihook/testdata/config-no-linux.json, cmd/fpga_crihook/testdata/config-non-existing-bitstream.json
=> Add support for multiple FPGAs per container

demo/screencast.sh, deployments/fpga_admissionwebhook/mappings-collection.yaml
Upgrade to DCP 1.1 based on Dmitry's PR #111 
I only changed back device names Arria11->Arria10
=> dcp1.1 upgrade

demo/readme.md
Signed-off-by: MCamp859 <maryx.camp@intel.com>
@mjkadera @josepalafox  Please review and provide any feedback. Link to screencast will be added in an upcoming revision.
=> Add demo readme file to serve as landing page.

demo/readme.md
Updated url to point to the FPGA screencast with a Legal Disclaimer.
=> Demo readme: update FPGA screencast url

.travis.yml
It makes cloning a lot faster with --singe-branch --depth 1 options
Signed-off-by: Ed Bartosh <eduard.bartosh@intel.com>
=> travis: speedup git clones of ostree and buildah

.travis.yml
travis: don't use sudo for buildah builds
=> Use buildah without sudo

.travis.yml
As buildah is built with TAGS="" it should work without ostree.
Thanks @mythi for the suggestion!
=> travis: don't build ostree

demo/readme.md
Add GPU plugin demo description and link to the video.
=> GPU plugin demo description and link

cmd/qat_plugin/qat_plugin.go, cmd/qat_plugin/qat_plugin_test.go
Environment variables based on number of devices requested in a container(e.g. QAT0, QAT1)
=> Improving consumption of devices by updating the environment variable name

demo/readme.md
Signed-off-by: MCamp859 <maryx.camp@intel.com>
=> Add TOC and other minor text edits to demo readme.

demo/readme.md, demo/screencast-qat-dpdk.sh
Description and link to demo screencast for QAT Device Plugin with DPDK deployment.
=> QAT Device Plugin with DPDK demo description and link

demo/readme.md
@nolancon @swatisehgal please review. 
Signed-off-by: MCamp859 <maryx.camp@intel.com>
=> Added QAT DPDK demo to ToC

demo/readme.md
=> Improved GPU demo video link to have an image

DEVEL.md
@rojkov Please review my changes to be sure the text is still technically accurate. 
Signed-off-by: MCamp859 <maryx.camp@intel.com>
=> Minor text edits to devel.md.

demo/openssl-qat-engine/Dockerfile.clear
Adds a Dockerfile for Clear Linux
=> Add clearlinux dockerfile

Gopkg.lock, cmd/fpga_crihook/main.go
=> Pass correct PCI bus/device/function to fpgaconf

deployments/fpga_plugin/build-initcontainer-image.sh, deployments/fpga_plugin/intel-fpga-initcontainer.Dockerfile
- Updated OpenCL SDK runtime to 1.2 release
- Minimize result container image
Note: this will reduce image after #190 to ~160Mb.
=> Update for init container image

build/docker/intel-qat-plugin.Dockerfile
@rojkov please validate in your setups
=> User ClearLinux as base builder image

pkg/deviceplugin/server.go
I've been working with device plugins which are by design able to restart (e.g. rolling a new DaemonSet) and I found that the socket never truly shuts down.
This commit adds a stop mechanism which causes the gRPC server to terminate rather than restart.
=> server.Stop() shuts down the socket rather than restarting it.

Jenkinsfile
=> Jenkinsfile: change credentialsId

deployments/fpga_admissionwebhook/deployment-tpl.yaml, deployments/fpga_plugin/fpga_plugin.yaml, deployments/gpu_plugin/gpu_plugin.yaml, deployments/qat_dpdk_app/base/crypto-perf-dpdk-pod-requesting-qat.yaml, deployments/qat_plugin/qat_plugin.yaml, deployments/qat_plugin/qat_plugin_kernel_mode.yaml
@bart0sh can you help with FPGA testing?
I've checked QAT and GPU. They run OK after this change and
```
root@intel-qat-plugin-fgmbn/ # touch /usr/bin/foobar
touch: cannot touch '/usr/bin/foobar': Read-only file system
```
=> deployments: set readOnlyRootFilesystem

README.md
NOTE: this might make sense to cherry-pick into release-0.15 branch as well
=> Add release-0.15 to the releases table

Jenkinsfile, Makefile, scripts/jenkins/Makefile, scripts/jenkins/qat/Makefile, scripts/jenkins/qat/logs.sh, scripts/jenkins/qat/plugin-deploy.sh, scripts/jenkins/qat/tc-deploy.sh
This commit adds bash scripts with the proper granularity for each sub-stage,
needed for QAT device main stage validation.
squash for #231 
Signed-off-by: Rivera Gonzalez, Julio C <julio.c.rivera.gonzalez@intel.com>
=> Add CI Jenkins stage with test case for intel-device-plugin: QAT

scripts/webhook-deploy.sh
Get rid of calling sed 2 times.
=> nitpicking

build/docker/intel-fpga-admissionwebhook.Dockerfile, cmd/fpga_admissionwebhook/fpga_admissionwebhook.go, deployments/fpga_admissionwebhook/deployment-tpl.yaml, deployments/fpga_admissionwebhook/service.yaml, scripts/webhook-deploy.sh
This PR changes webhook deployment to run its container with non-root user privileges.
=> Secure fpga weebhook

cmd/gpu_plugin/README.md
Expand and update the GPU plugin README.
=> gpu: doc: update README

demo/screencast-fpga-orchestrated.sh
Made the screencast to work with OPAE and DFL kernel drivers.
=> fpga: update screencast to work with both kernel drivers

Makefile, test/e2e/e2e_test.go
The tests can be run with
```
$ make test-e2e
```
Closes #158
Depends on #245
=> Add e2e tests for fpga_admissionwebhook

cmd/qat_plugin/README.md
Update the QAT README. Add some descriptions. Add information about
the command line and config options.
=> qat: docs: Update the README

README.md
Add a godoc badge pointing to the deviceplugin API
=> docs: README: add a godoc badge

cmd/vpu_plugin/README.md
Just follow the standard format to fix the vpu plugin readme.
Also added the ubuntu OpenVINO demo job long logs.
=> vpu: refactor the vpu plugin readme

Jenkinsfile
=> Jenkinsfile: make BMaaS stage opt-in

.travis.yml, Jenkinsfile
=> ci: update tool versions

scripts/webhook-create-signed-cert.sh
Setting --output-dir DIR enables writing contents of the secret to DIR
instead of creating the secret in the cluster. This allows creating
the secret later, for instance during fpga_plugin kustomization.
Signed-off-by: Antti Kervinen <antti.kervinen@intel.com>
=> fpga_plugin: add --output-dir to webhook-create-signed-cert

build/docker/intel-vpu-plugin.Dockerfile
=> images: vpu: set Clear Linux version

README.md
- fix broken link to project releases page
- add release 0.17 to the supported releases table
=> update supported releases table

.github/workflows/ci.yaml, Makefile
=> ci: add github actions

build/docker/intel-qat-plugin.Dockerfile, demo/openssl-qat-engine/Dockerfile
=> openssl-qat-engine: update QAT stack versions

README.md
=> README: switch to Github Actions badge

cmd/vpu_plugin/vpu_plugin.go, cmd/vpu_plugin/vpu_plugin_test.go
Move to using klog for logging and debug for vpu plugin.
=> vpu: move to using klog

cmd/fpga_plugin/fpga_plugin.go, cmd/fpga_plugin/fpga_plugin_test.go
increased FPGA plugin test coverage to 77.2%
=> fpga plugin: increase test coverage

cmd/vpu_plugin/vpu_plugin.go, cmd/vpu_plugin/vpu_plugin_test.go
Changed code a little bit to improve test coverage:
* call Scan in test code
* call Scan without hddl socket
* call Scan with 0 SharedDevNum
* move SharedDevNum in newDevicePlugin
* use Ticker instead of Sleep
=> vpu: improve test coverage

cmd/qat_plugin/dpdkdrv/dpdkdrv.go
=> qat: fix UIO mounts

cmd/fpga_plugin/fpga_plugin.go, cmd/gpu_plugin/gpu_plugin.go, cmd/gpu_plugin/gpu_plugin_test.go
=> gpu: increase code coverage for unit tests

.golangci.yml, cmd/fpga_crihook/main_test.go, cmd/fpga_plugin/fpga_plugin_test.go, cmd/gpu_plugin/gpu_plugin_test.go, cmd/qat_plugin/dpdkdrv/dpdkdrv.go, cmd/qat_plugin/dpdkdrv/dpdkdrv_test.go, pkg/topology/topology_test.go
=> linter: enable gosec check

.golangci.yml, cmd/fpga_tool/fpga_tool.go
=> fpga_tool: enable nakedret check

demo/readme.md
1, added a second fpga device plugin demo using OpenCL workload
2, updated screencast thumbnail image from png to svg to show play buttons, and resized them to fit on screen better
=> Add FPGA OpenCL Demo Screencast

demo/readme.md, demo/screencast-fpga-orchestrated.sh, demo/screencast-fpga-preprogrammed.sh, demo/test-fpga-orchestrated.yaml
Updated FPGA demo screencasts:
- used latest kustomize setup
- got rid of cloning github repository
- renamed test-fpga-region.yaml -> demo/test-fpga-orchestrated.yaml
- updated readme
=> fpga: update demo

README.md, scripts/set-version.sh
=> add release 0.18 to the supported releases table

test/e2e/fpga/fpga.go
=> e2e: fix FPGA tests

build/docker/intel-qat-plugin.Dockerfile, cmd/qat_plugin/README.md, demo/openssl-qat-engine/Dockerfile
=> qat: update QAT software stack

.github/workflows/ci.yaml, build/docker/intel-sgx-initcontainer.Dockerfile, build/docker/intel-sgx-plugin.Dockerfile, cmd/sgx_epchook/main.go, cmd/sgx_plugin/README.md, cmd/sgx_plugin/sgx_plugin.go, cmd/sgx_plugin/sgx_plugin_test.go, demo/intelsgx-job.yaml, demo/sgx-sdk-demo/Dockerfile, deployments/sgx_plugin/base/intel-sgx-hookinstall.yaml, deployments/sgx_plugin/base/intel-sgx-plugin.yaml, deployments/sgx_plugin/base/kustomization.yaml, deployments/sgx_plugin/kustomization.yaml, deployments/sgx_plugin/overlays/nfd/kustomization.yaml, deployments/sgx_plugin/overlays/nfd/nfd-master.yaml, deployments/sgx_plugin/overlays/nfd/nfd-worker-daemonset.yaml, deployments/sgx_plugin/overlays/nfd/nfd-worker.conf, go.mod, go.sum
Add a new plugin for exposing SGX resources. Also, add a NFD source hook for counting SGX EPC memory.
=> sgx: add new plugin.

cmd/gpu_plugin/README.md
Move remark about GVT-d to end of introduction. Remove remarks
about GVT-g for the time being.
=> gpu_plugin: README.md update

.golangci.yml, cmd/qat_plugin/kerneldrv/kerneldrv.go, cmd/vpu_plugin/vpu_plugin_test.go, pkg/deviceplugin/api.go, pkg/deviceplugin/server.go, pkg/deviceplugin/server_test.go, pkg/topology/topology.go, pkg/topology/topology_test.go
=> linter: enable staticcheck

.golangci.yml, cmd/qat_plugin/kerneldrv/kerneldrv_test.go, cmd/sgx_plugin/sgx_plugin_test.go, pkg/deviceplugin/manager.go, pkg/deviceplugin/manager_test.go, pkg/deviceplugin/server_test.go, pkg/fpga/bitstream/gbs.go, pkg/fpga/devtypes_test.go, test/envtest/fpgadeviceplugin_controller_test.go, test/envtest/gpudeviceplugin_controller_test.go, test/envtest/qatdeviceplugin_controller_test.go
=> lint: enable errcheck

DEVEL.md, README.md, cmd/fpga_crihook/README.md, cmd/fpga_plugin/README.md, cmd/fpga_tool/README.md, cmd/gpu_plugin/README.md, cmd/qat_plugin/README.md, cmd/sgx_plugin/README.md
=> sync README.md files with the current state of the code

test/e2e/deviceplugins_suite_test.go, test/e2e/sgx/sgx.go
=> SGX: add basic e2e tests

README.md, build/docker/intel-deviceplugin-operator.Dockerfile, build/docker/intel-fpga-admissionwebhook.Dockerfile, build/docker/intel-fpga-initcontainer.Dockerfile, build/docker/intel-fpga-plugin.Dockerfile, build/docker/intel-gpu-plugin.Dockerfile, build/docker/intel-qat-plugin.Dockerfile, build/docker/intel-sgx-initcontainer.Dockerfile, build/docker/intel-sgx-plugin.Dockerfile, build/docker/intel-vpu-plugin.Dockerfile, scripts/copy-modules-licenses.sh
=> images: distribute copyleft sources

DEVEL.md, README.md, cmd/fpga_admissionwebhook/README.md, cmd/fpga_crihook/README.md, cmd/fpga_plugin/README.md, cmd/fpga_tool/README.md, cmd/gpu_plugin/README.md, cmd/operator/README.md, cmd/qat_plugin/README.md, cmd/sgx_plugin/README.md, cmd/vpu_plugin/README.md, demo/readme.md
As requested, header and link changes broken into separate PR. Based on PR: #446 
Signed-off-by: Kevin Putnam <kevin.putnam@intel.com>
=> Documentation: Fixes broken links and standardizes headers.

.github/workflows/publish.yml
Closes: #399 
/cc @intelkevinputnam
=> ci: add a github action to generate and publish docs

Makefile, README.md, build/docker/intel-deviceplugin-operator.Dockerfile, build/docker/intel-fpga-admissionwebhook.Dockerfile, build/docker/intel-fpga-initcontainer.Dockerfile, build/docker/intel-fpga-plugin.Dockerfile, build/docker/intel-gpu-plugin.Dockerfile, build/docker/intel-qat-plugin.Dockerfile, build/docker/intel-vpu-plugin.Dockerfile, demo/crypto-perf/Dockerfile, demo/intelfpga-job.yaml, demo/opae-nlb-demo/Dockerfile, demo/openssl-qat-engine/Dockerfile, demo/test-fpga-orchestrated.yaml, demo/test-fpga-preprogrammed.yaml, deployments/fpga_admissionwebhook/manager/manager.yaml, deployments/fpga_plugin/base/intel-fpga-plugin-daemonset.yaml, deployments/gpu_plugin/base/intel-gpu-plugin.yaml, deployments/operator/manager/manager.yaml, deployments/operator/samples/deviceplugin_v1_gpudeviceplugin.yaml, deployments/operator/samples/deviceplugin_v1_qatdeviceplugin.yaml, deployments/qat_dpdk_app/base/crypto-perf-dpdk-pod-requesting-qat.yaml, deployments/qat_plugin/base/intel-qat-kernel-plugin.yaml, deployments/qat_plugin/base/intel-qat-plugin.yaml, deployments/vpu_plugin/base/intel-vpu-plugin.yaml, scripts/copy-modules-licenses.sh
=> release-0.18: image updates

pkg/webhooks/sgx/sgx.go
=> sgx webhook: implement quote generation logic

Makefile, README.md, cmd/fpga_admissionwebhook/README.md, cmd/fpga_plugin/README.md, cmd/operator/README.md
=> update to cert-manager v1.0.3

cmd/fpga_admissionwebhook/README.md, cmd/operator/README.md
=> improve docs for no_proxy

.github/workflows/ci.yaml, demo/sgx-aesmd-demo/Dockerfile, deployments/operator/samples/deviceplugin_v1_sgxdeviceplugin.yaml, deployments/sgx_aesmd/base/aesmd.conf, deployments/sgx_aesmd/base/intel-sgx-aesmd.yaml, deployments/sgx_aesmd/base/kustomization.yaml, deployments/sgx_aesmd/base/sgx_default_qcnl.conf, deployments/sgx_aesmd/kustomization.yaml
=> SGX remote attestation

README.md, cmd/sgx_plugin/README.md, deployments/sgx_enclave_apps/base/intelsgx-job.yaml, deployments/sgx_enclave_apps/base/kustomization.yaml, deployments/sgx_enclave_apps/overlays/sgx_ecdsa_aesmd_quote/change_workingdir_and_command.json, deployments/sgx_enclave_apps/overlays/sgx_ecdsa_aesmd_quote/kustomization.yaml, deployments/sgx_enclave_apps/overlays/sgx_ecdsa_inproc_quote/add_hostnetwork.yaml, deployments/sgx_enclave_apps/overlays/sgx_ecdsa_inproc_quote/add_sgx_default_qcnl_conf.yaml, deployments/sgx_enclave_apps/overlays/sgx_ecdsa_inproc_quote/kustomization.yaml, deployments/sgx_enclave_apps/overlays/sgx_ecdsa_inproc_quote/sgx_default_qcnl.conf
=> SGX documentation

build/docker/intel-qat-plugin.Dockerfile, demo/openssl-qat-engine/Dockerfile
=> openssl-qat-engine: update component versions

go.mod, go.sum
=> go.mod: update gousb to v1.1.0

Jenkinsfile
Use of parallel creates race possibility as installation of
go happens in one part but is used in another.
=> Jenkinsfile: do not use parallel method

pkg/webhooks/sgx/sgx.go
Start using a k8s 1.19 feature to report warnings from webhooks. Sample output:
```
$ kubectl run nginx --image=nginx --limits 'sgx.intel.com/enclave=1'
Warning: sgx.intel.com/enclave should not be used in Pod spec directly
pod/nginx created
```
TODO:
=> sgx: add warnings to webhook

deployments/fpga_admissionwebhook/crd/bases/fpga.intel.com_acceleratorfunctions.yaml, deployments/fpga_admissionwebhook/crd/bases/fpga.intel.com_fpgaregions.yaml, deployments/fpga_admissionwebhook/webhook/manifests.yaml, deployments/operator/crd/bases/deviceplugin.intel.com_fpgadeviceplugins.yaml, deployments/operator/crd/bases/deviceplugin.intel.com_gpudeviceplugins.yaml, deployments/operator/crd/bases/deviceplugin.intel.com_qatdeviceplugins.yaml, deployments/operator/crd/bases/deviceplugin.intel.com_sgxdeviceplugins.yaml, deployments/operator/crd/bases/fpga.intel.com_acceleratorfunctions.yaml, deployments/operator/crd/bases/fpga.intel.com_fpgaregions.yaml, deployments/operator/webhook/manifests.yaml, pkg/apis/deviceplugin/v1/fpgadeviceplugin_webhook.go, pkg/apis/deviceplugin/v1/gpudeviceplugin_webhook.go, pkg/apis/deviceplugin/v1/qatdeviceplugin_webhook.go, pkg/apis/deviceplugin/v1/sgxdeviceplugin_webhook.go, pkg/fpgacontroller/patcher/patchermanager.go, pkg/webhooks/sgx/sgx.go
The new versions adds `admissionReviewVersions` annotation and makes it mandatory.
=> upgrade controller-gen to v0.4.1

cmd/sgx_plugin/README.md, cmd/sgx_plugin/sgx_plugin.go, cmd/sgx_plugin/sgx_plugin_test.go, demo/sgx-sdk-demo/Dockerfile, deployments/sgx_plugin/base/intel-sgx-plugin.yaml, pkg/controllers/sgx/controller.go
=> SGX v4x updates

README.md, demo/readme.md, demo/screencast-sgx.sh
=> add SGX screencast script

demo/crypto-perf/run-dpdk-test
=> crypto-perf: update inclusive language

cmd/qat_plugin/dpdkdrv/dpdkdrv.go
Minor code clean-up to prepare for bigger rework in `scan()` needed for #451
=> QAT: cleanup

cmd/fpga_crihook/testdata/config-correct.json, cmd/fpga_crihook/testdata/config-no-FPGA-devices.json, cmd/fpga_crihook/testdata/config-no-afu.json, cmd/fpga_crihook/testdata/config-no-devices.json, cmd/fpga_crihook/testdata/config-no-env.json, cmd/fpga_crihook/testdata/config-no-process.json, cmd/fpga_crihook/testdata/config-no-region.json, cmd/fpga_crihook/testdata/config-non-existing-bitstream.json, cmd/fpga_crihook/testdata/config-region-afu-dont-match.json, pkg/topology/topology.go
=> language cleanup

deployments/fpga_admissionwebhook/webhook/manifests.yaml, deployments/operator/crd/bases/deviceplugin.intel.com_fpgadeviceplugins.yaml, deployments/operator/crd/bases/deviceplugin.intel.com_gpudeviceplugins.yaml, deployments/operator/crd/bases/deviceplugin.intel.com_qatdeviceplugins.yaml, deployments/operator/crd/bases/deviceplugin.intel.com_sgxdeviceplugins.yaml, deployments/operator/webhook/manifests.yaml, go.mod, go.sum, pkg/apis/deviceplugin/v1/fpgadeviceplugin_webhook.go, pkg/apis/deviceplugin/v1/gpudeviceplugin_webhook.go, pkg/apis/deviceplugin/v1/qatdeviceplugin_webhook.go, pkg/apis/deviceplugin/v1/sgxdeviceplugin_webhook.go, pkg/fpgacontroller/patcher/patchermanager.go, pkg/fpgacontroller/patcher/patchermanager_test.go, pkg/webhooks/sgx/sgx.go
Validated using `make test-with-kind`.
=> Move to Admission v1 API

deployments/operator/samples/deviceplugin_v1_fpgadeviceplugin.yaml, deployments/operator/samples/deviceplugin_v1_gpudeviceplugin.yaml, deployments/operator/samples/deviceplugin_v1_qatdeviceplugin.yaml, deployments/operator/samples/deviceplugin_v1_sgxdeviceplugin.yaml, pkg/apis/deviceplugin/v1/fpgadeviceplugin_types.go
=> operator: extend sample configs to include all possible specs

Makefile, build/docker/intel-deviceplugin-operator.Dockerfile, build/docker/intel-dsa-plugin.Dockerfile, build/docker/intel-fpga-admissionwebhook.Dockerfile, build/docker/intel-fpga-initcontainer.Dockerfile, build/docker/intel-fpga-plugin.Dockerfile, build/docker/intel-gpu-initcontainer.Dockerfile, build/docker/intel-gpu-plugin.Dockerfile, build/docker/intel-qat-plugin.Dockerfile, build/docker/intel-sgx-initcontainer.Dockerfile, build/docker/intel-sgx-plugin.Dockerfile, build/docker/intel-vpu-plugin.Dockerfile, cmd/qat_plugin/dpdkdrv/dpdkdrv_test.go
=> qat: run TestScanPrivate tests in parallel

.github/workflows/ci.yaml, cmd/dsa_plugin/README.md, demo/dsa-accel-config-demo-pod.yaml, demo/dsa-accel-config-demo/Dockerfile
- Impelemented demo image that runs accel-config tests
- Added testing instructions to the documentation
=> implement DSA demo

cmd/qat_plugin/README.md, deployments/qat_plugin/overlays/sriov_numvfs/sriov_numvfs_init.yaml
=> qat: add note about vfio-pci module parameters

README.md
=> README: add information about vulnerability reporting

.github/workflows/publish.yml, README.md, conf.py
Closes: #514 
/cc @intelkevinputnam does this look right?
=> README: fix links and add docs for release-0.19

cmd/fpga_plugin/README.md
=> fpga_plugin-readme; changed one instance of master to main.

cmd/fpga_admissionwebhook/README.md
=> fpga_admissionwebhook README.md; changed master to main

cmd/operator/README.md
Related to PR499. Signed-off-by: DougTW <doug.martin@intel.com>
=> Edited operator README. Changed 1 instance of master to main, line 78.

cmd/gpu_plugin/README.md
=> edited gpu_plugin README; changed 2 instances of master to main.

demo/crypto-perf/Dockerfile
Line 8 replaced 'master' with 'main'. Related to issue 499.
=> Edited demo crypto-perf dockerfile. 

demo/opae-nlb-demo/Dockerfile
Replaced 'master' with 'main' on line 8. Related to issue 499.
=> Edited demo opae-nlb-demo dockerfile. 

.github/workflows/ci.yaml, .github/workflows/publish.yml, README.md, cmd/dsa_plugin/README.md, conf.py
=> ci: drop master branch from workflow trigggers

DEVEL.md
=> doc: add checklist for new device plugins

deployments/operator/manifests/bases/intel-device-plugins-operator.clusterserviceversion.yaml
Synchronize sources for the operator's CSV with the update to the currently published version:  https://github.com/operator-framework/community-operators/pull/3187
=> operator: add categories to meta data

deployments/operator/samples/deviceplugin_v1_qatdeviceplugin.yaml
=> qat: fix QatDevicePlugin CR sample entry

.github/workflows/ci.yaml, README.md, build/docker/intel-sgx-admissionwebhook.Dockerfile, cmd/sgx_admissionwebhook/README.md, cmd/sgx_admissionwebhook/main.go, deployments/sgx_admissionwebhook/base/kustomization.yaml, deployments/sgx_admissionwebhook/base/manager_webhook_patch.yaml, deployments/sgx_admissionwebhook/certmanager/certificate.yaml, deployments/sgx_admissionwebhook/certmanager/kustomization.yaml, deployments/sgx_admissionwebhook/certmanager/kustomizeconfig.yaml, deployments/sgx_admissionwebhook/default/kustomization.yaml, deployments/sgx_admissionwebhook/default/namespace.yaml, deployments/sgx_admissionwebhook/manager/kustomization.yaml, deployments/sgx_admissionwebhook/manager/manager.yaml, deployments/sgx_admissionwebhook/overlays/default-with-certmanager/kustomization.yaml, deployments/sgx_admissionwebhook/overlays/default-with-certmanager/webhookcainjection_patch.yaml, deployments/sgx_admissionwebhook/webhook/kustomization.yaml, deployments/sgx_admissionwebhook/webhook/kustomizeconfig.yaml, deployments/sgx_admissionwebhook/webhook/manifests.yaml, deployments/sgx_admissionwebhook/webhook/service.yaml
=> sgx: add separate admissionwebhook image

PROJECT, deployments/operator/manifests/bases/intel-device-plugins-operator.clusterserviceversion.yaml, deployments/operator/samples/kustomization.yaml
This PR contains changes that were made to publish operator v0.20.0 on the operator hub: https://operatorhub.io/operator/intel-device-plugins-operator
It makes sense to also do these changes for release-0.20 branch in my opinion
=> published operator v0.20.0

cmd/gpu_plugin/gpu_plugin.go, cmd/gpu_plugin/gpu_plugin_test.go
This adds better GPU plugin functionality unit testing coverage, and fixes few minor issues the new tests revealed in the plugin & its test code.  Fix commits are before testing updates so that all commits pass existing tests. Copyright is also updated suitably.
EDIT:  removed this part as we couldn't agree on how it should be implemented: "Testing of command line options was missing earlier. Adding that will also help in minimizing testing changes for future pull requests."
=> Gpu plugin testing improvements

pkg/fpga/pci_linux.go, pkg/fpga/utils.go
=> pkg/fpga: detect driver attached to a PCI device

build/docker/intel-fpga-initcontainer.Dockerfile, build/docker/intel-gpu-initcontainer.Dockerfile, build/docker/intel-sgx-initcontainer.Dockerfile, build/docker/intel-vpu-plugin.Dockerfile, build/docker/toybox-config
=> part 2 of the distroless/static move

cmd/gpu_plugin/README.md
=> gpu_plugin: add documentation links to gpu aware scheduling

Makefile, cmd/gpu_nfdhook/labeler.go, cmd/gpu_nfdhook/labeler_test.go, cmd/gpu_plugin/gpu_plugin.go, cmd/internal/pluginutils/sriov.go
=> add pf skip to gpu nfdhook

cmd/gpu_plugin/README.md
This adds a section heading, TOC link, command line flag description
and a short explanation of what other dependent configuration
changes are needed with fractional resources in order for the command
line flag to achieve something useful.
=> more documentation for fractional resources

.github/workflows/publish.yml, Makefile, README.md, demo/crypto-perf/Dockerfile, demo/intelfpga-job.yaml, demo/opae-nlb-demo/Dockerfile, demo/test-fpga-orchestrated.yaml, demo/test-fpga-preprogrammed.yaml, deployments/dsa_plugin/base/intel-dsa-plugin.yaml, deployments/fpga_admissionwebhook/manager/manager.yaml, deployments/fpga_plugin/base/intel-fpga-plugin-daemonset.yaml, deployments/gpu_plugin/base/intel-gpu-plugin.yaml, deployments/gpu_plugin/overlays/fractional_resources/add-args.yaml, deployments/operator/manager/manager.yaml, deployments/operator/samples/deviceplugin_v1_dsadeviceplugin.yaml, deployments/operator/samples/deviceplugin_v1_fpgadeviceplugin.yaml, deployments/operator/samples/deviceplugin_v1_gpudeviceplugin.yaml, deployments/operator/samples/deviceplugin_v1_qatdeviceplugin.yaml, deployments/operator/samples/deviceplugin_v1_sgxdeviceplugin.yaml, deployments/qat_dpdk_app/base/crypto-perf-dpdk-pod-requesting-qat.yaml, deployments/qat_plugin/base/intel-qat-kernel-plugin.yaml, deployments/qat_plugin/base/intel-qat-plugin.yaml, deployments/sgx_admissionwebhook/manager/manager.yaml, deployments/sgx_plugin/base/intel-sgx-plugin.yaml, deployments/sgx_plugin/overlays/epc-nfd/add-epc-nfd-initcontainer.yaml, deployments/sgx_plugin/overlays/epc-register/init-daemonset.yaml, deployments/vpu_plugin/base/intel-vpu-plugin.yaml
=> images: release 0.21.0

.github/workflows/publish.yml, README.md, deployments/operator/samples/deviceplugin_v1_dsadeviceplugin.yaml, deployments/operator/samples/deviceplugin_v1_fpgadeviceplugin.yaml, deployments/operator/samples/deviceplugin_v1_gpudeviceplugin.yaml, deployments/operator/samples/deviceplugin_v1_qatdeviceplugin.yaml, deployments/operator/samples/deviceplugin_v1_sgxdeviceplugin.yaml
=> add 0.21 release information

cmd/fpga_admissionwebhook/README.md, cmd/fpga_plugin/README.md
=> webhook: document mappings deployment

DEVEL.md, Makefile, deployments/operator/manifests/bases/intel-device-plugins-operator.clusterserviceversion.yaml
Set of improvements and documentation updates for the operator publishing procedure.
Fixes: #672
=> Updates made during the latest operator publishing

build/docker/intel-qat-plugin-kerneldrv.Dockerfile
this resolves the conflict in https://github.com/intel/intel-device-plugins-for-kubernetes/issues/681
Closes: #681
=> Update qat driver in qat plugin image

Makefile, test/e2e/deviceplugins_suite_test.go, test/e2e/fpgaadmissionwebhook/fpgaadmissionwebhook.go, test/e2e/qat/qatplugin_dpdk.go, test/e2e/sgxadmissionwebhook/sgxaadmissionwebhook.go, test/e2e/utils/utils.go
=> e2e improvements

demo/screencast-sgx.sh
=> demo: update SGX screencast script

cmd/gpu_plugin/rm/gpu_plugin_resource_manager.go, cmd/internal/pluginutils/sriov.go
=> gpu rm linter comment fixes

deployments/operator/samples/deviceplugin_v1_qatdeviceplugin.yaml, pkg/controllers/qat/controller.go, test/envtest/qatdeviceplugin_controller_test.go
- Copied annotations from the QAT device plugin CR to the QAT deployment
- Tested with envtest
Fixes: #645
=> qat: copy annotations

cmd/gpu_nfdhook/labeler.go, cmd/gpu_nfdhook/labeler_test.go
This changes the memory reading to be done through lmem_total_bytes
file instead of the addr_range file.
=> gpu nfdhook: new memory amount reading logic

cmd/qat_plugin/README.md, deployments/operator/samples/deviceplugin_v1_qatdeviceplugin.yaml, deployments/qat_plugin/base/intel-qat-plugin-config.yaml
=> qat: set c6xxvf and 4xxxvf to default devices

.github/CODEOWNERS
=> codeowners: update VPU, DLB, and FPGA owners

README.md, cmd/operator/README.md
=> README: add that operator supports for DSA and DLB plugins

.github/workflows/ci.yaml, Jenkinsfile
=> ci:Add envtest

cmd/sgx_plugin/README.md
=> sgx: update README

deployments/fpga_plugin/base/intel-fpga-plugin-daemonset.yaml, deployments/qat_plugin/base/intel-qat-kernel-plugin.yaml, deployments/qat_plugin/base/intel-qat-plugin.yaml, deployments/sgx_plugin/base/intel-sgx-plugin.yaml, pkg/controllers/dlb/controller.go, pkg/controllers/dsa/controller.go, pkg/controllers/dsa/controller_test.go, pkg/controllers/fpga/controller.go, pkg/controllers/fpga/controller_test.go, pkg/controllers/gpu/controller.go, pkg/controllers/gpu/controller_test.go, pkg/controllers/qat/controller.go, pkg/controllers/qat/controller_test.go, pkg/controllers/sgx/controller.go, pkg/controllers/sgx/controller_test.go
In order to make controllers consistent, I add a nodeselector constraint of daemonset to dlb, fpga, qat too.
=> operator: add node selection constraint (amd64 arch)

test/e2e/utils/utils.go
=> e2e: wait longer in DeployWebhook

cmd/dlb_plugin/README.md
Add info on how to configure dlb driver and vfs.
-For commands that need superuser access, I used $ sudo than #, since # is used for comment and it does not look nice.
-Though the sysfs such as /sys/bus/pci/devices/0000:6d:00.0 may be different in another machine, I thought it would be more clear to just give a specific example than explaning.
=> dlb: update README

pkg/webhooks/sgx/sgx.go, test/e2e/sgxadmissionwebhook/sgxaadmissionwebhook.go
Do not add Volume or VolumeMount definitions in case they already exist in the Pod spec.
=> sgx-webhook: do not add Volume(Mount)s if they exist.

cmd/qat_plugin/dpdkdrv/dpdkdrv.go, cmd/qat_plugin/dpdkdrv/dpdkdrv_test.go
=> qat: rework device binding

pkg/webhooks/sgx/sgx.go, test/e2e/sgxadmissionwebhook/sgxaadmissionwebhook.go
The changes made by addVolumeMount() were overriden when the
intermediate container variable was assigned to the pod and
thus the volumeMount changes were lost.
Fix it by making the volumeMount changes to the intermediate
container that is then assigned to the final pod.
Also, make the latest e2e test case to use the
checkMutatedVolumes() helper and fix the illegal Volume
name.
Signed-off-by: Ismo Puustinen <ismo.puustinen@intel.com>
=> sgx: fix volumeMounts mutation

deployments/qat_plugin/overlays/apparmor_unconfined/add-apparmor-unconfined-intel-qat.yaml, deployments/qat_plugin/overlays/e2e/add-args.yaml, deployments/qat_plugin/overlays/e2e/kustomization.yaml, test/e2e/qat/qatplugin_dpdk.go
e2e combines all existing overlays: apparmor, debug, and sriov_numfs.
=> qat: add kustomize overlay for e2e tests

deployments/sgx_plugin/overlays/epc-hook-initcontainer/add-epc-nfd-initcontainer.yaml, deployments/sgx_plugin/overlays/epc-hook-initcontainer/kustomization.yaml, test/e2e/sgx/sgx.go
=> e2e: sgx: fix NFD and webhook deployment

build/docker/intel-fpga-initcontainer.Dockerfile, build/docker/intel-gpu-initcontainer.Dockerfile, build/docker/intel-sgx-initcontainer.Dockerfile, build/docker/toybox-config
=> images: update toybox to v0.8.6

.github/workflows/publish.yml, README.md
=> main: docs: create documentation for v0.23 release

cmd/gpu_nfdhook/README.md
Label descriptions had extra underscores.
=> README typofix

.github/workflows/e2e-fpga.yml, .github/workflows/e2e-qat.yml, .github/workflows/e2e-sgx.yml
Nightly builds should hopefully help to catch regressions faster.
Fixes: #763
=> e2e workflows: schedule nightly builds

cmd/qat_plugin/dpdkdrv/dpdkdrv.go, cmd/qat_plugin/dpdkdrv/dpdkdrv_test.go
=> qat: detect noiommu mode with VFIO

deployments/fpga_admissionwebhook/crd/bases/fpga.intel.com_acceleratorfunctions.yaml, deployments/fpga_admissionwebhook/crd/bases/fpga.intel.com_fpgaregions.yaml, deployments/fpga_admissionwebhook/rbac/role.yaml, deployments/fpga_admissionwebhook/webhook/manifests.yaml, deployments/operator/crd/bases/deviceplugin.intel.com_dlbdeviceplugins.yaml, deployments/operator/crd/bases/deviceplugin.intel.com_dsadeviceplugins.yaml, deployments/operator/crd/bases/deviceplugin.intel.com_fpgadeviceplugins.yaml, deployments/operator/crd/bases/deviceplugin.intel.com_gpudeviceplugins.yaml, deployments/operator/crd/bases/deviceplugin.intel.com_qatdeviceplugins.yaml, deployments/operator/crd/bases/deviceplugin.intel.com_sgxdeviceplugins.yaml, deployments/operator/crd/bases/fpga.intel.com_acceleratorfunctions.yaml, deployments/operator/crd/bases/fpga.intel.com_fpgaregions.yaml, deployments/operator/rbac/gpu_manager_role.yaml, deployments/operator/rbac/role.yaml, deployments/operator/webhook/manifests.yaml, pkg/apis/deviceplugin/v1/dsadeviceplugin_types.go
=> dsa: make initImage spec consistent with other APIs

.github/workflows/e2e-fpga.yml, .github/workflows/e2e-qat.yml, .github/workflows/e2e-sgx.yml
reverting as test environment is not ready for this due
to hitting docker hub pull limit
This reverts commit 0141827e7937673200f15be51ba847c58e4ebc2b.
=> Revert "e2e: enable triggering hw jobs on PRs"

Makefile, test/e2e/gpu/gpu.go
=> add device check to gpu e2e test and e2e-gpu makefile target

scripts/copy-modules-licenses.sh, scripts/set-image-pull-policy.sh, scripts/set-version.sh, scripts/update-clear-linux-base.sh
=> scripts: fix shellcheck errors

.github/workflows/e2e-fpga.yml, .github/workflows/e2e-qat.yml, .github/workflows/e2e-sgx.yml
Moved list of images to the environment variable
to allow accessing it from scheduled nightly runs
=> e2e actions: fix nightly runs

build/docker/intel-idxd-config-initcontainer.Dockerfile, demo/opae-nlb-demo/Dockerfile
=> images: update license obligations

.github/workflows/ci.yaml, Jenkinsfile, Makefile
<Commit 1> Makefile: add target 'install-tools'
Target 'install-tools' installs:
- controller-gen
- golangci-lint
- kind
Closes: #623
<Commit 2> Makefile: update target 'test-with-kind'
- Update target to use go for installing KinD
- Use Docker to build images
- Add e2e test for SGX admission webhook
- Add deployment of oeprator
- Add a test for operator deployment
<Commit 3> tests: add tests with github actions (test-with-kind)
Closes: #613
=> tests: add tests with github actions (kind) & Makefile: remove 'test-with-kind'

cmd/operator/README.md, deployments/nfd/kustomization.yaml, deployments/nfd/node-feature-rules.yaml, deployments/operator/samples/deviceplugin_v1_dlbdeviceplugin.yaml, deployments/operator/samples/deviceplugin_v1_dsadeviceplugin.yaml, deployments/operator/samples/deviceplugin_v1_fpgadeviceplugin.yaml, deployments/operator/samples/deviceplugin_v1_gpudeviceplugin.yaml, deployments/operator/samples/deviceplugin_v1_qatdeviceplugin.yaml, deployments/operator/samples/deviceplugin_v1_sgxdeviceplugin.yaml
- added labeling rules for all supported devices
- updated operator installation instructions
Fixes: #768
=> operator: implement NFD labelling rules

cmd/fpga_admissionwebhook/README.md, cmd/fpga_plugin/README.md, cmd/operator/README.md, cmd/qat_plugin/README.md, cmd/sgx_admissionwebhook/README.md, cmd/sgx_plugin/README.md, deployments/qat_dpdk_app/base/crypto-perf-dpdk-pod-requesting-qat.yaml
=> crypto-perf and cert-manager updates

build/docker/intel-deviceplugin-operator.Dockerfile, build/docker/intel-dlb-plugin.Dockerfile, build/docker/intel-dsa-plugin.Dockerfile, build/docker/intel-fpga-admissionwebhook.Dockerfile, build/docker/intel-fpga-initcontainer.Dockerfile, build/docker/intel-fpga-plugin.Dockerfile, build/docker/intel-gpu-initcontainer.Dockerfile, build/docker/intel-gpu-plugin.Dockerfile, build/docker/intel-qat-plugin.Dockerfile, build/docker/intel-sgx-admissionwebhook.Dockerfile, build/docker/intel-sgx-initcontainer.Dockerfile, build/docker/intel-sgx-plugin.Dockerfile, scripts/set-version.sh
Added `LABEL`s (name, vendor, version, release, summary, description) to all plugins and updated `scripts/set-version.sh` script to include the `LABEL version='<image-tag>'` by passing TAG parameter to `make set-version TAG=<image-tag>`
=> Images/Script - Added LABELs to all plugins

pkg/fpgacontroller/patcher/patcher.go, pkg/fpgacontroller/patcher/patcher_test.go
Webhook's patcher currently can't be re-applied to its output because it
rejects containers with the env vars it adds (e.i. FPGA_AFU_* and
FPGA_REGION_*).
Instead of rejecting container with disallowed env vars just reset them
first upon patching.
Closes #863
=> fpga_webhook: make patcher idempotent

cmd/dlb_plugin/README.md, demo/dlb-dpdk-demo/Dockerfile, demo/dlb-libdlb-demo/Dockerfile
=> dlb: update the link to dlb driver

Makefile, demo/dlb-libdlb-demo/Dockerfile, demo/openssl-qat-engine/Dockerfile, demo/sgx-aesmd-demo/Dockerfile, demo/sgx-sdk-demo/Dockerfile
=> demo: update openssl-qat-engine image

README.md
=> README: document registered resources

.github/workflows/ci.yaml, cmd/gpu_plugin/README.md, demo/intel-opencl-icd/Dockerfile, demo/intelgpu-job.yaml
=> demo: add intel-opencl-icd

Makefile, scripts/test-image-base-layer.sh
=> ci: test image base layer before push

.github/workflows/e2e-gpu.yml
=> add e2e-gpu workflow

cmd/operator/README.md
=> doc: fix operator usage instructions

Makefile
Delete trailing whitespace and tabify
Signed-off-by: Ruslan Mstoi <ruslan.mstoi@intel.com>
=> Makefile: whitespace fixes

cmd/gpu_plugin/gpu_plugin.go
=> gpu: fix typo in implmentation of preferredAllocator interface

.github/workflows/ci.yaml, .github/workflows/e2e-qat.yml, build/docker/intel-qat-initcontainer.Dockerfile, build/docker/toybox-config, demo/qat-init.sh, deployments/operator/crd/bases/deviceplugin.intel.com_qatdeviceplugins.yaml, deployments/operator/samples/deviceplugin_v1_qatdeviceplugin.yaml, deployments/qat_plugin/overlays/sriov_numvfs/sriov_numvfs_init.yaml, pkg/apis/deviceplugin/v1/qatdeviceplugin_types.go, pkg/apis/deviceplugin/v1/qatdeviceplugin_webhook.go, pkg/controllers/qat/controller.go, test/envtest/qatdeviceplugin_controller_test.go, test/envtest/suite_test.go
=> qat: add initimage to plugin

.gitignore
=> iaa: add built binary to gitignore

.gitignore, Makefile, README.md, charts/README.md, charts/operator/.helmignore, charts/operator/Chart.yaml, charts/operator/templates/NOTES.txt, charts/operator/values.yaml, scripts/set-version.sh
Signed-off-by: Ruslan Mstoi <ruslan.mstoi@intel.com>
=> Add helm charts

.github/workflows/ci.yaml, Jenkinsfile
=> ci: update to Go 1.18.1

demo/opae-nlb-demo/Dockerfile
This should hopefully fix libjson-c issue #904
=> opae-nlb-demo: switch to Debian unstable

demo/sgx-aesmd-demo/Dockerfile, demo/sgx-sdk-demo/Dockerfile
=> demo: update SGX images

cmd/dsa_plugin/README.md, cmd/iaa_plugin/README.md
=> dsa: Update the documentation on ConfigMap creation

DEVEL.md, Makefile, deployments/operator/manifests/bases/intel-device-plugins-operator.clusterserviceversion.yaml
=> operator deployment: move from packagemanifests to bundle

build/docker/intel-idxd-config-initcontainer.Dockerfile, demo/idxd-init.sh, deployments/dsa_plugin/overlays/dsa_initcontainer/dsa_initcontainer.yaml, deployments/iaa_plugin/overlays/iaa_initcontainer/iaa_initcontainer.yaml, pkg/controllers/dsa/controller.go, pkg/controllers/iaa/controller.go
=> idxd: Don't use root filesystem when working with templates

charts/operator/templates/operator.yaml, charts/operator/values.yaml
Signed-off-by: Ruslan Mstoi <ruslan.mstoi@intel.com>
=> Helm chart: add operator

demo/openssl-qat-engine/Dockerfile
=> openssl-qat-engine: move to use qatlib

Jenkinsfile
=> release-0.24: ci: fix wrong image TAG for kind tests

cmd/sgx_plugin/README.md, cmd/sgx_plugin/sgx_plugin.go, deployments/sgx_plugin/base/intel-sgx-plugin.yaml, pkg/controllers/sgx/controller_test.go
=> sgx: deprecate /dev/sgx/ mounts

Makefile, charts/sgx/.helmignore, charts/sgx/Chart.yaml, charts/sgx/templates/sgx.yaml, charts/sgx/values.yaml
Signed-off-by: Ruslan Mstoi <ruslan.mstoi@intel.com>
=> Helm chart: add SGX CR

.github/workflows/ci.yaml, Jenkinsfile
this should fix failing terrascan check and Jenkins job.
=> use curl -L to handle redirections

.github/CODEOWNERS
=> codeowners: update new owners

.github/workflows/ci.yaml, Jenkinsfile
=> priority: ci: use buildah from the distro

Makefile
=> Makefile: remove unused variable and update operator version to 0.24.0

.github/workflows/e2e-dsa.yml, Makefile, demo/dsa-accel-config-demo-pod.yaml, demo/dsa-accel-config-demo/Dockerfile, demo/dsa-accel-config-demo/idxd-reset.patch, demo/dsa-accel-config-demo/test_runner_disable_shared_queues.patch, scripts/set-version.sh, test/e2e/deviceplugins_suite_test.go, test/e2e/dsa/dsa.go
=> dsa: Add e2e tests

cmd/dlb_plugin/README.md, demo/dlb-dpdk-demo/Dockerfile, demo/dlb-libdlb-demo/Dockerfile
=> dlb: update driver version to new release

README.md
Reviewed Readme for clarity, brand names, and line character limits.
Amy Benich requested my review, I am also working with Serge Lunev on this project.
=> README Review

docs/extensions.rst
=> docs: fix table of contents for static docs

DEVEL.md, deployments/operator/manifests/bases/intel-device-plugins-operator.clusterserviceversion.yaml
=> operator: update csv spec (maintainer, replaces) and publishing instruction

.github/workflows/e2e-dlb.yml, Makefile, demo/dlb-libdlb-demo-pf-pod.yaml, demo/dlb-libdlb-demo-vf-pod.yaml, demo/dlb-libdlb-demo/test.sh, scripts/set-version.sh, test/e2e/dlb/dlb.go
This PR is going to contain everything needed to enable triggering DLB e2e testing on simulated SPR target
Fixes: #948
=> Implement DLB CI

demo/openssl-qat-engine/Dockerfile
I'm working on adding Asynch Mode NGINX into this...
=> openssl-qat-engine: add NGINX

pkg/controllers/reconciler_test.go
=> operator: TestUpgrade: make expected*Image to follow ImageMinVersion

.github/workflows/ci.yaml, Jenkinsfile, docs/requirements.txt
=> ci: fix docs generation and update envtest to use k8s v1.24.2

demo/openssl-qat-engine/Dockerfile
=> openssl-qat-engine: update qatlib and QAT engine versions

Makefile, deployments/fpga_admissionwebhook/crd/bases/fpga.intel.com_acceleratorfunctions.yaml, deployments/fpga_admissionwebhook/crd/bases/fpga.intel.com_fpgaregions.yaml, deployments/operator/crd/bases/deviceplugin.intel.com_dlbdeviceplugins.yaml, deployments/operator/crd/bases/deviceplugin.intel.com_dsadeviceplugins.yaml, deployments/operator/crd/bases/deviceplugin.intel.com_fpgadeviceplugins.yaml, deployments/operator/crd/bases/deviceplugin.intel.com_gpudeviceplugins.yaml, deployments/operator/crd/bases/deviceplugin.intel.com_iaadeviceplugins.yaml, deployments/operator/crd/bases/deviceplugin.intel.com_qatdeviceplugins.yaml, deployments/operator/crd/bases/deviceplugin.intel.com_sgxdeviceplugins.yaml, deployments/operator/crd/bases/fpga.intel.com_acceleratorfunctions.yaml, deployments/operator/crd/bases/fpga.intel.com_fpgaregions.yaml, deployments/operator/rbac/role.yaml, pkg/controllers/reconciler.go
=> deployments: regenerate using the latest controller-gen

cmd/sgx_plugin/README.md
Polish the document to avoid issue https://github.com/intel/intel-device-plugins-for-kubernetes/issues/1098
=> Add kind deployment notes for aesmd pod

charts/operator/templates/operator.yaml, charts/operator/values.yaml
- update and move controller args to helm variables (values.yaml)
- update kube-rback-proxy image to 0.8.0
=> helm: update operator chart

deployments/nfd/base/kustomization.yaml
=> deployments: move to NFD v0.11.1

charts/qat/.helmignore, charts/qat/Chart.yaml, charts/qat/templates/NOTES.txt, charts/qat/templates/qat.yaml, charts/qat/values.yaml
=> QAT helm chart

deployments/nfd/overlays/node-feature-rules/node-feature-rules-openshift.yaml, deployments/nfd/overlays/node-feature-rules/node-feature-rules.yaml, deployments/operator/samples/deviceplugin_v1_iaadeviceplugin.yaml
=> deployments: Add IAA NodeFeatureRule

test/envtest/dlbdeviceplugin_controller_test.go, test/envtest/dsadeviceplugin_controller_test.go, test/envtest/fpgadeviceplugin_controller_test.go, test/envtest/gpudeviceplugin_controller_test.go, test/envtest/iaadeviceplugin_controller_test.go, test/envtest/qatdeviceplugin_controller_test.go, test/envtest/sgxdeviceplugin_controller_test.go, test/envtest/suite_test.go
=> envtest: Fix upgrade test fail when the tests for CRUD operations fail

cmd/gpu_plugin/gpu_plugin.go
Current GPU count log is misleading (pretty much completely wrong).  This PR corrects that.
=> More detailed log for number of found GPU devices / resource types

test/e2e/utils/utils.go
Added testssl.sh switches to add more tests
Closes: #1103
=> e2e: update testssl.parameters and logging

.github/workflows/e2e-qat4.yml, Makefile, demo/openssl-qat-engine-cpa-sample-pod.yaml, scripts/set-version.sh, test/e2e/qat/qatplugin_qatgen4_crypto.go
=> qat: Add e2e tests

DEVEL.md, cmd/fpga_plugin/README.md, cmd/qat_plugin/README.md
=> docs: fix remaining review comments

README.md, cmd/gpu_plugin/README.md
=> gpu: add mentions about data center gpu support

cmd/qat_plugin/dpdkdrv/dpdkdrv.go, cmd/qat_plugin/dpdkdrv/dpdkdrv_test.go
=> qat: read device capabilities from sysfs

cmd/fpga_admissionwebhook/main.go, cmd/operator/README.md, cmd/sgx_admissionwebhook/main.go, deployments/fpga_admissionwebhook/rbac/kustomization.yaml, deployments/fpga_admissionwebhook/rbac/leader_election_role.yaml, deployments/fpga_admissionwebhook/rbac/leader_election_role_binding.yaml
=> Update SGX and FPGA webhook flags

DEVEL.md, build/docker/build-image.sh, demo/build-image.sh
=> build: add BUILDER=podman

cmd/gpu_plugin/README.md, deployments/gpu_plugin/overlays/nfd_labeled_nodes/add-nodeselector-intel-gpu.yaml, deployments/nfd/components/gpu/kustomization.yaml, deployments/nfd/components/gpu/master-args.yaml, deployments/nfd/components/gpu/master-rbac.yaml, deployments/nfd/overlays/gpu/kustomization.yaml
=> gpu: Improve installation options and documentation

deployments/qat_plugin/base/intel-qat-plugin.yaml, pkg/controllers/qat/controller.go, pkg/controllers/qat/controller_test.go
Add the SELinux labels for QAT plugins.
Signed-off-by: Manish Regmi <manish.regmi@intel.com>
=> add selinux labels for QAT

deployments/dlb_plugin/base/intel-dlb-plugin.yaml, deployments/dsa_plugin/base/intel-dsa-plugin.yaml, deployments/iaa_plugin/base/intel-iaa-plugin.yaml, deployments/qat_plugin/base/intel-qat-plugin.yaml, deployments/sgx_plugin/base/intel-sgx-plugin.yaml, deployments/vpu_plugin/base/intel-vpu-plugin.yaml, pkg/controllers/dlb/controller_test.go, pkg/controllers/dsa/controller_test.go, pkg/controllers/iaa/controller_test.go, pkg/controllers/sgx/controller_test.go
=> deployments: disable unused serviceAccounts for plugins

README.md, cmd/qat_plugin/README.md, cmd/sgx_plugin/README.md
=> docs: move away from 01.org doc links

pkg/apis/deviceplugin/v1/gpudeviceplugin_webhook.go
=> operator: gpu: prevent use of resourcemanager without shared devices

cmd/gpu_plugin/README.md
DKMS packages seem to be now published in addition to user-space driver packages.
=> Add information on new DKMS kernel GPU driver packages

cmd/gpu_plugin/README.md
Include the image building and pushing in the steps. Also notes about the need to modify the job yaml.
Closes: #1173
=> gpu: improve demo run instructions

build/docker/intel-deviceplugin-operator.Dockerfile, build/docker/intel-dlb-initcontainer.Dockerfile, build/docker/intel-dlb-plugin.Dockerfile, build/docker/intel-dsa-plugin.Dockerfile, build/docker/intel-fpga-admissionwebhook.Dockerfile, build/docker/intel-fpga-initcontainer.Dockerfile, build/docker/intel-fpga-plugin.Dockerfile, build/docker/intel-gpu-initcontainer.Dockerfile, build/docker/intel-gpu-plugin.Dockerfile, build/docker/intel-iaa-plugin.Dockerfile, build/docker/intel-idxd-config-initcontainer.Dockerfile, build/docker/intel-qat-initcontainer.Dockerfile, build/docker/intel-qat-plugin-kerneldrv.Dockerfile, build/docker/intel-qat-plugin.Dockerfile, build/docker/intel-sgx-admissionwebhook.Dockerfile, build/docker/intel-sgx-initcontainer.Dockerfile, build/docker/intel-sgx-plugin.Dockerfile, build/docker/intel-vpu-plugin.Dockerfile, build/docker/lib/default_build.docker, build/docker/lib/final_base.docker, build/docker/lib/toybox_build.docker, build/docker/templates/intel-idxd-config-initcontainer.Dockerfile.in, build/docker/templates/intel-qat-initcontainer.Dockerfile.in, build/docker/templates/intel-qat-plugin-kerneldrv.Dockerfile.in, build/docker/templates/intel-vpu-plugin.Dockerfile.in, demo/crypto-perf/Dockerfile, demo/opae-nlb-demo/Dockerfile
=> dockerfile fixes after hadolint scan

.github/workflows/ci.yaml
=> ci: update terrascan install location

test/e2e/dlb/dlb.go, test/e2e/dsa/dsa.go, test/e2e/fpga/fpga.go, test/e2e/gpu/gpu.go, test/e2e/iaa/iaa.go, test/e2e/qat/qatplugin_kernel.go, test/e2e/sgx/sgx.go
=> e2e: add securityContext check to see if rootfs is read-only

cmd/iaa_plugin/README.md
=> iaa: fix readme to have correct web links

deployments/operator/default/manager_auth_proxy_patch.yaml
=> operator: update kube-rbac-proxy image

cmd/operator/main.go, deployments/operator/manager/manager.yaml
=> operator: add support for Liveness and Readiness probes

.github/workflows/build-push.yml
pushing to ghcr.io, this time with added workflow instead of modifying main CI flow.
=> build images and push into ghcr.io registry

cmd/iaa_plugin/README.md, demo/iaa-qpl-demo-pod.yaml
=> iaa: fix the name of the demo image

cmd/gpu_nfdhook/labeler.go, cmd/gpu_nfdhook/labeler_test.go
Numa labeling only worked when card numbering started from 0.
=> fix gpu nfdhook numa labeling

README.md, cmd/qat_plugin/README.md
=> qat: minor doc updates

cmd/gpu_fakedev/configs/8x-DG1.json
Reminder to myself: do commit cleanups before testing, not afterwards...
=> Fix typo in gpu_fakedev example config

build/docker/intel-idxd-config-initcontainer.Dockerfile, build/docker/templates/intel-idxd-config-initcontainer.Dockerfile.in, demo/accel-config-demo/Dockerfile, demo/accel-config-demo/test_runner_disable_shared_queues.patch, demo/iaa-qpl-demo/Dockerfile
(some work I had forgotten to push)
=> demo: update accel-config 3.5.2

cmd/dlb_plugin/README.md, cmd/dsa_plugin/README.md, cmd/fpga_plugin/README.md, cmd/iaa_plugin/README.md, cmd/operator/README.md, cmd/qat_plugin/README.md, cmd/sgx_plugin/README.md, cmd/vpu_plugin/README.md
=> Update README kubectl applies for zsh support

cmd/gpu_plugin/rm/gpu_plugin_resource_manager_test.go
In preparation for grpc 1.52.0.
=> test: gpu: add fake target for grpc.Dial

build/docker/intel-dlb-initcontainer.Dockerfile, build/docker/templates/intel-dlb-initcontainer.Dockerfile.in
=> dlb: make dockerfile to have init script in /usr/local/bin

.github/CODEOWNERS
To help with reviews for dependabot&k8s version upgrades.
=> Add myself into additional CODEOWNERS targets

.github/workflows/e2e.yml, cmd/dlb_plugin/README.md, demo/dlb-dpdk-demo/Dockerfile, demo/dlb-libdlb-demo/Dockerfile
=> dlb: update DLB to v8.0.0

build/docker/intel-gpu-fakedev.Dockerfile
Add generated Dockerfile for intel-gpu-fakedev, like with all the other images.
=> Add generated Dockerfile for intel-gpu-fakedev

.github/workflows/e2e.yml, test/e2e/sgx/sgx.go
=> operator: Add e2e tests for SGX

cmd/sgx_plugin/README.md, demo/openssl-qat-engine/Dockerfile, deployments/nfd/overlays/node-feature-rules/node-feature-rules.yaml, deployments/sgx_plugin/overlays/epc-nfd/kustomization.yaml
Fixes: #1325
Fixes: #1333
Fixes: #1347
=> more little fixes

cmd/qat_plugin/README.md, cmd/qat_plugin/dpdkdrv/dpdkdrv.go, demo/qat-init.sh, deployments/nfd/overlays/node-feature-rules/node-feature-rules-openshift.yaml, deployments/nfd/overlays/node-feature-rules/node-feature-rules.yaml, pkg/controllers/qat/controller.go
Based on
https://lore.kernel.org/linux-crypto/20230303165650.81405-1-damian.muszynski@intel.com/
=> qat: add support for QAT 402xx

test/e2e/dlb/dlb.go, test/e2e/dsa/dsa.go, test/e2e/iaa/iaa.go, test/e2e/qat/qatplugin_dpdk.go, test/e2e/qat/qatplugin_kernel.go
=> e2e: device plugin gets deleted before next one is deployed

test/e2e/dsa/dsa.go, test/e2e/qat/qatplugin_dpdk.go, test/e2e/qat/qatplugin_kernel.go
=> e2e: fix aftereach to be in the correct location

test/e2e/qat/qatplugin_dpdk.go
runTests=4 is dsa test, and it does not run anything for now. So, use runTests=2, which is RSA decrypt test
=> qat,e2e: fix e2e test for cy

deployments/operator/manager/manager.yaml
=> operator: increase memory resources to 100/120Mi

cmd/xpumanager_sidecar/README.md, cmd/xpumanager_sidecar/main.go, cmd/xpumanager_sidecar/main_test.go
-Adapt to allow xe-links that are not on subdevices
-Support https for xpu-manager connection
=> Xpum sidecar updates

test/e2e/utils/utils.go
=> e2e: fix webhook TLS tests

.github/workflows/e2e.yml
This reverts commit d65fab6fb7a222c860927e47c4c159e0c517f553.
=> Revert "disable gpu e2e test temporarily"

.github/workflows/trivy-periodic.yaml
To fix token-permissions score.
=> workflow: add root permissions for periodic trivy

build/docker/intel-deviceplugin-operator.Dockerfile, build/docker/intel-dlb-initcontainer.Dockerfile, build/docker/intel-dlb-plugin.Dockerfile, build/docker/intel-dsa-plugin.Dockerfile, build/docker/intel-fpga-admissionwebhook.Dockerfile, build/docker/intel-fpga-initcontainer.Dockerfile, build/docker/intel-fpga-plugin.Dockerfile, build/docker/intel-gpu-fakedev.Dockerfile, build/docker/intel-gpu-initcontainer.Dockerfile, build/docker/intel-gpu-levelzero.Dockerfile, build/docker/intel-gpu-plugin.Dockerfile, build/docker/intel-iaa-plugin.Dockerfile, build/docker/intel-qat-initcontainer.Dockerfile, build/docker/intel-qat-plugin-kerneldrv.Dockerfile, build/docker/intel-qat-plugin.Dockerfile, build/docker/intel-sgx-admissionwebhook.Dockerfile, build/docker/intel-sgx-initcontainer.Dockerfile, build/docker/intel-sgx-plugin.Dockerfile, build/docker/intel-xpumanager-sidecar.Dockerfile, build/docker/lib/default_labels.docker
=> Added new LABEL maintainer to device plugin container images
